// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Tool Calling Type Definitions
 *
 * These types define a unified interface for AI tool/function calling
 * that works across all supporting providers (Claude, OpenAI, Gemini, etc.)
 *
 * Tools are defined using OpenAI-compatible JSON Schema format,
 * then transformed to provider-specific formats server-side.
 */
import type { AIProvider, AnalyzeTeamRunSummary, ToolResultProvenance } from '../../../types';
export type JSONSchemaType = 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'null';
export interface JSONSchemaProperty {
    type: JSONSchemaType | JSONSchemaType[];
    description?: string;
    enum?: (string | number | boolean)[];
    items?: JSONSchemaProperty;
    properties?: Record<string, JSONSchemaProperty>;
    required?: string[];
    default?: unknown;
    minLength?: number;
    maxLength?: number;
    minimum?: number;
    maximum?: number;
    pattern?: string;
    format?: string;
}
export interface JSONSchema {
    type: 'object';
    properties: Record<string, JSONSchemaProperty>;
    required?: string[];
    additionalProperties?: boolean;
}
/** Category of tool functionality */
export type ToolCategory = 'web' | 'data' | 'files' | 'compute';
/**
 * Definition of a tool that can be called by AI models.
 * Uses OpenAI-compatible format as the canonical representation.
 */
export interface ToolDefinition {
    /** Unique identifier for the tool (e.g., "fetch_url") */
    name: string;
    /** Human-readable description shown to AI for tool selection */
    description: string;
    /** JSON Schema defining the tool's parameters */
    parameters: JSONSchema;
    /** Category for UI organization and filtering */
    category: ToolCategory;
    /**
     * Where this tool executes:
     * - 'client': Runs in the browser (e.g., file parsing, SQL)
     * - 'server': Runs via Firebase callable function (name must match tool name)
     * - 'orchestrator': Handled by the Analyze orchestrator itself (delegate)
     */
    execution: 'client' | 'server' | 'orchestrator';
    /**
     * If specified, only these providers can use this tool.
     * If undefined, all providers with function support can use it.
     */
    supportedProviders?: AIProvider[];
    /** Whether the tool requires user confirmation before execution */
    requiresConfirmation?: boolean;
    /** Maximum execution time in milliseconds (default: 30000) */
    timeout?: number;
}
/**
 * A tool call requested by an AI model.
 * The AI returns this structure when it wants to invoke a tool.
 */
export interface ToolCall {
    /** Unique ID for this specific call (provider-generated) */
    id: string;
    /** Type of the call - always 'function' for our tools */
    type: 'function';
    /** The function/tool being called */
    function: {
        /** Name of the tool to invoke */
        name: string;
        /** JSON string of the arguments */
        arguments: string;
    };
    /**
     * Provider data that must go back with this call in later history, as the
     * proxy returned it (Gemini thinking models: the call's thought signature).
     */
    extra_content?: {
        google?: {
            thought_signature?: string;
        };
    };
}
/**
 * Parsed tool call with arguments already decoded.
 * Used internally after parsing the AI's response.
 */
export interface ParsedToolCall {
    /** Unique ID for this call */
    id: string;
    /** Name of the tool to invoke */
    name: string;
    /** Parsed arguments object */
    arguments: Record<string, unknown>;
}
/**
 * Result of executing a tool call.
 * This is sent back to the AI in a follow-up request.
 */
export interface ToolResult {
    /** ID of the tool call this result corresponds to */
    toolCallId: string;
    /** Whether the execution was successful */
    success: boolean;
    /** The result content (for successful executions) */
    content?: string;
    /** Error message (for failed executions) */
    error?: string;
    /** Generated images (for execute_python with matplotlib) */
    images?: Array<{
        mimeType: string;
        base64: string;
    }>;
    /** Interactive HTML outputs (Bokeh, Altair charts from execute_python) */
    htmlOutputs?: Array<{
        content: string;
        filename?: string;
    }>;
    /** Data files written to /output/ (CSV, JSON, Excel, etc.) */
    dataOutputs?: Array<{
        filename: string;
        base64: string;
        size: number;
    }>;
    /** Explicitly assembled HTML bundles from /output/ files */
    bundleOutputs?: Array<{
        name?: string;
        manifest: {
            version: 1;
            entryPoint: string;
            files: Record<string, {
                mimeType: string;
                content: string;
                isBase64?: boolean;
                size: number;
            }>;
        };
        sourceFiles: string[];
    }>;
    /** Provenance metadata for fetched external data (fetch_api/fetch_url) */
    provenance?: ToolResultProvenance;
    /** Additional metadata about the execution */
    metadata?: {
        /** Execution time in milliseconds */
        executionTime?: number;
        /** Whether result was truncated due to size */
        truncated?: boolean;
        /** Original content length before truncation */
        originalLength?: number;
        /** Cache hit indicator */
        cached?: boolean;
        /** Full stdout output for UI display (not sent to AI) */
        fullStdout?: string;
        /** Original fetched content size in bytes (for fetch_url/fetch_api UI display) */
        fetchedBytes?: number;
        /** Team tools: the sub-agent runs this call started (saved on the result message). */
        teamRuns?: AnalyzeTeamRunSummary[];
    };
}
/**
 * Controls how the AI should handle tool calling.
 *
 * - 'auto': AI decides whether to use tools (default)
 * - 'none': AI must not call any tools
 * - 'required': AI must call at least one tool
 * - { name: string }: AI must call the specific named tool
 */
export type ToolChoice = 'auto' | 'none' | 'required' | {
    name: string;
};
/**
 * Settings for individual tool enablement.
 */
export interface ToolSettings {
    /** Tool name */
    name: string;
    /** Whether this tool is enabled */
    enabled: boolean;
    /** Optional per-tool configuration */
    config?: Record<string, unknown>;
}
/**
 * Global tool settings for a user/session.
 */
export interface ToolSettingsConfig {
    /** Master switch to enable/disable all tools */
    enabled: boolean;
    /** Settings for individual tools */
    tools: Record<string, ToolSettings>;
    /** Default tool choice when tools are enabled */
    defaultToolChoice: ToolChoice;
}
/**
 * Default tool settings configuration.
 */
export declare const DEFAULT_TOOL_SETTINGS: ToolSettingsConfig;
/**
 * Request to execute a tool on the server.
 */
export interface ToolExecutionRequest {
    /** The tool call to execute */
    toolCall: ParsedToolCall;
    /** User ID for authorization */
    userId: string;
    /** Optional session context */
    sessionId?: string;
}
/**
 * State of a tool execution (for UI tracking).
 */
export type ToolExecutionState = 'pending' | 'executing' | 'completed' | 'failed';
/**
 * Progress information for ongoing tool execution.
 */
export interface ToolExecutionProgress {
    /** ID of the tool call */
    toolCallId: string;
    /** Current state */
    state: ToolExecutionState;
    /** Tool being executed */
    toolName: string;
    /** Start time */
    startedAt: number;
    /** Completion time (if finished) */
    completedAt?: number;
    /** Progress message for UI display */
    message?: string;
}
/**
 * Streaming event for tool-related updates.
 */
export interface ToolStreamEvent {
    type: 'tool_call_start' | 'tool_call_delta' | 'tool_call_complete' | 'tool_result';
    /** Tool call ID */
    toolCallId?: string;
    /** Tool name (for start events) */
    toolName?: string;
    /** Partial arguments (for delta events) */
    argumentsDelta?: string;
    /** Complete tool call (for complete events) */
    toolCall?: ToolCall;
    /** Tool result (for result events) */
    result?: ToolResult;
}
/**
 * Parse the JSON arguments string from a tool call.
 */
export declare function parseToolCallArguments(toolCall: ToolCall): ParsedToolCall;
/**
 * Check if a provider supports function calling.
 */
export declare function providerSupportsFunctions(provider: AIProvider): boolean;
/**
 * Format a tool result for display in the UI.
 */
export declare function formatToolResultForDisplay(result: ToolResult): string;
