// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export type DebateFormatId = 'oxford' | 'lincoln_douglas' | 'policy';
export type SelectableDebateFormatId = DebateFormatId;
export type DebateSideId = 'aff' | 'neg';
export type DebateVoteModel = 'checkpoint' | 'audience_stance';
export type DebateTeamMode = 'duel' | 'team';
export type AudienceStance = 'for' | 'against' | 'undecided';
export type AudienceVoteStage = 'initial' | 'final';
export type OxfordAudienceQuestions = Record<DebateSideId, string>;
export interface AudienceQuestionCheckpoint {
    afterMessageIndex: number;
    required: true;
}
export interface AudienceDecisionResult {
    initialStance: AudienceStance;
    finalStance: Exclude<AudienceStance, 'undecided'>;
    winningSide: DebateSideId;
    winningSideLabel: string;
    resultVerb: 'persuaded' | 'held' | 'flipped';
    summary: string;
    winningParticipantIds: string[];
}
export type PhaseId = 'opening' | 'constructive' | 'cross_examination' | 'rebuttal' | 'final_rebuttal' | 'question' | 'closing';
export interface MessageSpec {
    label: string;
    phase: PhaseId;
    speaker: DebateSideId;
    speakerSlot?: number;
    cxRole?: 'questioner' | 'answerer';
    audienceQuestionTarget?: DebateSideId;
    voteAfter?: boolean;
    votingLabel?: string;
}
export interface PresetConfig {
    id: string;
    label: string;
    shortLabel: string;
    description: string;
    messages: MessageSpec[];
    voteCount: number;
    voteModel?: DebateVoteModel;
    teamMode?: DebateTeamMode;
    teamSize?: number;
    initialVoteRequired?: boolean;
    finalVoteRequired?: boolean;
    audienceQuestionCheckpoint?: AudienceQuestionCheckpoint;
}
export interface FormatSpec {
    id: DebateFormatId;
    name: string;
    description: string;
    stepLabel: 'Rounds' | 'Speeches';
    presets: PresetConfig[];
    guidance: Partial<Record<PhaseId, string>>;
}
export declare const OXFORD_FORMAT: FormatSpec;
export declare const LINCOLN_DOUGLAS_FORMAT: FormatSpec;
export declare const POLICY_FORMAT: FormatSpec;
export declare const FORMATS: Record<DebateFormatId, FormatSpec>;
export declare function getFormat(id: DebateFormatId): FormatSpec;
export declare function getPresetForFormat(formatId: DebateFormatId, presetId: string): PresetConfig;
export declare function getPresetIdForRounds(rounds?: number): string;
