// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { ToolDefinition } from '../types';

export const assembleHtmlBundleTool: ToolDefinition = {
  name: 'assemble_html_bundle',

  description: `Legacy HTML bundle assembler.

This tool is not available for current Analyze output modes. Rich mode produces one presentational HTML artifact, and Portable mode produces only the selected non-HTML file formats.

Do not call this tool. For Rich mode, save one HTML file under /output/ with write_output_file or execute_python. For Portable mode, save only the selected portable formats.`,

  parameters: {
    type: 'object',
    properties: {
      name: {
        type: 'string',
        description: 'Optional display name for the assembled bundle artifact.',
      },
      entryPoint: {
        type: 'string',
        description: 'The main HTML file under /output, such as /output/site/index.html or site/index.html.',
      },
      files: {
        type: 'array',
        items: { type: 'string' },
        description: 'All /output files that belong in the bundle, including HTML pages, CSS, JS, images, fonts, and local data assets.',
      },
    },
    required: ['entryPoint', 'files'],
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  requiresConfirmation: false,
  timeout: 30000,
};

export interface AssembleHtmlBundleArgs {
  name?: string;
  entryPoint: string;
  files: string[];
}
