// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Execute Python Code Tool
 *
 * Runs model-written Python in the session's isolated server sandbox
 * (services/sandbox → debateai sandbox* callables). No internet access inside
 * the sandbox; data arrives through fetch_api/fetch_url into /data.
 *
 * Features:
 * - Fixed scientific package set (see the E2B template build script in debateai)
 * - Captures stdout output
 * - Captures matplotlib visualizations as images
 * - Variables and files persist for the session, including across page reloads
 */

import type { ToolDefinition } from '../types';

/**
 * Tool definition for executing Python code.
 */
export const executeCodeTool: ToolDefinition = {
  name: 'execute_python',

  description: `Execute Python 3 code in a secure, isolated sandbox with persistent session state.

SESSION PERSISTENCE:
Variables, imports, and functions persist between calls within the same session.
Define variables in one call, use them in the next.
Example workflow:
  Call 1: df = pd.read_csv('/uploads/data.csv')
  Call 2: df['value'].mean()  # df is still available!

FILE ACCESS:
- Uploaded files are at: /uploads/<filename>
- Save outputs to: /output/<filename>
- Use pd.read_csv('/uploads/data.csv') to read CSV files
- Use plt.savefig('/output/chart.png') to save figures

INSTALLED PACKAGES (fixed set - just import them; never pip install):
- numpy, pandas, matplotlib - pre-imported as np, pd, plt
- scipy, scikit-learn, statsmodels, sympy, networkx, seaborn, Pillow, scikit-image
- openpyxl, xlsxwriter - Excel read/write (pd.read_excel / df.to_excel)
- pypdf (from pypdf import PdfReader) - read and extract text from PDF files
  (scanned PDFs: page images sent as vision attachments automatically)
- python-docx (import docx), python-pptx (import pptx), reportlab
- plotly, bokeh, altair - interactive charts (HTML artifacts)
- folium - interactive Leaflet tile maps (HTML artifacts) — only when street-level pan/zoom is needed; thematic maps are Vega-Lite chart blocks
- geopandas, shapely, pyarrow, lxml, beautifulsoup4, nltk, wordcloud, xarray, astropy, biopython

MAP BOUNDARIES (for geopandas static maps; geopandas.datasets is gone):
- /opt/geo/world/ne_50m_admin_0_countries.shp - Natural Earth 1:50m countries; join on ISO_A3_EH (ISO_A3 is -99 for France and Norway), ISO_A2_EH, NAME
- /opt/geo/us/cb_2023_us_state_5m.shp - Census 2023 states; STATEFP (2-digit FIPS), STUSPS ("CA"), NAME
- /opt/geo/us/cb_2023_us_county_5m.shp - Census 2023 counties; GEOID (5-digit FIPS), NAME, STUSPS, STATE_NAME
- gpd.read_file(path); reproject for display (e.g. .to_crs(5070) for the contiguous US)

NO INTERNET ACCESS:
- requests/urllib cannot reach the web → USE fetch_api for REST APIs and fetch_url for web pages
- pip install does not work - the package set is fixed
- cv2, tensorflow, torch, pytesseract, easyocr → NOT AVAILABLE (use vision attachments for scanned PDFs)

Use this tool for:
- Calculations and mathematical operations
- Data analysis with pandas
- Visualizations with matplotlib
- Algorithms and simulations
- Processing uploaded data files

Important:
- Use print() to output results
- Save artifacts to /output/ with descriptive filenames so users can review/download them
- Variables persist - build on previous work
- Never embed tool-call syntax inside Python code (e.g., call:default/fetch_api{...} or fetch_api(...))
- Call tools separately, then read resulting files from /data/ or /uploads/ in Python
- Each call has a time limit; on timeout the code is stopped and variables are normally kept (if Python must restart, variables are cleared; files are always kept)
- Avoid infinite loops or excessive computation`,

  parameters: {
    type: 'object',
    properties: {
      code: {
        type: 'string',
        description: 'Python code to execute. Use print() for output. For visualizations, use matplotlib (figures are automatically captured).',
      },
    },
    required: ['code'],
    additionalProperties: false,
  },

  category: 'compute',

  // Dispatched by the client to the remote sandbox (services/sandbox)
  execution: 'client',

  // Available for all function-supporting providers
  supportedProviders: undefined,

  // Code execution is sandboxed, no confirmation needed
  requiresConfirmation: false,

  // 30 second timeout for computation
  timeout: 30000,
};

/**
 * Type for the execute_python tool arguments.
 */
export interface ExecuteCodeArgs {
  code: string;
}

/**
 * Type for the execute_python tool result.
 */
export interface ExecuteCodeResult {
  success: boolean;
  stdout: string;
  images?: string[];
  error?: string;
  executionTime?: number;
}

/**
 * Validate the code argument.
 */
export function validateExecuteCodeArgs(args: ExecuteCodeArgs): string[] {
  const errors: string[] = [];

  if (!args.code) {
    errors.push('Code is required');
    return errors;
  }

  if (typeof args.code !== 'string') {
    errors.push('Code must be a string');
    return errors;
  }

  // Basic sanity check - code shouldn't be too long
  if (args.code.length > 100000) {
    errors.push('Code exceeds maximum length of 100,000 characters');
  }

  return errors;
}
