// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Fetch API Tool
 *
 * Allows AI models to make authenticated HTTP requests to REST APIs.
 * Unlike fetch_url (which is for HTML pages), this tool handles structured
 * data from APIs (JSON, CSV). Supports authentication via stored API key references.
 *
 * The actual request is executed server-side in Firebase Functions
 * for security (URL validation, key resolution, response size limits).
 */

import type { ToolDefinition } from '../types';

/**
 * Tool definition for making authenticated API requests.
 */
export const fetchApiTool: ToolDefinition = {
  name: 'fetch_api',

  description: `Make authenticated HTTP requests to REST APIs. Use this for structured data from APIs (JSON, CSV), unlike fetch_url which is for HTML pages. Supports auth headers, query parameters, POST bodies, and API key references. The response (up to 25 MB; larger responses are refused) is saved as a file in /data, and you get its path and a preview.

Examples:
- Fetch stock data: fetch_api(url="https://www.alphavantage.co/query", query_params={"function":"TIME_SERIES_DAILY","symbol":"AAPL"}, api_key_ref="alpha_vantage")
- Fetch weather: fetch_api(url="https://api.weather.gov/points/39.7,-104.9")
- POST to API: fetch_api(url="...", method="POST", body={"query":"..."}, headers={"Authorization":"Bearer ..."})`,

  parameters: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
        description: 'The API endpoint URL',
      },
      method: {
        type: 'string',
        enum: ['GET', 'POST', 'PUT', 'DELETE'],
        default: 'GET',
        description: 'HTTP method (default: GET)',
      },
      headers: {
        type: 'object',
        description: 'Custom request headers (key-value pairs)',
      },
      query_params: {
        type: 'object',
        description: 'URL query parameters (key-value pairs, will be URL-encoded)',
      },
      body: {
        type: ['string', 'object'],
        description: 'Request body for POST/PUT requests (string or JSON object)',
      },
      response_format: {
        type: 'string',
        enum: ['json', 'text', 'csv'],
        default: 'json',
        description: 'Expected response format (default: json)',
      },
      api_key_ref: {
        type: 'string',
        description: 'Reference to a stored data service API key (e.g., "alpha_vantage", "openweathermap"). The key will be resolved server-side and injected into the request.',
      },
      timeout: {
        type: 'integer',
        default: 30000,
        minimum: 1000,
        maximum: 60000,
        description: 'Request timeout in milliseconds (default: 30000)',
      },
    },
    required: ['url'],
    additionalProperties: false,
  },

  category: 'data',
  execution: 'server',
  requiresConfirmation: false,
  timeout: 60000,
};

/**
 * Type for the fetch_api tool arguments.
 */
export interface FetchApiArgs {
  url: string;
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  headers?: Record<string, string>;
  query_params?: Record<string, string>;
  body?: string | Record<string, unknown>;
  response_format?: 'json' | 'text' | 'csv';
  api_key_ref?: string;
  timeout?: number;
}

/**
 * Type for the fetch_api tool response.
 */
export interface FetchApiResponse {
  status: number;
  statusText: string;
  headers?: Record<string, string>;
  data: unknown;
  contentType?: string;
  truncated?: boolean;
}

/**
 * Validate the fetch_api arguments.
 */
export function validateFetchApiArgs(args: FetchApiArgs): string[] {
  const errors: string[] = [];

  if (!args.url) {
    errors.push('URL is required');
    return errors;
  }

  // Basic URL validation
  try {
    const url = new URL(args.url);
    if (!['http:', 'https:'].includes(url.protocol)) {
      errors.push('URL must use http or https protocol');
    }
  } catch {
    errors.push('Invalid URL format');
  }

  // Validate method
  if (args.method && !['GET', 'POST', 'PUT', 'DELETE'].includes(args.method)) {
    errors.push('Method must be GET, POST, PUT, or DELETE');
  }

  // Validate timeout
  if (args.timeout !== undefined) {
    if (args.timeout < 1000 || args.timeout > 60000) {
      errors.push('Timeout must be between 1000 and 60000 milliseconds');
    }
  }

  // Validate response_format
  if (args.response_format && !['json', 'text', 'csv'].includes(args.response_format)) {
    errors.push('response_format must be json, text, or csv');
  }

  return errors;
}
