// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Fetch URL Tool
 *
 * Allows AI models to fetch and read content from web URLs.
 * The actual fetching is done server-side in Firebase Functions
 * for security (avoids CORS issues and keeps sensitive operations server-side).
 */

import type { ToolDefinition } from '../types';

/**
 * Tool definition for fetching URL content.
 */
export const fetchUrlTool: ToolDefinition = {
  name: 'fetch_url',

  description: `Fetch and read the content of a web URL. Use this tool when you need to access or analyze content from a webpage, article, documentation, or any publicly accessible URL. The tool returns the text content of the page, which you can then analyze, summarize, or extract information from.

Examples of when to use this tool:
- User asks "Summarize this article: https://example.com/news"
- User asks to "Read the documentation at https://docs.example.com/api"
- User wants to know "What does this page say about X: https://example.com/topic"
- User provides a URL and asks questions about its content

The tool handles HTML pages, plain text, and common document formats. It extracts readable text content and strips out navigation, ads, and other non-essential elements.`,

  parameters: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
        description: 'The complete URL to fetch (must start with http:// or https://)',
        pattern: '^https?://',
      },
      selector: {
        type: 'string',
        description: 'Optional CSS selector to extract specific content (e.g., "article", ".main-content", "#post-body"). If not provided, the main content will be automatically detected.',
      },
      includeMetadata: {
        type: 'boolean',
        description: 'Whether to include page metadata like title, description, and author in the response. Default: true',
        default: true,
      },
      maxLength: {
        type: 'integer',
        description: 'Maximum length of returned content in characters. Useful for very long pages. Default: 50000',
        default: 50000,
        minimum: 1000,
        maximum: 100000,
      },
    },
    required: ['url'],
    additionalProperties: false,
  },

  category: 'web',

  // Server-side execution via Firebase callable
  execution: 'server',

  // Available for all function-supporting providers
  supportedProviders: undefined,

  // URL fetching is generally safe, no confirmation needed
  requiresConfirmation: false,

  // 30 second timeout for slow pages
  timeout: 30000,
};

/**
 * Type for the fetch_url tool arguments.
 */
export interface FetchUrlArgs {
  url: string;
  selector?: string;
  includeMetadata?: boolean;
  maxLength?: number;
}

/**
 * Type for the fetch_url tool result metadata.
 */
export interface FetchUrlResultMetadata {
  title?: string;
  description?: string;
  author?: string;
  publishedDate?: string;
  siteName?: string;
  url: string;
  contentLength: number;
  fetchedAt: string;
}

/**
 * Validate the URL argument.
 */
export function validateFetchUrlArgs(args: FetchUrlArgs): string[] {
  const errors: string[] = [];

  if (!args.url) {
    errors.push('URL is required');
    return errors;
  }

  // Basic URL validation
  try {
    const url = new URL(args.url);
    if (!['http:', 'https:'].includes(url.protocol)) {
      errors.push('URL must use http or https protocol');
    }
  } catch {
    errors.push('Invalid URL format');
  }

  // Validate maxLength if provided
  if (args.maxLength !== undefined) {
    if (args.maxLength < 1000 || args.maxLength > 100000) {
      errors.push('maxLength must be between 1000 and 100000');
    }
  }

  return errors;
}
