// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Read File Tool
 *
 * Allows AI models to parse and inspect uploaded/session files with automatic
 * format detection. Faster and more reliable than Python for initial
 * file inspection. Supports CSV, JSON, Excel (.xlsx), and plain text.
 *
 * Executed client-side using PapaParse (CSV) and SheetJS (Excel).
 */

import type { ToolDefinition } from '../types';

/**
 * Tool definition for reading/parsing files already available in the session
 * virtual filesystem.
 */
export const readFileTool: ToolDefinition = {
  name: 'read_file',

  description: `Parse and read files from the session filesystem with automatic format detection. Supports files under /uploads, /output, and /data. Faster and more reliable than Python for initial file inspection. Supports CSV, JSON, Excel (.xlsx), and plain text with encoding detection. Returns structured data preview with schema information.

Use this tool to quickly inspect file contents, column names, data types, and preview rows before doing deeper analysis with execute_python. For large JSON, Markdown, HTML, CSS, or text files, use format="text" plus offset/max_chars to page through content without print() truncation.

Examples:
- read_file(path="/uploads/data.csv") - Auto-detect CSV and show preview
- read_file(path="/uploads/report.xlsx", sheet="Sheet2") - Read specific Excel sheet
- read_file(path="/uploads/config.json") - Parse JSON structure
- read_file(path="/uploads/data.csv", max_rows=5000) - Read more rows
- read_file(path="/output/_all_findings.json", format="text", offset=0, max_chars=4000) - Read a large output file in chunks`,

  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'File path in the virtual filesystem under /uploads, /output, or /data (e.g., /uploads/data.csv or /output/report.html)',
      },
      format: {
        type: 'string',
        enum: ['auto', 'csv', 'json', 'excel', 'text'],
        default: 'auto',
        description: 'File format (default: auto-detect from extension)',
      },
      sheet: {
        type: 'string',
        description: 'Excel sheet name (default: first sheet). Only used for Excel files.',
      },
      max_rows: {
        type: 'integer',
        default: 1000,
        minimum: 1,
        maximum: 10000,
        description: 'Maximum number of rows to return (default: 1000)',
      },
      encoding: {
        type: 'string',
        default: 'auto',
        description: 'Text encoding (default: auto-detect). Options: utf-8, latin1, etc.',
      },
      sample: {
        type: 'boolean',
        description: 'Return a random sample instead of first N rows for large files (default: false)',
        default: false,
      },
      offset: {
        type: 'integer',
        default: 0,
        minimum: 0,
        description: 'Character offset for text/JSON content previews (default: 0). Use with max_chars to page through large files.',
      },
      max_chars: {
        type: 'integer',
        default: 4000,
        minimum: 1,
        maximum: 5000,
        description: 'Maximum characters to return for text/JSON content previews (default: 4000, max: 5000 to avoid follow-up truncation)',
      },
    },
    required: ['path'],
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  timeout: 30000,
};

/**
 * Type for the read_file tool arguments.
 */
export interface ReadFileArgs {
  path: string;
  format?: 'auto' | 'csv' | 'json' | 'excel' | 'text';
  sheet?: string;
  max_rows?: number;
  encoding?: string;
  sample?: boolean;
  offset?: number;
  max_chars?: number;
}

/**
 * Type for the read_file tool result.
 */
export interface ReadFileResult {
  format: string;
  filename: string;
  /** Total number of rows (for tabular data) */
  totalRows?: number;
  /** Number of rows returned (may be less than total due to max_rows) */
  returnedRows?: number;
  /** Column names (for tabular data) */
  columns?: string[];
  /** Inferred column types (for tabular data) */
  columnTypes?: Record<string, string>;
  /** Data preview as array of objects (for tabular data) */
  data?: Record<string, unknown>[];
  /** Sheet names (for Excel files) */
  sheets?: string[];
  /** Active sheet name (for Excel files) */
  activeSheet?: string;
  /** Raw text content (for text/JSON files) */
  content?: string;
  /** Character offset for returned text content */
  contentOffset?: number;
  /** Character end offset for returned text content */
  contentEnd?: number;
  /** Total characters available for text content */
  totalChars?: number;
  /** JSON structure info */
  jsonType?: 'object' | 'array';
  jsonKeys?: string[];
  jsonArrayLength?: number;
  /** File size in bytes */
  fileSize?: number;
  /** Line count (for text files) */
  lineCount?: number;
  /** Whether data was sampled */
  sampled?: boolean;
  /** Whether data was truncated due to max_rows */
  truncated?: boolean;
}

/**
 * Validate the read_file arguments.
 */
export function validateReadFileArgs(args: ReadFileArgs): string[] {
  const errors: string[] = [];

  if (!args.path) {
    errors.push('File path is required');
    return errors;
  }

  // Path must stay inside the session filesystem areas exposed to analysis.
  const allowedPrefixes = ['/uploads/', '/output/', '/data/'];
  if (!allowedPrefixes.some((prefix) => args.path.startsWith(prefix))) {
    errors.push('File path must start with /uploads/, /output/, or /data/');
  }

  if (args.path.split('/').some((segment) => segment === '..')) {
    errors.push('File path cannot contain traversal segments');
  }

  // Validate max_rows
  if (args.max_rows !== undefined) {
    if (args.max_rows < 1 || args.max_rows > 10000) {
      errors.push('max_rows must be between 1 and 10000');
    }
  }

  if (args.offset !== undefined) {
    if (!Number.isInteger(args.offset) || args.offset < 0) {
      errors.push('offset must be a non-negative integer');
    }
  }

  if (args.max_chars !== undefined) {
    if (!Number.isInteger(args.max_chars) || args.max_chars < 1 || args.max_chars > 5000) {
      errors.push('max_chars must be between 1 and 5000');
    }
  }

  // Validate format
  if (args.format && !['auto', 'csv', 'json', 'excel', 'text'].includes(args.format)) {
    errors.push('format must be auto, csv, json, excel, or text');
  }

  return errors;
}
