// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Salesforce Org Evidence Request Tool
 *
 * Client tool that lets the Analyze AI pause mid-analysis and ask the user to
 * generate org-runtime evidence with a local coding agent (Claude Code/Codex +
 * Salesforce MCP / SF CLI). The app renders the request as a transcript card
 * with a copyable, check-targeted handoff prompt and an import affordance; the
 * model ends its turn after calling it and the session resumes when the user
 * imports the findings packet or declines.
 */

import type { ToolDefinition } from '../types';

export const requestSalesforceOrgEvidenceTool: ToolDefinition = {
  name: 'request_salesforce_org_evidence',

  description: `Ask the user to generate read-only Salesforce org-runtime evidence (SOQL, describes, test/diagnostic output) with their org-connected local coding agent, because the uploaded metadata alone cannot verify claims the current goal depends on. Call this AT MOST ONCE per analysis, and ONLY when goal-material claims are runtime_unverified AND org evidence would plausibly change the conclusions or recommendations — not for immaterial gaps (finalize with confidence labels instead). Never call it again after the user declines or after findings were imported. The investigation_prompt you write IS what the org-connected agent receives (the app only appends the read-only boundary and output format), so make it a real investigation brief, not a query list. Alongside the call, briefly say in your reply what you are waiting for and why: your turn ends when it runs, and the analysis resumes when the user imports the findings packet or chooses to continue without it.`,

  parameters: {
    type: 'object',
    properties: {
      reason: {
        type: 'string',
        description: 'One or two sentences for the USER: why org-runtime evidence would materially change this analysis.',
      },
      unverified_claims: {
        type: 'array',
        items: { type: 'string' },
        description: 'The specific goal-material claims that remain runtime_unverified — shown to the user on the request card.',
      },
      investigation_prompt: {
        type: 'string',
        description: 'The full brief for the ORG-CONNECTED AGENT, written as direct instructions to it (markdown). The agent CANNOT see Symposium, your analysis, its artifacts, or this conversation — it has only the local workspace source and org access — so the brief must be SELF-CONTAINED: inline every fact it needs (component names, paths, what your audit found), and never reference "the uploaded metadata analysis", "the audit above", or similar. Include: each specific QUESTION to answer and why it matters to your conclusions, what answer would change your recommendation, and concrete read-only checks (SOQL, describes, Apex test/diagnostic output) where you can specify them — but ask the agent to use its own judgment and org access to answer the questions, not just run your queries. Do NOT include deployment/mutation instructions or output-format specifications; the app appends the read-only boundary and the findings-packet contract.',
      },
    },
    required: ['reason', 'unverified_claims', 'investigation_prompt'],
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  requiresConfirmation: false,
  timeout: 15000,
};

export interface RequestSalesforceOrgEvidenceArgs {
  reason?: string;
  unverified_claims?: string[];
  investigation_prompt?: string;
}
