// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Salesforce Documentation Lookup Tool
 *
 * Server-backed evidence tool for grounding Salesforce metadata audit findings
 * in current official Salesforce documentation.
 */

import type { ToolDefinition } from '../types';
import type { SalesforceComponentType } from '../../../../services/salesforce/componentTypes';

export const salesforceDocsLookupTool: ToolDefinition = {
  name: 'salesforce_docs_lookup',

  description: `Retrieve current official Salesforce documentation. Use this whenever the analysis needs Salesforce documentation evidence — grounding claims about Salesforce features, limits, APIs, architecture, or release behavior — whether or not a Salesforce workspace was uploaded. Do NOT fetch Salesforce documentation domains with fetch_url or web_search: they serve JavaScript shells and 403s to raw fetches; this tool is the working retrieval path. It uses the official Salesforce documentation index when available, falls back to live official-domain search/fetch, returns structured documentation evidence with a citation map, reports topic coverage/missed topics, and marks preview/beta/pilot/stale-link risks so final recommendations do not rely on stale model training. After salesforce_metadata_audit runs an audit, risks, troubleshooting, feature_readiness, or handoff operation, call it before final synthesis using topics from salesforce-doc-topics.json. It does not edit metadata, deploy, or mutate any Salesforce org.`,

  parameters: {
    type: 'object',
    properties: {
      topics: {
        type: 'array',
        description: 'Salesforce documentation topics from salesforce-doc-topics.json, or concise strings such as "Apex governor limits", "Flow fault paths", or "EmailMessage ReplyToEmailMessageId behavior".',
        items: {
          type: ['object', 'string'],
          properties: {
            id: {
              type: 'string',
              description: 'Stable topic ID from salesforce-doc-topics.json.',
            },
            label: {
              type: 'string',
              description: 'Human-readable topic label.',
            },
            query: {
              type: 'string',
              description: 'Documentation search query for this topic.',
            },
            category: {
              type: 'string',
              description: 'Topic category, such as apex, flow, permissions, lwc, metadata_api, release, or imported_evidence.',
            },
          },
        },
      },
      componentTypes: {
        type: 'array',
        items: {
          type: 'string',
          enum: [
            'apex_class',
            'apex_trigger',
            'lwc_component',
            'aura_component',
            'custom_object',
            'custom_field',
            'validation_rule',
            'flow',
            'permission_set',
            'profile',
            'layout',
            'package_manifest',
            'custom_metadata',
            'unknown',
          ] satisfies SalesforceComponentType[],
        },
        description: 'Optional Salesforce metadata component types represented by the audit.',
      },
      apiVersions: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional API versions detected in metadata.',
      },
      riskSignalIds: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional static risk rule IDs to ground against documentation.',
      },
      releaseContext: {
        type: 'string',
        description: 'Optional release context from the user or audit, such as "current", "latest", "Summer 26", or "API 63". If omitted, derive context from official Salesforce release pages at runtime.',
      },
      maxResultsPerTopic: {
        type: 'integer',
        minimum: 1,
        maximum: 5,
        default: 2,
        description: 'Maximum official documentation pages to fetch per topic.',
      },
    },
    required: ['topics'],
    additionalProperties: false,
  },

  category: 'web',
  execution: 'server',
  requiresConfirmation: false,
  timeout: 90000,
};

export interface SalesforceDocsLookupTopicArg {
  id?: string;
  label?: string;
  query?: string;
  category?: string;
}

export interface SalesforceDocsLookupArgs {
  topics: Array<string | SalesforceDocsLookupTopicArg>;
  componentTypes?: SalesforceComponentType[];
  apiVersions?: string[];
  riskSignalIds?: string[];
  releaseContext?: string;
  maxResultsPerTopic?: number;
}
