// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Salesforce Metadata Audit Tool
 *
 * Read-only Analyze tool for Salesforce DX projects, metadata ZIPs, GitHub
 * source snapshots, and optional local Symposium agent insight packets
 * uploaded into the session. It never deploys, edits, or mutates an org.
 */

import type { ToolDefinition } from '../types';

export const salesforceMetadataAuditTool: ToolDefinition = {
  name: 'salesforce_metadata_audit',

  description: `Inspect uploaded Salesforce metadata in read-only mode. Use this for Salesforce DX project ZIPs, metadata ZIPs, uploaded source folders/files, or GitHub source snapshots. If the upload contains user-selected .symposium/salesforce-insights/<run-id>/manifest.json plus findings/evidence files, import those findings as optional imported agent evidence and join them to the metadata by path/component name. It builds a component inventory, dependency map, evidence ledger, Flow/Apex drilldowns, feature reference map, risk findings, troubleshooting brief, remediation backlog, feature-readiness brief, executive brief, stakeholder visual artifact plan, and engineering handoff package. Its outputs summarize the workspace; to read the source code itself (method bodies, SOQL, DML), use salesforce_read_source. It does not edit files, generate deployable patches, deploy metadata, or mutate a Salesforce org.`,

  parameters: {
    type: 'object',
    properties: {
      operation: {
        type: 'string',
        enum: ['audit', 'inventory', 'search', 'component', 'dependencies', 'risks', 'packet_findings', 'handoff', 'feature_readiness', 'troubleshooting'],
        default: 'audit',
        description: 'Audit operation to run. Use audit for the full artifact bundle, troubleshooting for pasted Flow/Apex errors or production bug reports, or packet_findings when the user specifically asks for imported agent evidence.',
      },
      paths: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional uploaded file paths such as /uploads/unpackaged.zip, /uploads/force-app/main/default/classes/Foo.cls, or a ZIP/folder containing user-selected .symposium/salesforce-insights/<run-id>/manifest.json files. If omitted, all uploaded files are scanned.',
      },
      query: {
        type: 'string',
        description: 'Search query for operation=search, pasted error/bug report for troubleshooting, or feature/change goal for feature_readiness and handoff. The audit uses this text to generate question-specific Salesforce documentation topics and feature reference maps.',
      },
      component: {
        type: 'string',
        description: 'Component name or ID for operation=component or operation=dependencies.',
      },
      include_artifacts: {
        type: 'boolean',
        default: true,
        description: 'Whether to create downloadable audit/index/dependency/handoff artifacts.',
      },
    },
    required: [],
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  requiresConfirmation: false,
  timeout: 60000,
};

export type SalesforceMetadataAuditOperation =
  | 'audit'
  | 'inventory'
  | 'search'
  | 'component'
  | 'dependencies'
  | 'risks'
  | 'packet_findings'
  | 'handoff'
  | 'feature_readiness'
  | 'troubleshooting';

export interface SalesforceMetadataAuditArgs {
  operation?: SalesforceMetadataAuditOperation;
  paths?: string[];
  query?: string;
  component?: string;
  include_artifacts?: boolean;
}
