// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Salesforce Source Reader Tool
 *
 * Read-only access to the uploaded Salesforce workspace's source text: a
 * component's or file's lines (numbered, for citations), or a search across
 * every source file. The audit's artifacts summarize the workspace; this is how
 * the operator and teammates read what the code actually does.
 */

import type { ToolDefinition } from '../types';

export const salesforceReadSourceTool: ToolDefinition = {
  name: 'salesforce_read_source',

  description: `Read the source of the uploaded Salesforce workspace (Apex classes and triggers, Flows, objects, fields, validation rules, and other metadata files), read-only. Give \`component\` (e.g. "LeadReparentingInvocable") or \`path\` to read a file with line numbers — use \`start_line\`/\`end_line\` to page through long files. Give \`pattern\` to search every source file (or only the files matching \`component\`/\`path\`) and get each matching line with its path and line number. Use it to check what code actually does — matching keys, filters, DML, Database.merge/convertLead calls, field mappings — and cite \`path:line\` for each claim. The audit's artifacts are summaries, not source: never describe logic you haven't read here.`,

  parameters: {
    type: 'object',
    properties: {
      component: {
        type: 'string',
        description: 'Component name (Apex class, trigger, Flow, object, etc.) — reads every source file for it, e.g. the .cls and its -meta.xml.',
      },
      path: {
        type: 'string',
        description: 'A source file path inside the workspace (e.g. force-app/main/default/classes/LeadSearchMatchInvocable.cls). A trailing part of the path or the file name is enough when it is unique.',
      },
      start_line: {
        type: 'number',
        description: 'First line to return (1-based). Defaults to 1.',
      },
      end_line: {
        type: 'number',
        description: 'Last line to return. Defaults to a page of lines after start_line; the result says how to read the next page.',
      },
      pattern: {
        type: 'string',
        description: 'Search instead of read: a case-insensitive regular expression (or plain text) matched against each line, e.g. "Database\\\\.(merge|convertLead)" or "Email__c".',
      },
    },
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  requiresConfirmation: false,
  timeout: 60000,
};

export interface SalesforceReadSourceArgs {
  component?: string;
  path?: string;
  start_line?: number;
  end_line?: number;
  pattern?: string;
}
