// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Web Search Tool
 *
 * Allows AI models to search the web and return a list of URLs with titles and snippets.
 * Uses Brave Search API server-side via Firebase callable function.
 *
 * Workflow enabled:
 * 1. AI calls web_search("query") -> Returns structured JSON with URLs
 * 2. AI calls fetch_url(best_url) -> Returns page content
 * 3. AI calls execute_python(analysis_code) -> Returns visualization
 */

import type { ToolDefinition } from '../types';

/**
 * Tool definition for web search.
 */
export const webSearchTool: ToolDefinition = {
  name: 'web_search',

  description: `Search the web and return a list of URLs with titles and snippets. Use this tool when you need to find information, documentation, data sources, or any web content. The tool returns structured JSON that you can parse to select the best URLs for further exploration with fetch_url.

Examples of when to use this tool:
- User asks "Find recent news about AI"
- User wants data: "Search for AAPL stock historical data CSV"
- User needs documentation: "Find Python pandas documentation for DataFrame"
- User wants to research a topic: "Search for climate change statistics 2024"

The results include:
- title: Page title
- url: Full URL (use with fetch_url to get content)
- snippet: Brief description/excerpt
- domain: Website domain

Tips:
- Be specific in your queries for better results
- After searching, use fetch_url on promising URLs to get full content
- For data analysis, search for CSV, JSON, or API endpoints
- When incorporating search results into your response, cite sources using numbered references like [1], [2], etc. matching the order of results returned`,

  parameters: {
    type: 'object',
    properties: {
      query: {
        type: 'string',
        description: 'The search query (e.g., "PODD stock historical data CSV", "Python pandas documentation")',
      },
      num_results: {
        type: 'integer',
        description: 'Number of results to return (1-10, default 5)',
        minimum: 1,
        maximum: 10,
        default: 5,
      },
    },
    required: ['query'],
    additionalProperties: false,
  },

  category: 'web',

  // Server-side execution via Firebase callable (matches tool name)
  execution: 'server',

  // Available for all function-supporting providers
  supportedProviders: undefined,

  // Web search is generally safe, no confirmation needed
  requiresConfirmation: false,

  // 30 second timeout for search API
  timeout: 30000,
};

/**
 * Type for the web_search tool arguments.
 */
export interface WebSearchArgs {
  query: string;
  num_results?: number;
}

/**
 * Type for individual search result.
 */
export interface SearchResult {
  title: string;
  url: string;
  snippet: string;
  domain: string;
}

/**
 * Type for the web_search tool response.
 */
export interface WebSearchResponse {
  results: SearchResult[];
  query: string;
  totalResults?: number;
}

/**
 * Validate the web_search arguments.
 */
export function validateWebSearchArgs(args: WebSearchArgs): string[] {
  const errors: string[] = [];

  if (!args.query) {
    errors.push('Query is required');
    return errors;
  }

  if (typeof args.query !== 'string') {
    errors.push('Query must be a string');
    return errors;
  }

  if (args.query.trim().length === 0) {
    errors.push('Query cannot be empty');
    return errors;
  }

  if (args.query.length > 500) {
    errors.push('Query exceeds maximum length of 500 characters');
  }

  if (args.num_results !== undefined) {
    if (typeof args.num_results !== 'number' || !Number.isInteger(args.num_results)) {
      errors.push('num_results must be an integer');
    } else if (args.num_results < 1 || args.num_results > 10) {
      errors.push('num_results must be between 1 and 10');
    }
  }

  return errors;
}
