// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { ToolDefinition } from '../types';

export const writeOutputFileTool: ToolDefinition = {
  name: 'write_output_file',

  description: `Write or append text/binary content directly to a file under /output/.

Use this instead of execute_python when creating long HTML, CSS, JavaScript, JSON, Markdown, or text artifacts. It avoids wrapping large strings inside Python code, which is brittle and can fail when history is compacted. Do not switch to execute_python merely to keep artifact content "in code"; that recreates the compaction failure mode.

If a later history item shows write_output_file content was omitted or replaced with a placeholder, the file content was still written. Inspect the saved file with read_file(path="/output/...", format="text", offset=0, max_chars=4000) instead of regenerating it from memory.

The tool will reject history-compaction placeholder strings as content so they cannot overwrite a real artifact file.

Use this tool for:
- Writing single-page Rich HTML artifacts, supporting styles, scripts, and local assets
- Appending large files in chunks
- Saving full audit findings or intermediate text files for later paged reading with read_file

Do not use this for data analysis or computation; use execute_python for that.`,

  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Destination path under /output, e.g. /output/site/index.html.',
      },
      content: {
        type: 'string',
        description: 'File content. For binary content, provide base64 and set is_base64=true.',
      },
      append: {
        type: 'boolean',
        default: false,
        description: 'Append to an existing file instead of replacing it.',
      },
      is_base64: {
        type: 'boolean',
        default: false,
        description: 'Whether content is base64-encoded binary data.',
      },
    },
    required: ['path', 'content'],
    additionalProperties: false,
  },

  category: 'files',
  execution: 'client',
  requiresConfirmation: false,
  timeout: 30000,
};

export interface WriteOutputFileArgs {
  path: string;
  content: string;
  append?: boolean;
  is_base64?: boolean;
}
