// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * UTF-8 safe base64 helpers.
 *
 * Browser `btoa`/`atob` only support Latin-1 text. These helpers ensure
 * Unicode JSON/spec payloads can be encoded/decoded safely.
 */

function hasBrowserBase64(): boolean {
  return typeof btoa === 'function' && typeof atob === 'function';
}

export function encodeUtf8ToBase64(value: string): string {
  if (!value) return '';

  if (hasBrowserBase64()) {
    const bytes = new TextEncoder().encode(value);
    let binary = '';
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }

  if (typeof Buffer !== 'undefined') {
    return Buffer.from(value, 'utf-8').toString('base64');
  }

  throw new Error('No base64 encoder available');
}

export function decodeBase64ToUtf8(value: string): string {
  if (!value) return '';

  if (hasBrowserBase64()) {
    const binary = atob(value);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return new TextDecoder('utf-8', { fatal: false }).decode(bytes);
  }

  if (typeof Buffer !== 'undefined') {
    return Buffer.from(value, 'base64').toString('utf-8');
  }

  throw new Error('No base64 decoder available');
}

/**
 * Repair "mojibake" — text whose UTF-8 bytes were decoded a second time as
 * Latin-1, so a curly apostrophe (’, U+2019) shows as "â€™", "é" as "Ã©", etc.
 *
 * The transform is only applied when it is provably lossless:
 *  1. The string carries the mojibake signature (a UTF-8 lead byte in the
 *     0xC2/0xC3/0xE2 range followed by a 0x80–0xBF continuation byte).
 *  2. Every code unit is ≤ 0xFF — i.e. the whole string is a Latin-1 byte
 *     string. A code unit > 0xFF means real Unicode is already present, so
 *     re-decoding would corrupt it; we leave such strings untouched.
 *  3. Re-interpreting the code units as bytes yields valid UTF-8 (fatal decode).
 *
 * This heals legacy artifacts that were captured through a bare `atob` (Latin-1)
 * decode, and — applied at spec parse time — stops the corruption from
 * self-perpetuating when a model copies the visible mojibake back into an edit.
 */
export function repairUtf8Mojibake(value: string): string {
  if (!value) return value;
  // UTF-8 lead byte (0xC2/0xC3 accents, 0xE2 punctuation) + a 0x80-0xBF continuation.
  if (!/[\u00c2\u00c3\u00e2][\u0080-\u00bf]/.test(value)) return value;
  for (let i = 0; i < value.length; i++) {
    if (value.charCodeAt(i) > 0xff) return value;
  }
  try {
    const bytes = Uint8Array.from(value, (ch) => ch.charCodeAt(0));
    return new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch {
    return value;
  }
}

export function looksLikeJsonString(value: string): boolean {
  const trimmed = value.trimStart();
  return trimmed.startsWith('{') || trimmed.startsWith('[');
}

export function looksLikeBase64(value: string): boolean {
  if (!value) return false;
  const trimmed = value.trim();
  if (trimmed.length < 8 || trimmed.length % 4 !== 0) return false;
  return /^[A-Za-z0-9+/]+={0,2}$/.test(trimmed);
}

/**
 * Prefer raw JSON. If payload is legacy base64 JSON, decode it.
 */
export function decodePossiblyBase64Json(value: string): string {
  if (!value) return value;
  if (looksLikeJsonString(value)) return value;
  if (!looksLikeBase64(value)) return value;

  try {
    const decoded = decodeBase64ToUtf8(value);
    if (!looksLikeJsonString(decoded)) return value;
    JSON.parse(decoded);
    return decoded;
  } catch {
    return value;
  }
}
