// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { AnalyzeDocumentPresetId } from '../types/analyze';

export type AnalysisLensDomain = 'salesforce';

export type SalesforceAnalysisLensId =
  | 'salesforce_stakeholder_audit'
  | 'salesforce_troubleshooting'
  | 'salesforce_packet_findings'
  | 'salesforce_dependency_impact'
  | 'salesforce_access_governance'
  | 'salesforce_process_automation'
  | 'salesforce_engineering_handoff'
  | 'salesforce_feature_readiness'
  | 'salesforce_release_readiness';

export type AnalysisLensId = SalesforceAnalysisLensId;

export interface AnalysisLensProfile {
  id: AnalysisLensId;
  domain: AnalysisLensDomain;
  name: string;
  shortName: string;
  description: string;
  recommendedOperation: string;
  expectedArtifacts: string[];
  promptInstruction: string;
  /** Report TYPE (content structure) that usually fits this lens's deliverable; a user-pinned type wins. */
  defaultReportTypeId: Exclude<AnalyzeDocumentPresetId, 'auto'>;
  selectable?: boolean;
}

export const SALESFORCE_ANALYSIS_LENSES: AnalysisLensProfile[] = [
  {
    id: 'salesforce_stakeholder_audit',
    domain: 'salesforce',
    name: 'Workspace Audit',
    shortName: 'Workspace Audit',
    description: 'Comprehensive read-only audit with executive brief, dependency context, remediation backlog, and implementation handoff artifacts.',
    recommendedOperation: 'audit',
    expectedArtifacts: [
      'salesforce-executive-brief.md',
      'salesforce-stakeholder-visual-artifacts.json',
      'salesforce-remediation-backlog.json',
      'salesforce-vscode-handoff.json',
    ],
    promptInstruction: 'Run salesforce_metadata_audit(operation="audit") first, then synthesize executive, product, and engineering views from the generated artifacts.',
    defaultReportTypeId: 'source_grounded_audit',
  },
  {
    id: 'salesforce_troubleshooting',
    domain: 'salesforce',
    name: 'Troubleshooting',
    shortName: 'Troubleshooting',
    description: 'Diagnose pasted Flow errors, Apex exceptions, validation failures, or production bug reports against the uploaded Salesforce workspace.',
    recommendedOperation: 'troubleshooting',
    expectedArtifacts: ['salesforce-troubleshooting-brief.md', 'salesforce-component-index.json', 'salesforce-dependency-map.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="troubleshooting", query=<pasted Flow error, Apex exception, or production bug report>) first. Treat the pasted issue as diagnostic input, identify likely metadata entry points, relate them to risks/dependencies/imported agent evidence, and propose read-only next diagnostic steps.',
    defaultReportTypeId: 'technical_handoff',
  },
  {
    id: 'salesforce_packet_findings',
    domain: 'salesforce',
    name: 'Imported Agent Evidence',
    shortName: 'Agent Evidence',
    description: 'Import optional local agent insight packets, validate them, map findings to metadata paths/components, and summarize stakeholder impact.',
    recommendedOperation: 'packet_findings',
    expectedArtifacts: ['salesforce-insight-packets.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="packet_findings") first. Use salesforce-insight-packets.json importedFindings[] for the imported agent evidence; do not infer it from transcript text.',
    defaultReportTypeId: 'source_grounded_audit',
    selectable: false,
  },
  {
    id: 'salesforce_dependency_impact',
    domain: 'salesforce',
    name: 'Dependency & Impact Atlas',
    shortName: 'Impact Atlas',
    description: 'Build a component dependency and blast-radius view for explaining what changes or risks touch.',
    recommendedOperation: 'dependencies',
    expectedArtifacts: ['salesforce-dependency-map.json', 'salesforce-component-index.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="dependencies") or audit when packet overlays are needed, then build a dependency/impact visualization plan. Express the dependency/blast-radius structure as `diagram` blocks (Mermaid flowchart), not as charts.',
    defaultReportTypeId: 'data_dashboard',
  },
  {
    id: 'salesforce_access_governance',
    domain: 'salesforce',
    name: 'Access & Governance',
    shortName: 'Access & Governance',
    description: 'Focus on profiles, permission sets, sharing model concerns, broad permissions, and security/governance exposure.',
    recommendedOperation: 'risks',
    expectedArtifacts: ['salesforce-metadata-audit-report.md', 'salesforce-remediation-backlog.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="risks") or audit, then separate deterministic access risks from imported agent evidence.',
    defaultReportTypeId: 'source_grounded_audit',
  },
  {
    id: 'salesforce_process_automation',
    domain: 'salesforce',
    name: 'Process Automation Map',
    shortName: 'Automation Map',
    description: 'Explain flows, triggers, validation rules, and automation debt in product and operations language.',
    recommendedOperation: 'audit',
    expectedArtifacts: ['salesforce-component-index.json', 'salesforce-stakeholder-visual-artifacts.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="audit") first, then extract flow, trigger, validation-rule, and automation findings for a process map. Render the process map as `diagram` blocks (Mermaid flowchart or sequenceDiagram), not as charts.',
    defaultReportTypeId: 'general_report',
  },
  {
    id: 'salesforce_engineering_handoff',
    domain: 'salesforce',
    name: 'Implementation Handoff',
    shortName: 'Handoff',
    description: 'Create a remediation roadmap and local implementation handoff package for later work outside Symposium.',
    recommendedOperation: 'handoff',
    expectedArtifacts: ['salesforce-vscode-handoff.json', 'salesforce-remediation-backlog.json'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="handoff") or audit when full context is needed. Produce implementation handoff prompts and acceptance criteria, not deployable patches.',
    defaultReportTypeId: 'technical_handoff',
  },
  {
    id: 'salesforce_feature_readiness',
    domain: 'salesforce',
    name: 'Feature Readiness',
    shortName: 'Feature Readiness',
    description: 'Assess readiness, impact, risks, and likely workstreams for a named Salesforce feature or initiative.',
    recommendedOperation: 'feature_readiness',
    expectedArtifacts: ['salesforce-feature-readiness-brief.md', 'salesforce-executive-brief.md'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="feature_readiness", query=<user goal>) when the user names a feature/change goal; otherwise ask for the feature goal.',
    defaultReportTypeId: 'decision_memo',
  },
  {
    id: 'salesforce_release_readiness',
    domain: 'salesforce',
    name: 'Release Readiness',
    shortName: 'Release Readiness',
    description: 'Assess org readiness for an upcoming Salesforce seasonal release or planned go-live window: impacted metadata, deprecations, risks, and a preparation checklist.',
    recommendedOperation: 'feature_readiness',
    expectedArtifacts: ['salesforce-feature-readiness-brief.md', 'salesforce-executive-brief.md'],
    promptInstruction: 'Run salesforce_metadata_audit(operation="feature_readiness", query=<release name/window plus any named initiatives>) first, then run salesforce_docs_lookup emphasizing release-category topics (release notes, deprecations, API retirements) before final synthesis. Produce a readiness checklist that separates verified local metadata evidence from release-notes evidence.',
    defaultReportTypeId: 'executive_brief',
  },
];

export const ANALYSIS_LENSES: AnalysisLensProfile[] = [
  ...SALESFORCE_ANALYSIS_LENSES,
];

export const SALESFORCE_SELECTABLE_ANALYSIS_LENSES: AnalysisLensProfile[] = SALESFORCE_ANALYSIS_LENSES.filter(
  (lens) => lens.selectable !== false,
);

export function getAnalysisLens(id: string): AnalysisLensProfile | undefined {
  return ANALYSIS_LENSES.find((lens) => lens.id === id);
}

export function getAnalysisLenses(ids: string[]): AnalysisLensProfile[] {
  const selected = new Set(ids);
  return ANALYSIS_LENSES.filter((lens) => selected.has(lens.id));
}
