// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { ArtifactBrandingOptions } from '../types/branding';

export const ARTIFACT_BRANDING = {
  version: 1,
  brandName: 'Symposium AI',
  attribution: 'Created with Symposium AI',
  generatedBy: 'Generated by Symposium AI',
  url: 'https://symposiumai.app',
  hostLabel: 'symposiumai.app',
  logoPath: '/branding/symposium-logo.svg',
  logoFilename: 'branding/symposium-logo.svg',
  /** Canonical raster mark for document exports (PDF/PPTX/DOCX embed PNG, not SVG). */
  logoPngPath: '/assets/app-logo.png',
  colors: {
    primary: '#6366f1',
    text: '#334155',
    muted: '#64748b',
    border: '#e2e8f0',
    background: '#f8fafc',
    transcriptPrimary: '#9333EA',
  },
  logoSvg: `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="1024" height="1024" fill="#1A1A1A" rx="81.92" ry="81.92"/>
  <circle cx="686.08" cy="512" r="172.032" fill="#C15F3C" opacity="0.15"/>
  <circle cx="686.08" cy="512" r="163.84" fill="#C15F3C" opacity="0.65"/>
  <circle cx="645.3530166581517" cy="623.8964670942328" r="172.032" fill="#10A37F" opacity="0.15"/>
  <circle cx="645.3530166581517" cy="623.8964670942328" r="163.84" fill="#10A37F" opacity="0.65"/>
  <circle cx="542.2286747682592" cy="683.4353336443652" r="172.032" fill="#4888F8" opacity="0.15"/>
  <circle cx="542.2286747682592" cy="683.4353336443652" r="163.84" fill="#4888F8" opacity="0.65"/>
  <circle cx="424.96000000000004" cy="662.7577022907951" r="172.032" fill="#20808D" opacity="0.15"/>
  <circle cx="424.96000000000004" cy="662.7577022907951" r="163.84" fill="#20808D" opacity="0.65"/>
  <circle cx="348.41830857358906" cy="571.5388665501324" r="172.032" fill="#FA520F" opacity="0.15"/>
  <circle cx="348.41830857358906" cy="571.5388665501324" r="163.84" fill="#FA520F" opacity="0.65"/>
  <circle cx="348.41830857358906" cy="452.4611334498676" r="172.032" fill="#FF7759" opacity="0.15"/>
  <circle cx="348.41830857358906" cy="452.4611334498676" r="163.84" fill="#FF7759" opacity="0.65"/>
  <circle cx="424.9599999999999" cy="361.24229770920493" r="172.032" fill="#0F6FFF" opacity="0.15"/>
  <circle cx="424.9599999999999" cy="361.24229770920493" r="163.84" fill="#0F6FFF" opacity="0.65"/>
  <circle cx="542.2286747682592" cy="340.5646663556348" r="172.032" fill="#4D6BFE" opacity="0.15"/>
  <circle cx="542.2286747682592" cy="340.5646663556348" r="163.84" fill="#4D6BFE" opacity="0.65"/>
  <circle cx="645.3530166581517" cy="400.10353290576717" r="172.032" fill="#1DA1F2" opacity="0.15"/>
  <circle cx="645.3530166581517" cy="400.10353290576717" r="163.84" fill="#1DA1F2" opacity="0.65"/>
  <circle cx="512" cy="512" r="61.44" fill="#1A1A1A"/>
</svg>`,
} as const;

export const DEFAULT_ARTIFACT_BRANDING_OPTIONS: Required<ArtifactBrandingOptions> = {
  visibility: 'visible',
  includeLogo: true,
  includeUrl: true,
};

