// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Data Connector Profiles
 *
 * Defines available data sources that the AI can access via the fetch_api tool.
 * Each connector profile includes:
 * - Authentication configuration (none, query param, header, bearer)
 * - API documentation injected into the AI system prompt
 * - Example fetch_api calls for the AI
 * - Rate limit information
 *
 * Connectors are either:
 * - Symposium-managed: Free/no-auth APIs where Symposium provides access
 * - BYOK (Bring Your Own Key): User provides their own API key
 */

export type ConnectorCategory =
  | 'finance'
  | 'economics'
  | 'weather'
  | 'science'
  | 'reference'
  | 'health'
  | 'education'
  | 'government'
  | 'news'
  | 'geo'
  | 'developer'
  | 'data';
export type ConnectorAuthType = 'query_param' | 'header' | 'bearer' | 'none';

export interface DataConnectorProfile {
  /** Unique identifier used as api_key_ref in fetch_api calls */
  id: string;
  /** Display name */
  name: string;
  /** Category for UI grouping */
  category: ConnectorCategory;
  /** Short description of the data source */
  description: string;
  /** Base URL for API requests */
  baseUrl: string;
  /** How authentication is injected into requests */
  authType: ConnectorAuthType;
  /** Query param name or header name for auth key injection */
  authKeyName?: string;
  /** Whether the user must provide their own API key */
  requiresUserKey: boolean;
  /** Whether Symposium provides a managed key (for free/no-auth APIs) */
  managedBySymposium?: boolean;
  /** Rate limit configuration */
  rateLimits?: { requests: number; period: 'minute' | 'hour' | 'day' };
  /** API documentation injected into AI system prompt when connector is available */
  documentation: string;
  /** Example fetch_api calls for the AI */
  exampleCalls: string[];
  /** URL where users can sign up for an API key */
  signupUrl?: string;
  /** Whether this API supports polling for frequently-updating data */
  supportsRealtime?: boolean;
  /** Minimum recommended polling interval in seconds */
  pollingInterval?: number;
  /** Specialized Analyze tool to use instead of fetch_api, when applicable */
  toolName?: string;
}

// ============================================================================
// Connector Category Metadata
// ============================================================================

export const CONNECTOR_CATEGORIES: Record<ConnectorCategory, { label: string; description: string }> = {
  finance: { label: 'Finance', description: 'Stock prices, economic data, and financial reports' },
  economics: { label: 'Economics', description: 'Macroeconomic indicators, labor data, and international statistics' },
  weather: { label: 'Weather', description: 'Weather forecasts, alerts, and historical data' },
  science: { label: 'Science', description: 'Research papers, scientific data, and academic resources' },
  reference: { label: 'Reference', description: 'General knowledge, encyclopedia, and knowledge graph sources' },
  health: { label: 'Health', description: 'Clinical, biomedical, and public health datasets' },
  education: { label: 'Academic', description: 'Scholarly publications, citations, and researcher metadata' },
  government: { label: 'Government', description: 'Public government datasets and APIs' },
  news: { label: 'News', description: 'News articles, headlines, and media sources' },
  geo: { label: 'Geography', description: 'Geospatial data, maps, and location services' },
  developer: { label: 'Developer', description: 'Code repositories, developer tools, and project data' },
  data: { label: 'Data', description: 'General data import, spreadsheets, and tabular data sources' },
};

// ============================================================================
// Connector Profiles
// ============================================================================

export const DATA_CONNECTORS: DataConnectorProfile[] = [
  // --- FREE / NO AUTH (Symposium-managed) ---
  {
    id: 'weather_gov',
    name: 'Weather.gov (NOAA)',
    category: 'weather',
    description: 'US weather forecasts, alerts, and observations from the National Weather Service',
    baseUrl: 'https://api.weather.gov',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 10, period: 'minute' },
    documentation: `US weather data from NOAA/NWS. Endpoints:
  - /points/{lat},{lon} - Get forecast office and grid
  - /gridpoints/{office}/{x},{y}/forecast - 7-day forecast
  - /alerts/active?area={state} - Active weather alerts
  - /stations/{stationId}/observations/latest - Current conditions`,
    exampleCalls: [
      'fetch_api(url="https://api.weather.gov/points/39.7456,-104.9897")',
      'fetch_api(url="https://api.weather.gov/alerts/active", query_params={"area": "CO"})',
    ],
    supportsRealtime: true,
    pollingInterval: 300,
  },
  {
    id: 'fred',
    name: 'FRED (Federal Reserve)',
    category: 'finance',
    description: 'Economic data: GDP, unemployment, interest rates, CPI, and 800K+ time series',
    baseUrl: 'https://api.stlouisfed.org/fred',
    authType: 'query_param',
    authKeyName: 'api_key',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `Federal Reserve Economic Data with 800K+ series. Endpoints:
  - /series/observations?series_id={id}&file_type=json - Time series data
  - /series/search?search_text={query} - Search for series
  Common series: GDP, UNRATE, FEDFUNDS, CPIAUCSL, DGS10, SP500`,
    exampleCalls: [
      'fetch_api(url="https://api.stlouisfed.org/fred/series/observations", query_params={"series_id":"GDP","file_type":"json"}, api_key_ref="fred")',
    ],
    signupUrl: 'https://fred.stlouisfed.org/docs/api/api_key.html',
    supportsRealtime: true,
    pollingInterval: 3600,
  },
  {
    id: 'usgs_earthquake',
    name: 'USGS Earthquake Data',
    category: 'science',
    description: 'Real-time and historical earthquake data worldwide',
    baseUrl: 'https://earthquake.usgs.gov/fdsnws/event/1',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    documentation: `USGS earthquake catalog. Endpoints:
  - /query?format=geojson&starttime={date}&endtime={date} - Search earthquakes
  - /query?format=geojson&minmagnitude={mag}&limit={n} - Filter by magnitude
  Parameters: starttime, endtime, minmagnitude, maxmagnitude, latitude, longitude, maxradiuskm
  Parse with: geopandas.GeoDataFrame.from_features(data["features"]) for spatial analysis; use Folium for interactive maps or matplotlib for static PNG maps.`,
    exampleCalls: [
      'fetch_api(url="https://earthquake.usgs.gov/fdsnws/event/1/query", query_params={"format":"geojson","starttime":"2024-01-01","minmagnitude":"5","limit":"20"})',
    ],
    supportsRealtime: true,
    pollingInterval: 60,
  },
  {
    id: 'arxiv',
    name: 'arXiv',
    category: 'science',
    description: 'Search and access scientific papers across physics, CS, math, biology, and more',
    baseUrl: 'https://export.arxiv.org/api',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 3, period: 'minute' },
    documentation: `arXiv paper search API (returns Atom XML). Endpoint:
  - /query?search_query={query}&start={offset}&max_results={n} - Search papers
  Query syntax: ti:keyword (title), au:name (author), cat:cs.AI (category), all:keyword
  Pagination: Use "start" param for offset (0-indexed). Batch size: 100-200 papers per request recommended. For large-scale analysis (200+ papers), paginate with multiple fetch_api calls incrementing "start".
  Note: Responses are XML. For JSON-native academic search, consider Semantic Scholar instead.
  Parse XML with: import xml.etree.ElementTree as ET; root = ET.fromstring(text); use namespace {'atom': 'http://www.w3.org/2005/Atom'} with root.findall('atom:entry', ns). Text mining with: wordcloud for abstracts, networkx for co-authorship graphs.`,
    exampleCalls: [
      'fetch_api(url="https://export.arxiv.org/api/query", query_params={"search_query":"all:transformer+attention","max_results":"10"}, response_format="text")',
      'fetch_api(url="https://export.arxiv.org/api/query", query_params={"search_query":"cat:cs.AI","start":"0","max_results":"100"}, response_format="text")',
    ],
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    category: 'reference',
    description: 'Article summaries, revision-aware encyclopedia content, and pageview analytics',
    baseUrl: 'https://en.wikipedia.org/api/rest_v1',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 100, period: 'minute' },
    documentation: `Wikipedia REST and MediaWiki APIs for general knowledge research. Endpoints:
  - /api/rest_v1/page/summary/{title} - Article summary with extract and metadata
  - https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/{project}/{access}/{agent}/{article}/{granularity}/{start}/{end} - Pageview time series
  - /w/api.php?action=query&list=search&srsearch={query}&format=json - Article search
  Titles are typically underscore-separated (e.g., Artificial_intelligence).`,
    exampleCalls: [
      'fetch_api(url="https://en.wikipedia.org/api/rest_v1/page/summary/Artificial_intelligence")',
      'fetch_api(url="https://en.wikipedia.org/w/api.php", query_params={"action":"query","list":"search","srsearch":"climate adaptation","format":"json"})',
      'fetch_api(url="https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia.org/all-access/user/Artificial_intelligence/monthly/20240101/20241231")',
    ],
  },
  {
    id: 'wikidata',
    name: 'Wikidata',
    category: 'reference',
    description: 'Structured knowledge graph entities, properties, and references via SPARQL',
    baseUrl: 'https://query.wikidata.org',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 20, period: 'minute' },
    documentation: `Wikidata query and entity APIs. Endpoints:
  - /sparql?query={SPARQL}&format=json - Run SPARQL queries over Wikidata
  - https://www.wikidata.org/wiki/Special:EntityData/{QID}.json - Raw entity data by ID
  Prefer small LIMIT values and explicit filters in SPARQL for performance.`,
    exampleCalls: [
      'fetch_api(url="https://query.wikidata.org/sparql", query_params={"format":"json","query":"SELECT ?item ?itemLabel WHERE { ?item wdt:P31 wd:Q146 . SERVICE wikibase:label { bd:serviceParam wikibase:language \\"en\\". } } LIMIT 5"})',
      'fetch_api(url="https://www.wikidata.org/wiki/Special:EntityData/Q42.json")',
    ],
  },
  {
    id: 'crossref',
    name: 'Crossref',
    category: 'education',
    description: 'DOI metadata, citations, and publication records across journals and conferences',
    baseUrl: 'https://api.crossref.org',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 50, period: 'minute' },
    documentation: `Crossref REST API for publication metadata. Endpoints:
  - /works?query={query}&rows={n} - Search works
  - /works/{doi} - Retrieve metadata for a DOI
  - /journals/{issn}/works - Works for a journal ISSN
  Include a "mailto" query param for polite pool routing when possible.`,
    exampleCalls: [
      'fetch_api(url="https://api.crossref.org/works", query_params={"query":"large language models","rows":"10","mailto":"research@symposiumai.app"})',
      'fetch_api(url="https://api.crossref.org/works/10.1038%2Fnphys1170", query_params={"mailto":"research@symposiumai.app"})',
    ],
  },
  {
    id: 'openalex',
    name: 'OpenAlex',
    category: 'education',
    description: 'Open scholarly graph with works, authors, institutions, and citation networks',
    baseUrl: 'https://api.openalex.org',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `OpenAlex API for open scholarly metadata. Endpoints:
  - /works?search={query}&per-page={n} - Search scholarly works
  - /works?filter={filters} - Filter by date, concept, institution, etc.
  - /authors?search={name}&per-page={n} - Search author records
  Optional: include "mailto" query param for polite pool behavior.`,
    exampleCalls: [
      'fetch_api(url="https://api.openalex.org/works", query_params={"search":"transformer architecture","per-page":"10"})',
      'fetch_api(url="https://api.openalex.org/authors", query_params={"search":"Yoshua Bengio","per-page":"5"})',
    ],
  },
  {
    id: 'clinicaltrials_gov',
    name: 'ClinicalTrials.gov',
    category: 'health',
    description: 'Clinical study registrations, interventions, outcomes, and trial status by NCT ID',
    baseUrl: 'https://clinicaltrials.gov/api/v2',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `ClinicalTrials.gov API v2 for trial discovery and metadata. Endpoints:
  - /studies?query.term={term}&pageSize={n} - Search studies by keywords
  - /studies/{NCT_ID} - Detailed study record by trial ID
  - /studies?query.cond={condition}&filter.overallStatus={status} - Filter by condition/status
  Use NCT IDs as stable identifiers for citation and reproducibility.`,
    exampleCalls: [
      'fetch_api(url="https://clinicaltrials.gov/api/v2/studies", query_params={"query.term":"type 2 diabetes","pageSize":"10"})',
      'fetch_api(url="https://clinicaltrials.gov/api/v2/studies/NCT04280705")',
    ],
  },
  {
    id: 'openfda',
    name: 'openFDA',
    category: 'health',
    description: 'FDA drug events, labels, recalls, and device reports with structured query syntax',
    baseUrl: 'https://api.fda.gov',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 240, period: 'minute' },
    documentation: `openFDA API for public FDA datasets. Endpoints:
  - /drug/event.json?search={query}&limit={n} - Adverse event reports
  - /drug/label.json?search={query}&limit={n} - Drug label metadata
  - /food/enforcement.json?search={query}&limit={n} - Food recalls
  Query language supports fielded search with operators like +AND+, +OR+, and date ranges.`,
    exampleCalls: [
      'fetch_api(url="https://api.fda.gov/drug/event.json", query_params={"search":"patient.drug.medicinalproduct:aspirin","limit":"5"})',
      'fetch_api(url="https://api.fda.gov/drug/label.json", query_params={"search":"openfda.brand_name:lipitor","limit":"3"})',
    ],
  },
  {
    id: 'us_census',
    name: 'US Census Bureau',
    category: 'government',
    description: 'US demographics and economics from ACS and decennial census datasets',
    baseUrl: 'https://api.census.gov/data',
    authType: 'query_param',
    authKeyName: 'key',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 500, period: 'day' },
    documentation: `US Census Bureau API for population, income, and housing indicators. Endpoints:
  - /{year}/acs/acs1?get={fields}&for=state:* - 1-year ACS estimates by state
  - /{year}/acs/acs5?get={fields}&for=county:*&in=state:{fips} - 5-year ACS county data
  - /{year}/dec/pl?get={fields}&for=state:* - Decennial census tables
  Use variable IDs (e.g., B01001_001E total population, B19013_001E median household income).
  API key is injected using the "key" query parameter when api_key_ref="us_census".`,
    exampleCalls: [
      'fetch_api(url="https://api.census.gov/data/2023/acs/acs1", query_params={"get":"NAME,B01001_001E","for":"state:*"}, api_key_ref="us_census")',
      'fetch_api(url="https://api.census.gov/data/2022/acs/acs5", query_params={"get":"NAME,B19013_001E","for":"county:*","in":"state:06"}, api_key_ref="us_census")',
    ],
  },
  {
    id: 'bls',
    name: 'Bureau of Labor Statistics',
    category: 'economics',
    description: 'Employment, unemployment, CPI, inflation, and labor force time series',
    baseUrl: 'https://api.bls.gov/publicAPI/v2',
    authType: 'query_param',
    authKeyName: 'registrationkey',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 500, period: 'day' },
    documentation: `BLS Public Data API v2 for labor and inflation series. Endpoints:
  - /timeseries/data/{seriesId} - Single time series (GET)
  - /timeseries/data/ - Multiple series and date bounds (POST JSON body)
  Common series: LNS14000000 (US unemployment rate), CUUR0000SA0 (CPI-U all items).
  Registration key is injected via registrationkey query parameter when api_key_ref="bls".`,
    exampleCalls: [
      'fetch_api(url="https://api.bls.gov/publicAPI/v2/timeseries/data/CUUR0000SA0", api_key_ref="bls")',
      'fetch_api(url="https://api.bls.gov/publicAPI/v2/timeseries/data/", method="POST", body={"seriesid":["LNS14000000","CUUR0000SA0"],"startyear":"2023","endyear":"2025"}, api_key_ref="bls")',
    ],
  },
  {
    id: 'nasa',
    name: 'NASA Open APIs',
    category: 'government',
    description: 'Astronomy, Mars rover, and near-earth object datasets from NASA',
    baseUrl: 'https://api.nasa.gov',
    authType: 'query_param',
    authKeyName: 'api_key',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'hour' },
    documentation: `NASA Open APIs for science and mission data. Endpoints:
  - /planetary/apod?api_key={key} - Astronomy Picture of the Day
  - /mars-photos/api/v1/rovers/{rover}/photos?earth_date={YYYY-MM-DD}&api_key={key} - Mars rover photos
  - /neo/rest/v1/feed?start_date={YYYY-MM-DD}&end_date={YYYY-MM-DD}&api_key={key} - Near-earth objects
  API key is injected using api_key query parameter when api_key_ref="nasa".`,
    exampleCalls: [
      'fetch_api(url="https://api.nasa.gov/planetary/apod", api_key_ref="nasa")',
      'fetch_api(url="https://api.nasa.gov/neo/rest/v1/feed", query_params={"start_date":"2026-02-01","end_date":"2026-02-03"}, api_key_ref="nasa")',
    ],
    supportsRealtime: true,
    pollingInterval: 3600,
  },
  {
    id: 'epa_envirofacts',
    name: 'EPA Envirofacts',
    category: 'government',
    description: 'Environmental facility and emissions data from EPA Envirofacts',
    baseUrl: 'https://enviro.epa.gov/enviro/efservice',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `EPA Envirofacts REST service. Path segments define filters and output format. Endpoints:
  - /tri_facility/state_abbr/{state}/rows/{start}:{end}/JSON - TRI facilities by state
  - /tri_facility/city_name/{city}/rows/{start}:{end}/JSON - TRI facilities by city
  Results can be exported in JSON or CSV formats.`,
    exampleCalls: [
      'fetch_api(url="https://enviro.epa.gov/enviro/efservice/tri_facility/state_abbr/VA/rows/0:10/JSON")',
      'fetch_api(url="https://enviro.epa.gov/enviro/efservice/tri_facility/city_name/RICHMOND/rows/0:10/JSON")',
    ],
  },
  {
    id: 'fbi_crime',
    name: 'FBI Crime Data (UCR)',
    category: 'government',
    description: 'State-level crime rate and count series by offense from FBI CDE summarized endpoints',
    baseUrl: 'https://api.usa.gov/crime/fbi/cde',
    authType: 'query_param',
    authKeyName: 'API_KEY',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `FBI Crime Data Explorer API (validated route):
  - /summarized/state/{state}/{offense}?from={MM-YYYY}&to={MM-YYYY} - Monthly offense rates and counts
  Common offense values that return data: violent-crime, property-crime, homicide, robbery, burglary.
  API key is injected using API_KEY query parameter.
  Note: Use summarized endpoints for now; other public CDE routes are inconsistent across environments.`,
    exampleCalls: [
      'fetch_api(url="https://api.usa.gov/crime/fbi/cde/summarized/state/AL/violent-crime", query_params={"from":"01-2020","to":"12-2020"}, api_key_ref="fbi_crime")',
      'fetch_api(url="https://api.usa.gov/crime/fbi/cde/summarized/state/CA/homicide", query_params={"from":"01-2019","to":"12-2020"}, api_key_ref="fbi_crime")',
    ],
    signupUrl: 'https://api.data.gov/signup/',
  },
  {
    id: 'oecd',
    name: 'OECD SDMX',
    category: 'economics',
    description: 'OECD economic indicators and dataflow metadata via SDMX endpoints',
    baseUrl: 'https://sdmx.oecd.org/public/rest',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `OECD SDMX REST API for macroeconomic datasets. Endpoints:
  - /dataflow/{agency} - List available dataflows for an agency
  - /datastructure/{agency}/{resource_id}/{version} - Retrieve dataset dimensions/codelists
  - /data/{dataflow},{dsd},{version}/{key}?startPeriod={period}&endPeriod={period} - Retrieve observations after validating the current dataflow metadata
  Responses are SDMX-XML; use response_format="text" and parse in Python when needed.
  Parse SDMX-XML with: import xml.etree.ElementTree as ET; root = ET.fromstring(text) then xpath with namespaces. Time series analysis with: statsmodels for forecasting/regression.`,
    exampleCalls: [
      'fetch_api(url="https://sdmx.oecd.org/public/rest/dataflow/OECD.SDD.STES", response_format="text")',
      'fetch_api(url="https://sdmx.oecd.org/public/rest/datastructure/OECD.SDD.STES/DSD_STES/4.1", response_format="text")',
    ],
  },
  {
    id: 'imf',
    name: 'IMF DataMapper',
    category: 'economics',
    description: 'IMF macro indicators including GDP growth, inflation, and labor metrics',
    baseUrl: 'https://www.imf.org/external/datamapper/api/v1',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `IMF DataMapper API for country-level macroeconomic indicators. Endpoints:
  - /{indicator} - Indicator values for all countries
  - /{indicator}/{country_codes} - Indicator filtered to selected countries
  Examples: NGDP_RPCH (real GDP growth), PCPIPCH (inflation).`,
    exampleCalls: [
      'fetch_api(url="https://www.imf.org/external/datamapper/api/v1/NGDP_RPCH")',
      'fetch_api(url="https://www.imf.org/external/datamapper/api/v1/PCPIPCH/USA,FRA,DEU")',
    ],
  },
  {
    id: 'eurostat',
    name: 'Eurostat',
    category: 'economics',
    description: 'EU statistics for population, inflation, labor, trade, and economic activity',
    baseUrl: 'https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `Eurostat dissemination API. Endpoint pattern:
  - /{dataset_code}?{dimension_filters} - Dataset values filtered by dimensions
  Common datasets: demo_pjan (population), prc_hicp_midx (HICP inflation), une_rt_m (unemployment).`,
    exampleCalls: [
      'fetch_api(url="https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/demo_pjan", query_params={"geo":"DE","sex":"T","age":"TOTAL"})',
      'fetch_api(url="https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/prc_hicp_midx", query_params={"geo":"DE","coicop":"CP00","freq":"M"})',
    ],
  },
  {
    id: 'un_population',
    name: 'UN Population Data',
    category: 'economics',
    description: 'UN SDG population-related indicators and country-level series metadata',
    baseUrl: 'https://unstats.un.org/SDGAPI/v1/sdg',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `UN SDG API for population and development indicators. Endpoints:
  - /GeoArea/List - List geo area codes (M49-aligned country/region codes)
  - /Series/List - List series metadata and indicator codes
  - /Series/Data?seriesCode={code}&areaCode={m49} - Indicator observations
  Example series EN_LND_CNSPOP reports population density values.`,
    exampleCalls: [
      'fetch_api(url="https://unstats.un.org/SDGAPI/v1/sdg/GeoArea/List")',
      'fetch_api(url="https://unstats.un.org/SDGAPI/v1/sdg/Series/Data", query_params={"seriesCode":"EN_LND_CNSPOP","areaCode":"840"})',
    ],
  },
  {
    id: 'npm_registry',
    name: 'npm Registry',
    category: 'developer',
    description: 'Package versions, metadata, dependencies, and download stats for npm modules',
    baseUrl: 'https://registry.npmjs.org',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `npm registry APIs for JavaScript package intelligence. Endpoints:
  - /{package}/latest - Latest package metadata (small response, best for interactive analysis)
  - /{package} - Full package metadata (large response; use only when release history is required)
  - /-/v1/search?text={query}&size={n} - Package search
  - https://api.npmjs.org/downloads/point/{range}/{package} - Download metrics
  Package metadata includes exact version tarball URLs and integrity hashes.`,
    exampleCalls: [
      'fetch_api(url="https://registry.npmjs.org/react/latest")',
      'fetch_api(url="https://registry.npmjs.org/-/v1/search", query_params={"text":"state management","size":"10"})',
      'fetch_api(url="https://api.npmjs.org/downloads/point/last-week/react")',
    ],
    supportsRealtime: true,
    pollingInterval: 3600,
  },
  {
    id: 'hacker_news',
    name: 'Hacker News',
    category: 'developer',
    description: 'Top stories, discussions, and user activity from the Hacker News Firebase API',
    baseUrl: 'https://hacker-news.firebaseio.com/v0',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `Hacker News official Firebase API. Endpoints:
  - /topstories.json, /newstories.json, /beststories.json - Story ID lists
  - /item/{id}.json - Story/comment/job details
  - /user/{id}.json - User profile and karma
  Fetch IDs first, then hydrate details with /item/{id}.json calls.`,
    exampleCalls: [
      'fetch_api(url="https://hacker-news.firebaseio.com/v0/topstories.json")',
      'fetch_api(url="https://hacker-news.firebaseio.com/v0/item/8863.json")',
    ],
    supportsRealtime: true,
    pollingInterval: 60,
  },
  {
    id: 'pypi',
    name: 'PyPI',
    category: 'developer',
    description: 'Python package metadata, releases, dependencies, and distribution files from the Python Package Index',
    baseUrl: 'https://pypi.org/pypi',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `PyPI JSON API for package metadata and release history. Endpoints:
  - /{package}/json - Latest package metadata and all releases (can be large)
  - /{package}/{version}/json - Metadata for a specific release version
  Includes requires_dist dependency metadata and distribution file details (digests, size, upload time).`,
    exampleCalls: [
      'fetch_api(url="https://pypi.org/pypi/pandas/2.2.0/json")',
      'fetch_api(url="https://pypi.org/pypi/fastapi/0.115.0/json")',
    ],
    supportsRealtime: true,
    pollingInterval: 3600,
  },
  {
    id: 'stack_exchange',
    name: 'Stack Exchange',
    category: 'developer',
    description: 'Stack Overflow and Stack Exchange questions, answers, tags, users, and score/ranking metadata',
    baseUrl: 'https://api.stackexchange.com/2.3',
    authType: 'query_param',
    authKeyName: 'key',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `Stack Exchange API for community Q&A analysis. Endpoints:
  - /search/advanced?site={site}&q={query} - Advanced full-text search
  - /questions?site={site}&tagged={tags}&sort={sort} - Question listings
  - /questions/{ids}/answers?site={site} - Answers for one or more questions
  The "site" query parameter is required (for example: stackoverflow, superuser, serverfault).
  API key is injected automatically via the "key" query parameter when api_key_ref="stack_exchange".`,
    exampleCalls: [
      'fetch_api(url="https://api.stackexchange.com/2.3/search/advanced", query_params={"site":"stackoverflow","q":"vector database","sort":"relevance","pagesize":"10"}, api_key_ref="stack_exchange")',
      'fetch_api(url="https://api.stackexchange.com/2.3/questions", query_params={"site":"stackoverflow","tagged":"python;pandas","sort":"votes","order":"desc","pagesize":"10"}, api_key_ref="stack_exchange")',
    ],
    signupUrl: 'https://stackapps.com/apps/oauth/register',
  },
  {
    id: 'libraries_io',
    name: 'Libraries.io',
    category: 'developer',
    description: 'Cross-ecosystem package intelligence: dependency trees, release history, maintainers, and repository links',
    baseUrl: 'https://libraries.io/api',
    authType: 'query_param',
    authKeyName: 'api_key',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `Libraries.io API for package ecosystem and dependency metadata. Endpoints:
  - /search?q={query}&platform={platform}&per_page={n} - Package search by platform
  - /{platform}/{name} - Package details including dependencies and latest release
  - /{platform}/{name}/dependencies - Dependency graph for the package
  API key is injected automatically via the "api_key" query parameter when api_key_ref="libraries_io".`,
    exampleCalls: [
      'fetch_api(url="https://libraries.io/api/search", query_params={"q":"state management","platform":"npm","per_page":"10"}, api_key_ref="libraries_io")',
      'fetch_api(url="https://libraries.io/api/npm/react", api_key_ref="libraries_io")',
    ],
    signupUrl: 'https://libraries.io/api',
  },
  {
    id: 'open_library',
    name: 'Open Library',
    category: 'reference',
    description: 'Open book catalog metadata, author records, editions, ISBN lookup, and bibliographic search',
    baseUrl: 'https://openlibrary.org',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `Open Library APIs for books and bibliographic metadata. Endpoints:
  - /search.json?title={title}&author={author} - Search books/authors
  - /isbn/{isbn}.json - Lookup edition metadata by ISBN
  - /works/{work_id}.json - Work-level metadata and subjects
  Includes keys/identifiers such as ISBN and OCLC where available.`,
    exampleCalls: [
      'fetch_api(url="https://openlibrary.org/search.json", query_params={"title":"thinking fast and slow","limit":"5"})',
      'fetch_api(url="https://openlibrary.org/isbn/9780143127741.json")',
    ],
  },
  {
    id: 'dictionary_api',
    name: 'Dictionary API',
    category: 'reference',
    description: 'English word definitions, parts of speech, phonetics, and usage examples',
    baseUrl: 'https://api.dictionaryapi.dev/api/v2/entries',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 120, period: 'minute' },
    documentation: `Free Dictionary API for lexical reference. Endpoint:
  - /en/{word} - Definitions, phonetics, meanings, and examples for an English word
  Supports other languages in some deployments via /{lang}/{word}.`,
    exampleCalls: [
      'fetch_api(url="https://api.dictionaryapi.dev/api/v2/entries/en/deterministic")',
      'fetch_api(url="https://api.dictionaryapi.dev/api/v2/entries/en/provenance")',
    ],
  },
  {
    id: 'who_gho',
    name: 'WHO Global Health Observatory',
    category: 'health',
    description: 'WHO global health indicators and metadata through an OData-compatible API',
    baseUrl: 'https://ghoapi.azureedge.net/api',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `WHO GHO OData API for global health indicators and dimensions. Endpoints:
  - /Indicator?$top={n} - List available indicator codes and metadata
  - /Dimension?$top={n} - List dimensions and dimension values
  - /{indicator_code}?$filter=SpatialDim eq '{ISO3}' - Indicator observations by country
  Use ISO3 country codes in SpatialDim filters (for example: USA, IND, BRA).
  OData responses have nested structure — extract the "value" array into a DataFrame: pd.DataFrame(data["value"]).`,
    exampleCalls: [
      'fetch_api(url="https://ghoapi.azureedge.net/api/Indicator", query_params={"$top":"10"})',
      'fetch_api(url="https://ghoapi.azureedge.net/api/Dimension", query_params={"$top":"10"})',
    ],
  },
  {
    id: 'sec_edgar',
    name: 'SEC EDGAR',
    category: 'finance',
    description: 'Company filings, financial reports, and regulatory documents',
    baseUrl: 'https://efts.sec.gov/LATEST',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 10, period: 'minute' },
    documentation: `SEC EDGAR company filing search. No API key required, but a User-Agent header identifying your app is mandatory (SEC policy). Always include headers={"User-Agent":"AppName contact@email.com"} in fetch_api calls. Endpoints:
  - /search-index?q={query}&dateRange=custom&startdt={date}&enddt={date} - Full-text search
  Also: data.sec.gov/submissions/CIK{number}.json for company filings
  data.sec.gov/api/xbrl/companyfacts/CIK{number}.json for XBRL financial data`,
    exampleCalls: [
      'fetch_api(url="https://data.sec.gov/submissions/CIK0000320193.json", headers={"User-Agent":"SymposiumAI research@symposiumai.app"})',
    ],
  },

  // --- FREE / NO AUTH (Symposium-managed) - Stock Data ---
  {
    id: 'yahoo_finance',
    name: 'Yahoo Finance',
    category: 'finance',
    description: 'Stock quotes, historical prices, company info, and market data',
    baseUrl: 'https://query1.finance.yahoo.com/v8/finance',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `Yahoo Finance API for stock data. Use the /v8/finance/chart endpoint for ALL queries — it provides both current prices and historical data.
  IMPORTANT: Do NOT use /v7/finance/quote — it returns 401 Unauthorized.
  Endpoint: /chart/{symbol}?interval={1d|1wk|1mo}&range={1d|5d|1mo|3mo|6mo|1y|5y|max}
  Current price: response.chart.result[0].meta.regularMarketPrice, chartPreviousClose
  Historical data: response.chart.result[0].indicators.quote[0] has {open, high, low, close, volume} arrays.
  Timestamps: response.chart.result[0].timestamp (Unix seconds).
  For multiple symbols, make separate /chart/{symbol} calls for each.`,
    exampleCalls: [
      'fetch_api(url="https://query1.finance.yahoo.com/v8/finance/chart/AAPL", query_params={"interval":"1d","range":"1mo"})',
      'fetch_api(url="https://query1.finance.yahoo.com/v8/finance/chart/MSFT", query_params={"interval":"1d","range":"5d"})',
    ],
    supportsRealtime: true,
    pollingInterval: 60,
  },

  // --- BYOK (User provides key) ---
  {
    id: 'openweathermap',
    name: 'OpenWeatherMap',
    category: 'weather',
    description: 'Global weather data: current, forecast, historical, air quality',
    baseUrl: 'https://api.openweathermap.org/data/2.5',
    authType: 'query_param',
    authKeyName: 'appid',
    requiresUserKey: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `Global weather API. Endpoints:
  - /weather?q={city}&units=metric - Current weather
  - /forecast?q={city}&units=metric - 5-day/3-hour forecast
  - /air_pollution?lat={lat}&lon={lon} - Air quality index`,
    exampleCalls: [
      'fetch_api(url="https://api.openweathermap.org/data/2.5/weather", query_params={"q":"London","units":"metric"}, api_key_ref="openweathermap")',
    ],
    signupUrl: 'https://home.openweathermap.org/users/sign_up',
    supportsRealtime: true,
    pollingInterval: 600,
  },
  {
    id: 'newsapi',
    name: 'NewsAPI',
    category: 'news',
    description: 'Search 80,000+ news sources worldwide for headlines and articles',
    baseUrl: 'https://newsapi.org/v2',
    authType: 'header',
    authKeyName: 'X-Api-Key',
    requiresUserKey: true,
    rateLimits: { requests: 100, period: 'day' },
    documentation: `News aggregation API. Endpoints:
  - /everything?q={query}&sortBy=publishedAt - Search all articles
  - /top-headlines?country={code}&category={cat} - Top headlines
  Categories: business, entertainment, health, science, sports, technology`,
    exampleCalls: [
      'fetch_api(url="https://newsapi.org/v2/everything", query_params={"q":"artificial intelligence","sortBy":"publishedAt","pageSize":"10"}, api_key_ref="newsapi")',
    ],
    signupUrl: 'https://newsapi.org/register',
  },
  {
    id: 'semantic_scholar',
    name: 'Semantic Scholar',
    category: 'science',
    description: 'Academic paper search with citation graphs, author profiles, and recommendations',
    baseUrl: 'https://api.semanticscholar.org/graph/v1',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `Semantic Scholar academic search. Endpoints:
  - /paper/search?query={q}&limit={n}&fields=title,abstract,year,citationCount - Search papers
  - /paper/{paperId}?fields=title,abstract,references,citations - Paper details
  - /author/{authorId}/papers?fields=title,year - Author papers
  No API key is required for public access. Public traffic is shared and can be throttled, so use modest limits, request only needed fields, and pause between paginated calls.`,
    exampleCalls: [
      'fetch_api(url="https://api.semanticscholar.org/graph/v1/paper/search", query_params={"query":"large language models","limit":"10","fields":"title,abstract,year,citationCount"})',
    ],
  },
  {
    id: 'world_bank',
    name: 'World Bank',
    category: 'government',
    description: 'Global development indicators: GDP, population, life expectancy, poverty, and more',
    baseUrl: 'https://api.worldbank.org/v2',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 60, period: 'minute' },
    documentation: `World Bank development indicators API. Always pass format=json. Response is [pagination_meta, data_array]. Endpoints:
  - /country/{code}/indicator/{indicator}?format=json - Get indicator for a country
  - /country/all/indicator/{indicator}?format=json&date=2000:2023&per_page=300 - All countries
  - /indicator?format=json - List available indicators
  - /country?format=json - List countries
  Common indicators: NY.GDP.MKTP.CD (GDP), SP.POP.TOTL (population), SP.DYN.LE00.IN (life expectancy), EN.ATM.CO2E.PC (CO2 per capita), SI.POV.DDAY (poverty), SL.UEM.TOTL.ZS (unemployment)`,
    exampleCalls: [
      'fetch_api(url="https://api.worldbank.org/v2/country/US/indicator/NY.GDP.MKTP.CD", query_params={"format":"json","date":"2000:2023","per_page":"50"})',
      'fetch_api(url="https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL", query_params={"format":"json","date":"2023","per_page":"300"})',
    ],
  },
  {
    id: 'socrata',
    name: 'Socrata / data.gov',
    category: 'government',
    description: 'Open government data from CDC, NYC, CMS, and thousands of public datasets',
    baseUrl: 'https://data.cdc.gov',
    authType: 'query_param',
    authKeyName: '$$app_token',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 1000, period: 'hour' },
    documentation: `Socrata Open Data API (SODA) for government datasets. Queries go to per-domain URLs.
  Pattern: https://{domain}/resource/{dataset_id}.json with SoQL query params.
  SoQL params: $where, $select, $group, $order, $limit, $offset
  Common domains: data.cdc.gov, data.cityofnewyork.us, data.cms.gov
  Discovery: https://api.us.socrata.com/api/catalog/v1?q={search} - Search for datasets across all domains
  Note: The app token is injected automatically via $$app_token.`,
    exampleCalls: [
      'fetch_api(url="https://api.us.socrata.com/api/catalog/v1", query_params={"q":"covid vaccination","limit":"10"}, api_key_ref="socrata")',
      'fetch_api(url="https://data.cdc.gov/resource/8xkx-amqh.json", query_params={"$limit":"50","$order":"date DESC"}, api_key_ref="socrata")',
    ],
  },
  {
    id: 'pubmed',
    name: 'PubMed / NIH',
    category: 'science',
    description: 'Search biomedical literature: 35M+ citations from MEDLINE, life science journals, and online books',
    baseUrl: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 3, period: 'minute' },
    documentation: `PubMed E-utilities for biomedical literature search. Two-step pattern:
  1. esearch.fcgi - Search and get PMIDs: retmode=json, db=pubmed, term={query}
  2. esummary.fcgi - Get article details: retmode=json, db=pubmed, id={pmid_list}
  Or efetch.fcgi for full abstracts (returns XML or text): rettype=abstract, retmode=text
  Query syntax: Use field tags — [ti] (title), [au] (author), [mh] (MeSH term), [dp] (date). Boolean AND/OR/NOT.
  Example queries: "covid vaccine[ti] AND 2024[dp]", "CRISPR[mh] AND review[pt]"`,
    exampleCalls: [
      'fetch_api(url="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi", query_params={"db":"pubmed","term":"machine learning radiology","retmode":"json","retmax":"10"})',
      'fetch_api(url="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi", query_params={"db":"pubmed","id":"38123456,38123457","retmode":"json"})',
    ],
  },
  {
    id: 'overpass_osm',
    name: 'OpenStreetMap / Overpass',
    category: 'geo',
    description: 'Query OpenStreetMap for POIs, buildings, roads, and geographic features worldwide',
    baseUrl: 'https://overpass-api.de/api',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 10, period: 'minute' },
    documentation: `Overpass API for querying OpenStreetMap data. Endpoint:
  - /interpreter with Overpass QL in "data" query param
  Always prefix queries with [out:json][timeout:25]; Use out center; for way/relation centroids.
  Common tags: amenity=restaurant, tourism=hotel, amenity=hospital, leisure=park, shop=supermarket, amenity=charging_station
  Area syntax: area[name="City Name"]->.searchArea; node(area.searchArea)[amenity=restaurant];
  Bounding box: node[amenity=restaurant](south,west,north,east);
  Pairs well with Plotly for visualizations. Spatial analysis with: geopandas for GeoDataFrames, Folium for interactive maps, matplotlib for static maps.`,
    exampleCalls: [
      'fetch_api(url="https://overpass-api.de/api/interpreter", query_params={"data":"[out:json][timeout:25];area[name=\\"San Francisco\\"]->.searchArea;node(area.searchArea)[amenity=restaurant];out center 50;"})',
      'fetch_api(url="https://overpass-api.de/api/interpreter", query_params={"data":"[out:json][timeout:25];node[amenity=charging_station](37.774,-122.420,37.780,-122.410);out center 20;"})',
    ],
  },

  // --- BYOK (User provides key) ---
  {
    id: 'github',
    name: 'GitHub',
    category: 'developer',
    description: 'Repositories, issues, pull requests, commits, code search, and user profiles',
    baseUrl: 'https://api.github.com',
    authType: 'bearer',
    requiresUserKey: true,
    rateLimits: { requests: 5000, period: 'hour' },
    documentation: `GitHub REST API. Endpoints:
  - /repos/{owner}/{repo} - Repository metadata
  - /repos/{owner}/{repo}/issues?state=open&per_page=30 - List issues
  - /repos/{owner}/{repo}/pulls?state=open - List pull requests
  - /repos/{owner}/{repo}/commits?per_page=30 - List commits
  - /repos/{owner}/{repo}/contributors - List contributors
  - /repos/{owner}/{repo}/languages - Language breakdown
  - /search/repositories?q={query}&sort=stars - Search repos
  - /search/code?q={query}+repo:{owner}/{repo} - Search code (30 req/min separate limit)
  - /users/{username} - User profile
  Note: File contents at /repos/{owner}/{repo}/contents/{path} are base64-encoded.`,
    exampleCalls: [
      'fetch_api(url="https://api.github.com/repos/facebook/react", api_key_ref="github")',
      'fetch_api(url="https://api.github.com/search/repositories", query_params={"q":"language:python stars:>1000","sort":"stars","per_page":"10"}, api_key_ref="github")',
    ],
    signupUrl: 'https://github.com/settings/tokens',
  },
  {
    id: 'google_sheets_csv',
    name: 'Google Sheets / CSV',
    category: 'data',
    description: 'Import data from published Google Sheets or any public CSV URL',
    baseUrl: 'https://docs.google.com/spreadsheets/d',
    authType: 'none',
    requiresUserKey: false,
    managedBySymposium: true,
    rateLimits: { requests: 30, period: 'minute' },
    documentation: `Fetch tabular data from Google Sheets or CSV URLs. Two patterns:
  1. Google Sheets (must be published to web):
     https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/export?format=csv
     For specific sheet: add &gid={SHEET_ID}
  2. Any public CSV URL: fetch directly
  IMPORTANT: Always use response_format="text" to get raw CSV text.
  Parse with: pd.read_csv(io.StringIO(csv_text)) in Python code execution.`,
    exampleCalls: [
      'fetch_api(url="https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv", response_format="text")',
    ],
  },
];

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get a connector profile by ID.
 */
export function getConnector(id: string): DataConnectorProfile | undefined {
  return DATA_CONNECTORS.find(c => c.id === id);
}

/**
 * Get connectors grouped by category.
 */
export function getConnectorsByCategory(): Record<ConnectorCategory, DataConnectorProfile[]> {
  const grouped: Record<ConnectorCategory, DataConnectorProfile[]> = {
    finance: [],
    economics: [],
    weather: [],
    science: [],
    reference: [],
    health: [],
    education: [],
    government: [],
    news: [],
    geo: [],
    developer: [],
    data: [],
  };

  for (const connector of DATA_CONNECTORS) {
    grouped[connector.category].push(connector);
  }

  return grouped;
}

/**
 * Get connectors that don't require user keys (Symposium-managed).
 */
export function getManagedConnectors(): DataConnectorProfile[] {
  return DATA_CONNECTORS.filter(c => c.managedBySymposium || !c.requiresUserKey);
}

/**
 * Get connectors that require user-provided API keys.
 */
export function getBYOKConnectors(): DataConnectorProfile[] {
  return DATA_CONNECTORS.filter(c => c.requiresUserKey);
}
