// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Shared provider/model registry metadata.
 *
 * Keeps alias resolution and default model IDs in one place so UI state,
 * pricing, and request routing stay aligned.
 */
export declare const MODEL_ALIASES: Record<string, string>;
export declare const DEFAULT_PROVIDER_MODELS: Record<string, string>;
export declare function resolveModelAlias(modelId: string): string;
export declare function getDefaultModelId(providerId: string): string;
