// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export interface ModelConfig {
    id: string;
    name: string;
    description: string;
    contextLength: number;
    contextLabel?: string | null;
    maxOutputTokens?: number;
    isDefault?: boolean;
    isPreview?: boolean;
    supportsVision?: boolean;
    supportsDocuments?: boolean;
    supportsFunctions?: boolean;
    supportsWebSearch?: boolean;
    supportsThinking?: boolean;
    supportsStreaming?: boolean;
    requiresTemperature1?: boolean;
    useMaxCompletionTokens?: boolean;
    supportsImageInput?: boolean;
    supportsImageGeneration?: boolean;
    unsupportedParams?: (keyof ModelParameters)[];
    isDeprecated?: boolean;
}
export interface ProviderModels {
    [providerId: string]: ModelConfig[];
}
export declare const AI_MODELS: ProviderModels;
export interface ModelParameters {
    temperature: number;
    maxTokens: number;
    topP?: number;
    topK?: number;
    frequencyPenalty?: number;
    presencePenalty?: number;
    stopSequences?: string[];
    seed?: number;
}
export declare const DEFAULT_PARAMETERS: ModelParameters;
export declare const PARAMETER_RANGES: {
    temperature: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
    maxTokens: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
    topP: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
    topK: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
    frequencyPenalty: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
    presencePenalty: {
        min: number;
        max: number;
        step: number;
        description: string;
    };
};
export declare const PROVIDER_PARAMETER_RANGES: {
    [providerId: string]: {
        [param: string]: {
            min: number;
            max: number;
            step: number;
            description?: string;
        };
    };
};
export declare function getParameterRange(providerId: string, param: keyof typeof PARAMETER_RANGES, modelId?: string): {
    min: number;
    max: number;
    step: number;
    description: string;
};
export declare function normalizeTemperatureForModel(providerId: string, modelId: string | undefined, temperature: number | undefined): number | undefined;
export declare const PROVIDER_SUPPORTED_PARAMS: {
    [key: string]: (keyof ModelParameters)[];
};
export declare function getSupportedParams(providerId: string, modelId?: string): (keyof ModelParameters)[];
export declare const CURATED_MODEL_IDS: {
    [providerId: string]: string[];
};
export declare const getProviderModels: (providerId: string) => ModelConfig[];
export declare const getProviderDefaultModel: (providerId: string) => ModelConfig | undefined;
export declare const resolveProviderModelId: (providerId: string, modelId?: string, options?: {
    allowUnknown?: boolean;
}) => string | undefined;
export declare const getModelById: (providerId: string, modelId: string) => ModelConfig | undefined;
export declare const DEFAULT_MAX_OUTPUT_TOKENS = 16384;
export declare function getMaxOutputTokens(providerId: string, modelId: string): number;
