// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export interface ProviderInfo {
    id: string;
    name: string;
    company: string;
    color: string;
    gradient: [string, string];
    apiKeyPrefix: string;
    apiKeyPlaceholder: string;
    docsUrl: string;
    getKeyUrl: string;
    description: string;
    features: string[];
    enabled: boolean;
}
export declare const AI_PROVIDERS: ProviderInfo[];
export declare const getProviderById: (id: string) => ProviderInfo | undefined;
export declare const getEnabledProviders: () => ProviderInfo[];
export interface ToolProviderInfo {
    id: string;
    name: string;
    company: string;
    color: string;
    gradient: [string, string];
    apiKeyPrefix: string;
    apiKeyPlaceholder: string;
    docsUrl: string;
    getKeyUrl: string;
    description: string;
    features: string[];
    /** Which tool(s) this provider enables */
    enablesTools: string[];
}
export declare const TOOL_PROVIDERS: ToolProviderInfo[];
export declare const getToolProviderById: (id: string) => ToolProviderInfo | undefined;
