// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Firestore-safe codec for artifact preview tables.
 *
 * Firestore rejects nested arrays ("Nested arrays are not supported"), and
 * `metadata.preview.table.rows` is `string[][]` — so ANY artifact carrying a
 * table preview (tabular JSON, CSV, the Layout presentation overlay) failed
 * cloud sync on every attempt. Encode rows as an array of `{ cells }` maps at
 * the Firestore boundary and decode on read; the app-side preview shape stays
 * untouched everywhere else.
 */

interface EncodedPreviewRow {
  cells: string[];
}

type AnyRecord = Record<string, unknown>;

function previewTable(record: AnyRecord): AnyRecord | undefined {
  const metadata = record.metadata as AnyRecord | undefined;
  const preview = metadata?.preview as AnyRecord | undefined;
  const table = preview?.table as AnyRecord | undefined;
  return table && Array.isArray(table.rows) ? table : undefined;
}

function withPreviewTableRows(record: AnyRecord, rows: unknown[]): AnyRecord {
  const metadata = record.metadata as AnyRecord;
  const preview = metadata.preview as AnyRecord;
  const table = preview.table as AnyRecord;
  return {
    ...record,
    metadata: {
      ...metadata,
      preview: { ...preview, table: { ...table, rows } },
    },
  };
}

/** rows: string[][] → [{ cells: string[] }] so setDoc accepts the record. */
export function encodeArtifactPreviewForFirestore(record: AnyRecord): AnyRecord {
  const table = previewTable(record);
  if (!table) return record;
  const rows = table.rows as unknown[];
  if (!rows.some((row) => Array.isArray(row))) return record;
  return withPreviewTableRows(
    record,
    rows.map((row) => (Array.isArray(row) ? { cells: row } : row)),
  );
}

/** Inverse of the encoder; tolerates already-plain (legacy/local) rows. */
export function decodeArtifactPreviewFromFirestore(record: AnyRecord): AnyRecord {
  const table = previewTable(record);
  if (!table) return record;
  const rows = table.rows as unknown[];
  const isEncodedRow = (row: unknown): row is EncodedPreviewRow =>
    !!row && typeof row === 'object' && Array.isArray((row as EncodedPreviewRow).cells);
  if (!rows.some(isEncodedRow)) return record;
  return withPreviewTableRows(
    record,
    rows.map((row) => (isEncodedRow(row) ? row.cells : row)),
  );
}
