// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Salesforce metadata component kinds. Lives on its own so the tool
 * definitions (and the Analyze contract synced to the server) can import it
 * without pulling in the metadata service.
 */
export type SalesforceComponentType = 'apex_class' | 'apex_trigger' | 'lwc_component' | 'aura_component' | 'custom_object' | 'custom_field' | 'validation_rule' | 'flow' | 'permission_set' | 'profile' | 'layout' | 'package_manifest' | 'custom_metadata' | 'unknown';
