// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import uploadPathRules from './salesforce-upload-path-rules.json';

interface SalesforceUploadPathRules {
  supportedTopLevelFiles: string[];
  insightPacketFiles: string[];
  ignoredMetadataPathSegments: string[];
  ignoredWorkspaceBundlePathSegments: string[];
  metadataSegmentRules: Array<{
    segment: string;
    suffixes: string[];
  }>;
  objectMetadataSuffixes: string[];
}

const PATH_RULES = uploadPathRules as SalesforceUploadPathRules;
const SUPPORTED_TOP_LEVEL_FILES = new Set(PATH_RULES.supportedTopLevelFiles);
const INSIGHT_PACKET_FILES = new Set(PATH_RULES.insightPacketFiles);
const IGNORED_METADATA_PATH_SEGMENTS = new Set(PATH_RULES.ignoredMetadataPathSegments);
const IGNORED_WORKSPACE_BUNDLE_PATH_SEGMENTS = new Set(PATH_RULES.ignoredWorkspaceBundlePathSegments);

export function normalizeSalesforcePath(path: string): string {
  return path.replace(/\\/g, '/').replace(/^\/+/, '');
}

export interface SalesforceInsightPacketPathInfo {
  rootPath: string;
  runId: string;
  relativePath: string;
}

export function getSalesforceInsightPacketPathInfo(path: string): SalesforceInsightPacketPathInfo | null {
  const normalized = normalizeSalesforcePath(path);
  const segments = normalized.split('/').filter(Boolean);
  const lowerSegments = segments.map((segment) => segment.toLowerCase());
  const symposiumIndex = lowerSegments.findIndex((segment, index) =>
    segment === '.symposium' && lowerSegments[index + 1] === 'salesforce-insights'
  );

  if (symposiumIndex < 0 || segments.length <= symposiumIndex + 3) {
    return null;
  }

  const runId = segments[symposiumIndex + 2];
  const relativePath = segments.slice(symposiumIndex + 3).join('/');
  if (!runId || !relativePath || relativePath.includes('/')) {
    return null;
  }

  return {
    rootPath: segments.slice(0, symposiumIndex + 3).join('/'),
    runId,
    relativePath,
  };
}

export function isSalesforceInsightPacketPath(path: string): boolean {
  const info = getSalesforceInsightPacketPathInfo(path);
  return !!info && INSIGHT_PACKET_FILES.has(info.relativePath.toLowerCase());
}

export function isSalesforceMetadataSourcePath(path: string): boolean {
  const normalized = normalizeSalesforcePath(path);
  const lower = normalized.toLowerCase();
  const segments = lower.split('/').filter(Boolean);
  const filename = segments[segments.length - 1] || '';

  if (!filename || filename === '.ds_store') return false;
  if (segments.some((segment) => IGNORED_METADATA_PATH_SEGMENTS.has(segment))) return false;
  if (SUPPORTED_TOP_LEVEL_FILES.has(filename)) return true;

  for (const rule of PATH_RULES.metadataSegmentRules) {
    if (segments.includes(rule.segment) && rule.suffixes.some((suffix) => lower.endsWith(suffix))) {
      return true;
    }
  }

  if (segments.includes('objects')) {
    return PATH_RULES.objectMetadataSuffixes.some((suffix) => lower.endsWith(suffix));
  }

  return false;
}

export function isSalesforceWorkspaceBundlePath(path: string): boolean {
  const normalized = normalizeSalesforcePath(path);
  const lower = normalized.toLowerCase();
  const segments = lower.split('/').filter(Boolean);
  const filename = segments[segments.length - 1] || '';

  if (!filename || filename === '.ds_store') return false;
  if (segments.some((segment) => IGNORED_WORKSPACE_BUNDLE_PATH_SEGMENTS.has(segment))) return false;

  return isSalesforceMetadataSourcePath(normalized) || isSalesforceInsightPacketPath(normalized);
}
