// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { AISelectionConfig } from '../components/ai-selection/types';

/**
 * Analyze mode output profile selected by the user.
 *
 * - rich: produce one presentational HTML artifact with embedded visuals
 * - portable: produce selected export-ready file formats
 */
export type AnalyzeOutputMode = 'rich' | 'portable';
// `linked_mini_website` is retained only to normalize persisted legacy selections.
export type AnalyzeRichOutputType = 'linked_mini_website' | 'single_page_html';
export const ANALYZE_DOCUMENT_PRESET_IDS = [
  // 'auto' = let the model pick the best-fitting report type from the data + request.
  // The six concrete types below are the structures it chooses among (and the user can pin).
  'auto',
  'general_report',
  'executive_brief',
  'technical_handoff',
  'source_grounded_audit',
  'data_dashboard',
  'decision_memo',
] as const;
export type AnalyzeDocumentPresetId = typeof ANALYZE_DOCUMENT_PRESET_IDS[number];
export const DEFAULT_ANALYZE_DOCUMENT_PRESET_ID: AnalyzeDocumentPresetId = 'auto';
export type AnalyzePortableFormat =
  | 'json'
  | 'csv'
  | 'tsv'
  | 'txt'
  | 'parquet'
  | 'xlsx'
  | 'docx'
  | 'md'
  | 'pdf'
  | 'png'
  | 'svg';

export interface AnalyzeRichOutputConfig {
  type: AnalyzeRichOutputType | null;
  documentPreset?: AnalyzeDocumentPresetId;
  packages: string[];
}

export interface AnalyzePortableOutputConfig {
  formats: AnalyzePortableFormat[];
}

export interface AnalyzeOutputSelection {
  mode: AnalyzeOutputMode | null;
  rich: AnalyzeRichOutputConfig;
  portable: AnalyzePortableOutputConfig;
}

export type AnalyzeOutputSelectionValidationReason =
  | 'missing_mode'
  | 'missing_rich_type'
  | 'missing_portable_formats';

export interface AnalyzeOutputSelectionValidation {
  valid: boolean;
  reason: AnalyzeOutputSelectionValidationReason | null;
}

export const DEFAULT_ANALYZE_OUTPUT_SELECTION: AnalyzeOutputSelection = {
  mode: null,
  rich: {
    type: null,
    documentPreset: DEFAULT_ANALYZE_DOCUMENT_PRESET_ID,
    packages: [],
  },
  portable: {
    formats: [],
  },
};

const ANALYZE_PORTABLE_FORMAT_SET: ReadonlySet<string> = new Set<AnalyzePortableFormat>([
  'json',
  'csv',
  'tsv',
  'txt',
  'parquet',
  'xlsx',
  'docx',
  'md',
  'pdf',
  'png',
  'svg',
]);
const ANALYZE_DOCUMENT_PRESET_SET: ReadonlySet<string> = new Set(ANALYZE_DOCUMENT_PRESET_IDS);

export function isAnalyzeDocumentPresetId(value: unknown): value is AnalyzeDocumentPresetId {
  return typeof value === 'string' && ANALYZE_DOCUMENT_PRESET_SET.has(value);
}

export function createDefaultAnalyzeOutputSelection(): AnalyzeOutputSelection {
  // Modes retired (Phase 4): every run produces the structured report. The mode/
  // rich/portable fields are vestigial; new sessions start as the structured report.
  return {
    mode: 'rich',
    rich: {
      type: 'single_page_html',
      documentPreset: DEFAULT_ANALYZE_DOCUMENT_PRESET_ID,
      packages: [],
    },
    portable: {
      formats: [],
    },
  };
}

export function normalizeAnalyzeOutputSelection(value: unknown): AnalyzeOutputSelection {
  if (!value || typeof value !== 'object') {
    return createDefaultAnalyzeOutputSelection();
  }

  const candidate = value as Partial<AnalyzeOutputSelection>;
  const mode: AnalyzeOutputMode | null = candidate.mode === 'rich' || candidate.mode === 'portable'
    ? candidate.mode
    : null;
  const richType: AnalyzeRichOutputType | null = candidate.rich?.type === 'linked_mini_website' || candidate.rich?.type === 'single_page_html'
    ? candidate.rich.type
    : null;
  const documentPreset = isAnalyzeDocumentPresetId(candidate.rich?.documentPreset)
    ? candidate.rich.documentPreset
    : DEFAULT_ANALYZE_DOCUMENT_PRESET_ID;
  const packages = Array.isArray(candidate.rich?.packages)
    ? candidate.rich!.packages.filter((pkg): pkg is string => typeof pkg === 'string')
    : [];
  const formats = Array.isArray(candidate.portable?.formats)
    ? candidate.portable!.formats.filter(
      (format): format is AnalyzePortableFormat => typeof format === 'string' && ANALYZE_PORTABLE_FORMAT_SET.has(format),
    )
    : [];

  return {
    mode,
    rich: {
      type: richType,
      documentPreset,
      packages,
    },
    portable: {
      formats,
    },
  };
}

export function validateAnalyzeOutputSelection(
  selection: AnalyzeOutputSelection,
): AnalyzeOutputSelectionValidation {
  // Modes retired (Phase 4): the AI always produces the structured report, so a run
  // is always valid to send. Format is an app-side export choice, not a precondition.
  // (Param kept for call-site compatibility; intentionally unused.)
  void selection;
  return { valid: true, reason: null };
}

/**
 * Role for an Analyze participant.
 * - operator: runs tools, delegates to teammates, and produces artifacts
 * - reviewer: critiques operator outputs (auto-review); can also take delegated tasks
 * - teammate: takes tasks the operator delegates; no review pass
 */
export type AnalyzeParticipantRole = 'operator' | 'reviewer' | 'teammate';

/**
 * Analyze mode selection config with participant role.
 * Role is optional for backward compatibility with older persisted state.
 */
export interface AnalyzeRoleSelectionConfig extends AISelectionConfig {
  role?: AnalyzeParticipantRole;
}

export type AnalyzeReviewPriority = 'P0' | 'P1' | 'P2' | 'P3';
export type AnalyzeReviewActionType =
  | 'verify'
  | 'expand'
  | 'revise'
  | 'countercheck'
  | 'reject_claim';

export type AnalyzeReviewCost = 'low' | 'med' | 'high';
export type AnalyzeReviewItemStatus = 'pending' | 'queued' | 'completed' | 'dismissed';
export type AnalyzeReviewStatus = 'idle' | 'running' | 'error';

/**
 * Structured reviewer output item.
 */
export interface AnalyzeReviewItem {
  id: string;
  reviewerId: string;
  reviewerName: string;
  priority: AnalyzeReviewPriority;
  confidence: number;
  actionType: AnalyzeReviewActionType;
  title: string;
  details: string;
  artifactRefs: string[];
  expectedOutcome: string;
  estimatedCost: AnalyzeReviewCost;
  selected: boolean;
  status: AnalyzeReviewItemStatus;
  createdAt: number;
  /** Independent re-derivation by another model with tools ("Check independently"). */
  verification?: AnalyzeReviewVerification;
}

export type AnalyzeVerificationVerdict = 'confirmed' | 'disputed' | 'unverifiable';

export interface AnalyzeReviewVerification {
  status: 'running' | 'done' | 'failed';
  verdict?: AnalyzeVerificationVerdict;
  /** The verifier's evidence and reasoning (its answer after the verdict line). */
  summary?: string;
  verifierName: string;
  verifierModel: string;
  runId?: string;
  verifiedAt?: number;
}
