// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export type AnalysisArtifactBlockKind = 'markdown' | 'callout' | 'metric_grid' | 'table' | 'artifact_ref' | 'chart' | 'diagram' | 'embedded_html';
export type AnalysisArtifactCalloutTone = 'info' | 'success' | 'warning' | 'risk';
/**
 * Optional, model-authored soft provenance for a block. The verifiable hard
 * provenance (endpoint/hashes/fetch time) is resolved app-side from the block's
 * citations → sources → data-artifact ToolResultProvenance; this is supplementary.
 */
export interface AnalysisArtifactBlockProvenance {
    sourceIds?: string[];
    computedAt?: string;
    inputs?: string[];
}
export interface AnalysisArtifactBaseBlock {
    id?: string;
    title?: string;
    citations?: string[];
    provenance?: AnalysisArtifactBlockProvenance;
}
export interface AnalysisArtifactMarkdownBlock extends AnalysisArtifactBaseBlock {
    kind: 'markdown';
    markdown: string;
}
export interface AnalysisArtifactCalloutBlock extends AnalysisArtifactBaseBlock {
    kind: 'callout';
    tone?: AnalysisArtifactCalloutTone;
    body: string;
}
export interface AnalysisArtifactMetric {
    label: string;
    value: string;
    detail?: string;
}
export interface AnalysisArtifactMetricGridBlock extends AnalysisArtifactBaseBlock {
    kind: 'metric_grid';
    metrics: AnalysisArtifactMetric[];
}
export interface AnalysisArtifactTableBlock extends AnalysisArtifactBaseBlock {
    kind: 'table';
    headers: string[];
    rows: string[][];
    caption?: string;
}
export interface AnalysisArtifactRefBlock extends AnalysisArtifactBaseBlock {
    kind: 'artifact_ref';
    artifactId: string;
    caption?: string;
}
/**
 * A Vega-Lite top-level spec (data + encoding, not pixels). Kept loose
 * (`Record<string, unknown>`) so the model can author the full grammar; the
 * renderer/exporter compile it with vega-lite and fail gracefully if invalid.
 */
export type VegaLiteSpec = Record<string, unknown>;
/**
 * A structured chart, authored as a spec rather than a baked image. The
 * `spec.type` discriminator leaves room for other engines later without a
 * breaking change.
 */
export interface AnalysisArtifactChartBlock extends AnalysisArtifactBaseBlock {
    kind: 'chart';
    spec: {
        type: 'vega-lite';
        spec: VegaLiteSpec;
    };
    caption?: string;
}
/**
 * A structural diagram (process/flow, architecture, sequence, ER, state, gantt)
 * authored as Mermaid source text. The app owns layout and rendering — live SVG
 * in the viewer, a rasterized figure in exports — so the model never has to
 * hand-place boxes. The `spec.type` discriminator leaves room for other engines
 * later without a breaking change.
 */
export interface AnalysisArtifactDiagramBlock extends AnalysisArtifactBaseBlock {
    kind: 'diagram';
    spec: {
        type: 'mermaid';
        code: string;
    };
    caption?: string;
}
/**
 * The escape hatch: an AI-authored interactive component (a street-level map, a
 * linked-brushing dashboard, a custom widget) that Vega/structured blocks can't
 * express. The AI saves it as an HTML artifact and references it by id/filename;
 * the app renders it in a sandboxed iframe inside the report (live in HTML export,
 * a static snapshot in PDF/PPTX). Authoring stays the AI's job; assembly the app's.
 */
export interface AnalysisArtifactEmbeddedHtmlBlock extends AnalysisArtifactBaseBlock {
    kind: 'embedded_html';
    /** The saved HTML artifact this embeds (filename the model wrote, e.g. map.html). */
    artifactId: string;
    caption?: string;
    /** Render height in px (default ~420). */
    height?: number;
}
export type AnalysisArtifactBlock = AnalysisArtifactMarkdownBlock | AnalysisArtifactCalloutBlock | AnalysisArtifactMetricGridBlock | AnalysisArtifactTableBlock | AnalysisArtifactRefBlock | AnalysisArtifactChartBlock | AnalysisArtifactDiagramBlock | AnalysisArtifactEmbeddedHtmlBlock;
export interface AnalysisArtifactPage {
    slug: string;
    title: string;
    summary?: string;
    blocks: AnalysisArtifactBlock[];
    relatedPageSlugs?: string[];
}
/**
 * Verifiable fetch provenance baked onto a source app-side (NOT model-authored):
 * the exact API call that produced the source's data. Resolved at spec-creation
 * from the fetch provenance map; survives to render/export inside the spec.
 */
export interface AnalysisArtifactSourceFetch {
    endpoint: string;
    method: string;
    fetchedAt: string;
    cacheStatus: 'fresh' | 'cached';
    responseHash: string;
    parameterHash?: string;
    connectorId?: string;
}
export interface AnalysisArtifactSource {
    id: string;
    label: string;
    title?: string;
    url?: string;
    retrievedAt?: string;
    sourceArtifactId?: string;
    note?: string;
    /** App-injected verifiable provenance (see AnalysisArtifactSourceFetch). */
    provenance?: AnalysisArtifactSourceFetch[];
}
export interface AnalysisArtifactSpecV1 {
    version: 1;
    kind: 'analysis_artifact_spec';
    title: string;
    audience?: string;
    /**
     * Report type the model chose / was pinned to (e.g. 'data_dashboard'). Model-authored
     * free text (schema caps it, never fails validation on a slightly-off value); the app
     * normalizes it for the UI hint and per-type presentation (resolveReportTypeBaseTheme).
     */
    reportTypeId?: string;
    summary: string;
    createdAt?: string;
    pages: AnalysisArtifactPage[];
    sources?: AnalysisArtifactSource[];
}
export interface AnalysisArtifactSpecValidationResult {
    success: boolean;
    errors: string[];
}
