// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { AISelectionConfig } from '../components/ai-selection/types';
/**
 * Analyze mode output profile selected by the user.
 *
 * - rich: produce one presentational HTML artifact with embedded visuals
 * - portable: produce selected export-ready file formats
 */
export type AnalyzeOutputMode = 'rich' | 'portable';
export type AnalyzeRichOutputType = 'linked_mini_website' | 'single_page_html';
export declare const ANALYZE_DOCUMENT_PRESET_IDS: readonly ["auto", "general_report", "executive_brief", "technical_handoff", "source_grounded_audit", "data_dashboard", "decision_memo"];
export type AnalyzeDocumentPresetId = typeof ANALYZE_DOCUMENT_PRESET_IDS[number];
export declare const DEFAULT_ANALYZE_DOCUMENT_PRESET_ID: AnalyzeDocumentPresetId;
export type AnalyzePortableFormat = 'json' | 'csv' | 'tsv' | 'txt' | 'parquet' | 'xlsx' | 'docx' | 'md' | 'pdf' | 'png' | 'svg';
export interface AnalyzeRichOutputConfig {
    type: AnalyzeRichOutputType | null;
    documentPreset?: AnalyzeDocumentPresetId;
    packages: string[];
}
export interface AnalyzePortableOutputConfig {
    formats: AnalyzePortableFormat[];
}
export interface AnalyzeOutputSelection {
    mode: AnalyzeOutputMode | null;
    rich: AnalyzeRichOutputConfig;
    portable: AnalyzePortableOutputConfig;
}
export type AnalyzeOutputSelectionValidationReason = 'missing_mode' | 'missing_rich_type' | 'missing_portable_formats';
export interface AnalyzeOutputSelectionValidation {
    valid: boolean;
    reason: AnalyzeOutputSelectionValidationReason | null;
}
export declare const DEFAULT_ANALYZE_OUTPUT_SELECTION: AnalyzeOutputSelection;
export declare function isAnalyzeDocumentPresetId(value: unknown): value is AnalyzeDocumentPresetId;
export declare function createDefaultAnalyzeOutputSelection(): AnalyzeOutputSelection;
export declare function normalizeAnalyzeOutputSelection(value: unknown): AnalyzeOutputSelection;
export declare function validateAnalyzeOutputSelection(selection: AnalyzeOutputSelection): AnalyzeOutputSelectionValidation;
/**
 * Role for an Analyze participant.
 * - operator: runs tools, delegates to teammates, and produces artifacts
 * - reviewer: critiques operator outputs (auto-review); can also take delegated tasks
 * - teammate: takes tasks the operator delegates; no review pass
 */
export type AnalyzeParticipantRole = 'operator' | 'reviewer' | 'teammate';
/**
 * Analyze mode selection config with participant role.
 * Role is optional for backward compatibility with older persisted state.
 */
export interface AnalyzeRoleSelectionConfig extends AISelectionConfig {
    role?: AnalyzeParticipantRole;
}
export type AnalyzeReviewPriority = 'P0' | 'P1' | 'P2' | 'P3';
export type AnalyzeReviewActionType = 'verify' | 'expand' | 'revise' | 'countercheck' | 'reject_claim';
export type AnalyzeReviewCost = 'low' | 'med' | 'high';
export type AnalyzeReviewItemStatus = 'pending' | 'queued' | 'completed' | 'dismissed';
export type AnalyzeReviewStatus = 'idle' | 'running' | 'error';
/**
 * Structured reviewer output item.
 */
export interface AnalyzeReviewItem {
    id: string;
    reviewerId: string;
    reviewerName: string;
    priority: AnalyzeReviewPriority;
    confidence: number;
    actionType: AnalyzeReviewActionType;
    title: string;
    details: string;
    artifactRefs: string[];
    expectedOutcome: string;
    estimatedCost: AnalyzeReviewCost;
    selected: boolean;
    status: AnalyzeReviewItemStatus;
    createdAt: number;
    /** Independent re-derivation by another model with tools ("Check independently"). */
    verification?: AnalyzeReviewVerification;
}
export type AnalyzeVerificationVerdict = 'confirmed' | 'disputed' | 'unverifiable';
export interface AnalyzeReviewVerification {
    status: 'running' | 'done' | 'failed';
    verdict?: AnalyzeVerificationVerdict;
    /** The verifier's evidence and reasoning (its answer after the verdict line). */
    summary?: string;
    verifierName: string;
    verifierModel: string;
    runId?: string;
    verifiedAt?: number;
}
