// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export type ArtifactBrandingVisibility = 'visible' | 'metadata' | 'off';
export type HtmlBrandingMode = 'auto' | 'report_shell_v1' | 'footer_only';
export interface ArtifactBrandingOptions {
    visibility?: ArtifactBrandingVisibility;
    includeLogo?: boolean;
    includeUrl?: boolean;
}
export interface ArtifactBrandingRecord {
    version: 1;
    visibility: ArtifactBrandingVisibility;
    brandName: string;
    attribution: string;
    url: string;
    logoPath: string;
    appliedAt: string;
}
