// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
export * from './canonical';
export * from './analyze';
export * from './branding';
import type { AudienceDecisionResult, AudienceStance, AudienceVoteStage, DebateFormatId, DebateSideId, OxfordAudienceQuestions, PhaseId } from '../config/debate/formats';
export type AIProvider = 'claude' | 'openai' | 'chatgpt' | 'google' | 'perplexity' | 'mistral' | 'cohere' | 'deepseek' | 'grok' | 'moonshot' | 'zai';
export type UIMode = 'simple' | 'expert';
export type SubscriptionTier = 'free' | 'pro' | 'business';
export interface User {
    id: string;
    email?: string;
    subscription: SubscriptionTier;
    uiMode: UIMode;
    preferences: {
        theme: 'light' | 'dark' | 'auto';
        fontSize: 'small' | 'medium' | 'large';
    };
}
export interface AIConfig {
    id: string;
    provider: AIProvider;
    name: string;
    model: string;
    modelConfig?: {
        displayName: string;
        contextLength: number;
        pricing?: {
            inputPer1M: number;
            outputPer1M: number;
        };
    };
    personality?: string;
    parameters?: ModelParameters;
    avatar?: string;
    icon?: string;
    iconType?: 'image' | 'letter';
    color?: string;
}
export interface Citation {
    index: number;
    url: string;
    title?: string;
    snippet?: string;
}
/**
 * Provenance metadata for fetched external data.
 * Captures deterministic lineage for fetched external data/tool lookups.
 */
export interface ToolResultProvenance {
    tool: 'fetch_api' | 'fetch_url' | 'salesforce_docs_lookup';
    connectorId?: string;
    endpoint: string;
    method: string;
    parameters: Record<string, string>;
    parameterHash: string;
    fetchedAt: string;
    responseHash: string;
    cacheStatus: 'fresh' | 'cached';
}
/**
 * What one Analyze sub-agent run did, saved on its team tool's result message
 * so the Team panel can show past runs after a reload (lane transcripts are
 * not saved).
 */
export interface AnalyzeTeamRunSummary {
    runId: string;
    /** The operator's team tool call this run belongs to. */
    parentToolCallId: string;
    /** Shared by runs of the same approved task (two or more = a panel). */
    assignmentKey?: string;
    agentName: string;
    provider: string;
    model: string;
    task: string;
    status: 'completed' | 'failed' | 'stopped';
    files: string[];
    answerFile?: string;
    toolCount: number;
    startedAt: number;
    endedAt: number;
}
export interface MessageMetadata {
    sessionId?: string;
    conversationTurn?: number;
    responseTime?: number;
    wordCount?: number;
    modelUsed?: string;
    aiId?: string;
    providerId?: string;
    /** Marks a failed turn ("Sorry, I encountered an error…") so it never feeds other AIs' context. */
    isError?: boolean;
    citations?: Citation[];
    providerMetadata?: Record<string, unknown>;
    /** Generated image data from image generation feature */
    generatedImage?: GeneratedImageMetadata;
    /** Indicates this message is a placeholder while an image is being generated */
    isGeneratingImage?: boolean;
    /** Tool calls made by the AI (for tool calling feature) */
    toolCalls?: Array<{
        id: string;
        type: 'function';
        function: {
            name: string;
            arguments: string;
        };
    }>;
    /** Tool execution results (for displaying output like generated images from code execution) */
    toolExecutionResults?: Array<{
        toolName: string;
        content?: string;
        error?: string;
        success: boolean;
        images?: Array<{
            mimeType: string;
            base64: string;
        }>;
        htmlOutputs?: Array<{
            content: string;
            filename?: string;
        }>;
        dataOutputs?: Array<{
            filename: string;
            base64: string;
            size: number;
        }>;
        bundleOutputs?: Array<{
            name?: string;
            manifest: {
                version: 1;
                entryPoint: string;
                files: Record<string, {
                    mimeType: string;
                    content: string;
                    isBase64?: boolean;
                    size: number;
                }>;
            };
            sourceFiles: string[];
        }>;
        provenance?: ToolResultProvenance;
    }>;
    /**
     * Tool call ID for tool result messages (V2 canonical format).
     * Present when this message is a tool result responding to a specific tool call.
     */
    toolCallId?: string;
    /**
     * Indicates this message is a tool result (V2 canonical format).
     * Used to identify tool result messages in conversation history.
     */
    isToolResult?: boolean;
    /**
     * Tool name for tool result messages (V2 canonical format).
     * Indicates which tool produced this result.
     */
    toolName?: string;
    /**
     * Success status for tool result messages (V2 canonical format).
     * Indicates whether the tool execution succeeded.
     */
    success?: boolean;
    /**
     * External data provenance for tool result messages.
     * Present for fetch_api/fetch_url tool outputs when available.
     */
    toolProvenance?: ToolResultProvenance;
    /**
     * Set by the app (not the model) when the operator's reply came back empty:
     * the transcript shows a notice with Retry instead of AI text.
     */
    appNotice?: {
        kind: 'empty_after_tools' | 'empty_reply';
    };
    /** Team mode was on for this turn, but the operator answered without a team plan (app note). */
    teamModeSkipped?: boolean;
    /** The reply stopped at the model's output limit and may be cut off (app note). */
    outputLimitReached?: boolean;
    /** Team tool results (propose_team / delegate): the runs they started. */
    teamRuns?: AnalyzeTeamRunSummary[];
    /**
     * Data connector IDs explicitly selected by the user for this message.
     * Stored for history/debugging.
     */
    selectedConnectorIds?: string[];
    /**
     * Domain analysis lens IDs explicitly selected by the user for this message.
     * Stored for history/debugging.
     */
    selectedAnalysisLensIds?: string[];
    /** Structured debate vote metadata for transcript and history. */
    debateVote?: DebateVoteResult;
    /** Submitted Oxford audience questions, stored as a host message. */
    debateAudienceQuestions?: OxfordAudienceQuestions;
    /** Debate speech role metadata used by transcript and voice generation. */
    debateSpeech?: DebateSpeechMetadata;
    /** Debate podcast MC/interstitial metadata used by transcript and audio generation. */
    debateInterstitial?: DebateInterstitialMetadata;
    /** Debate TTS generation state and generated audio location. */
    debateAudio?: DebateAudioMetadata;
}
/** Metadata for a generated image in a message */
export interface GeneratedImageMetadata {
    /** URL or data URL of the image */
    url: string;
    /** Base64 data for download/offline access */
    base64?: string;
    /** Revised prompt (ChatGPT may modify the prompt) */
    revisedPrompt?: string;
    /** Original prompt used for generation */
    prompt: string;
    /** Model used for generation */
    model: string;
    /** Provider that generated the image */
    providerId: string;
    /** Iteration number in round-robin mode (1-based) */
    iterationNumber?: number;
    /** Total iterations in round-robin mode */
    totalIterations?: number;
    /** Indicates this image was created by refining another image */
    isRefinement?: boolean;
    /** Message ID of the original image that was refined */
    refinementOf?: string;
    /** The refinement instructions used */
    refinementInstructions?: string;
}
export interface DebateVoteResult {
    round: number;
    winnerId: string;
    winnerName?: string;
    votingLabel: string;
    criterion: string;
    timestamp: number;
    voteKind?: 'checkpoint' | 'audience_stance';
    audienceVoteStage?: AudienceVoteStage;
    audienceStance?: AudienceStance;
    audienceResult?: AudienceDecisionResult;
}
export interface DebateSpeechMetadata {
    formatId: DebateFormatId;
    presetId: string;
    messageIndex: number;
    totalMessages: number;
    phase: PhaseId;
    speaker: DebateSideId;
    speakerSlot?: number;
    cxRole?: 'questioner' | 'answerer';
    audienceQuestionTarget?: DebateSideId;
    label: string;
}
export type DebateInterstitialKind = 'intro' | 'phase_segue' | 'audience_question' | 'vote_cue' | 'winner_outro';
export type DebatePodcastFlowStep = 'intro' | 'speech' | 'phase_segue' | 'audience_question' | 'vote_cue' | 'winner_outro';
export interface DebatePodcastMCConfig {
    providerId: AIProvider;
    modelId: string;
    voice: DebateVoiceSelection;
}
export interface DebatePodcastConfig {
    enabled: true;
    mc: DebatePodcastMCConfig;
    pauseMs?: number;
}
export interface DebateInterstitialMetadata {
    kind: DebateInterstitialKind;
    flowStep: DebatePodcastFlowStep;
    formatId: DebateFormatId;
    presetId: string;
    messageIndex?: number;
    afterMessageIndex?: number;
    beforeMessageIndex?: number;
    label: string;
    providerId: AIProvider;
    modelId: string;
}
export interface DebateVoiceSelection {
    voiceId: string;
    voiceName: string;
}
export interface DebateVoiceConfig {
    enabled: true;
    providerId: 'elevenlabs';
    debaterVoices: Record<string, DebateVoiceSelection>;
    ttsModelId?: string;
    podcast?: DebatePodcastConfig;
}
export interface DebateAudioMetadata {
    status: 'generating' | 'ready' | 'failed';
    voiceId: string;
    voiceName: string;
    modelId?: string;
    generatedAt?: number;
    mimeType?: string;
    uri?: string;
    clips?: Array<{
        index: number;
        uri: string;
        mimeType: string;
        text: string;
        characterCount: number;
    }>;
    clipCount?: number;
    characterCount?: number;
    error?: string;
}
export interface MessageAttachment {
    type: 'image' | 'document' | 'video' | 'audio';
    uri: string;
    mimeType: string;
    base64?: string;
    fileName?: string;
    fileSize?: number;
}
export interface Message {
    id: string;
    sender: string;
    /** Message sender type: user, ai, or tool (for tool results in canonical format) */
    senderType: 'user' | 'ai' | 'tool';
    content: string;
    timestamp: number;
    mentions?: string[];
    metadata?: MessageMetadata;
    attachments?: MessageAttachment[];
}
export interface ChatSession {
    id: string;
    selectedAIs: AIConfig[];
    messages: Message[];
    isActive: boolean;
    createdAt: number;
    startTime?: number;
    lastMessageAt?: number;
    sessionType?: 'chat' | 'comparison' | 'debate' | 'analyze';
    topic?: string;
    debateConfig?: {
        formatId?: 'oxford' | 'lincoln_douglas' | 'policy';
        presetId?: string;
        rounds?: number;
        tempo?: 'streaming' | 'fixed';
        postStreamPauseMs?: number;
        civility?: 1 | 2 | 3 | 4 | 5;
        voteResults?: DebateVoteResult[];
        audienceResult?: AudienceDecisionResult;
        voiceConfig?: DebateVoiceConfig;
    };
    syncOverride?: boolean;
    stoppedAIs?: string[];
    debateWinner?: string;
    debateScores?: Record<string, {
        roundWins: number;
    }>;
}
export type SessionType = 'chat' | 'debate' | 'comparison' | 'analyze';
export interface SyncSettings {
    global: 'all' | 'none' | 'selective';
    modes: {
        chat: boolean;
        debate: boolean;
        comparison: boolean;
        analyze: boolean;
    };
    hasCompletedOnboarding: boolean;
}
export interface PersonalityConfig {
    id: string;
    name: string;
    description: string;
    systemPrompt: string;
    traits: {
        formality: number;
        humor: number;
        technicality: number;
        empathy: number;
    };
    isPremium: boolean;
}
export interface ModelParameters {
    temperature: number;
    maxTokens: number;
    topP?: number;
    topK?: number;
    frequencyPenalty?: number;
    presencePenalty?: number;
    stopSequences?: string[];
    seed?: number;
}
export interface ExpertConfig {
    modelSelection: {
        provider: AIProvider;
        model: string;
        parameters: ModelParameters;
    }[];
    systemPrompt: string;
    contextManagement: 'auto' | 'manual';
    turnOrder: 'round-robin' | 'free-for-all' | 'moderated';
}
export type AI = AIConfig;
/** Tone profile for personality (0-1 scale) */
export interface PersonalityTone {
    formality: number;
    humor: number;
    energy: number;
    empathy: number;
    technicality: number;
}
/** Debate behavior profile for personality */
export interface PersonalityDebateProfile {
    argumentStyle: 'logical' | 'emotional' | 'balanced';
    aggression: number;
    concession: number;
    interruption?: number;
}
/** Model parameters associated with a personality */
export interface PersonalityModelParameters {
    temperature: number;
    topP?: number;
}
/** User's customization of a built-in personality */
export interface PersonalityCustomization {
    personalityId: string;
    isCustomized: boolean;
    tone?: Partial<PersonalityTone>;
    debateProfile?: Partial<PersonalityDebateProfile>;
    modelParameters?: Partial<PersonalityModelParameters>;
    updatedAt: number;
}
/** A fully custom personality created by the user */
export interface CustomPersonality {
    id: string;
    name: string;
    emoji: string;
    description?: string;
    tone: PersonalityTone;
    debateProfile: PersonalityDebateProfile;
    modelParameters: PersonalityModelParameters;
    isAdvancedMode?: boolean;
    selectedArchetype?: string;
    systemPrompt?: string;
    debatePrompt?: string;
    chatGuidance?: string;
    debateGuidance?: string;
    compareGuidance?: string;
    createdAt: number;
    updatedAt: number;
}
/** All user personality settings stored in Firestore */
export interface UserPersonalitySettings {
    customizations: Record<string, PersonalityCustomization>;
    customPersonalities: CustomPersonality[];
    updatedAt: number;
}
