// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Notebook Interface Types for Analyze Mode
 *
 * These types support a Jupyter-like notebook interface where:
 * - Each cell contains a user prompt, AI response, code, and outputs
 * - Artifacts (code, images, data) can be saved and downloaded
 * - Sessions can be archived and continued later
 */

import type { Message, ToolResultProvenance } from './index';
import type { ArtifactBrandingRecord } from './branding';

// ============================================================================
// Artifact Types
// ============================================================================

/** Type of artifact produced by notebook execution */
export type ArtifactType = 'code' | 'image' | 'table' | 'data' | 'html'
  | 'dataset' | 'artifact_bundle'
  | 'analysis_artifact_spec'
  | 'report_spec' | 'document_pdf' | 'document_pptx' | 'document_docx' | 'document_html'
  | 'presentation_overlay'
  | 'salesforce_audit_report'
  | 'salesforce_component_index'
  | 'salesforce_dependency_map'
  | 'salesforce_vscode_handoff';

/** Placeholder used when an artifact listing intentionally omits payload data. */
export const ARTIFACT_DATA_NOT_LOADED = '__ARTIFACT_DATA_NOT_LOADED__';

export interface ArtifactPreviewTable {
  columns: string[];
  rows: string[][];
  totalRows?: number;
  totalColumns?: number;
}

export interface ArtifactPreviewMetric {
  label: string;
  value: string;
}

export interface ArtifactPreviewMetadata {
  version: 1;
  kind: 'image' | 'table' | 'text' | 'code' | 'html' | 'report' | 'document' | 'bundle';
  title?: string;
  subtitle?: string;
  excerpt?: string;
  table?: ArtifactPreviewTable;
  metrics?: ArtifactPreviewMetric[];
  thumbnailDataUrl?: string;
}

/** Artifact profile controlling security and portability behavior */
export type ArtifactProfile =
  | 'ARCHIVE_PORTABLE'
  | 'SESSION_STATIC_REPORT'
  | 'SESSION_INTERACTIVE';

/** Tracks how an artifact was generated */
export interface ArtifactProvenance {
  generator: string;
  generatorVersion?: string;
  inputs?: string[];
  retrievalTimestamps?: Record<string, number>;
  dataHash?: string;
  /** External fetch lineage entries used to produce this artifact */
  sources?: ToolResultProvenance[];
}


/** A single policy violation found during artifact validation */
export interface PolicyViolation {
  rule: string;
  severity: 'error' | 'warning';
  message: string;
  location?: string;
}

/** Result of policy gate validation */
export interface PolicyReport {
  passed: boolean;
  violations: PolicyViolation[];
  checkedAt: number;
  auditOnly: boolean;
}

/** Dependency relationship between artifacts */
export interface ArtifactDependency {
  artifactId: string;
  relationship: 'data_source' | 'linked_page' | 'stylesheet' | 'script';
}

/** Artifact produced by a notebook cell */
export interface Artifact {
  id: string;
  cellId: string;
  sessionId: string;
  name: string;
  type: ArtifactType;
  mimeType: string;
  /** Base64 for binary data, raw string for code/text */
  data: string;
  createdAt: number;
  metadata?: {
    /** Programming language for code artifacts */
    language?: string;
    /** Dimensions for images (e.g., "800x600") */
    dimensions?: string;
    /** Row count for tables/data */
    rowCount?: number;
    /** Column count for tables/data */
    columnCount?: number;
    /** File size in bytes */
    fileSize?: number;
    /** Column schema for dataset artifacts */
    schema?: Array<{ name: string; type: string }>;
    /** External domains referenced in HTML artifacts */
    externalDomains?: string[];
    /** Storage mode for bundles too large for Firestore */
    bundleStorageMode?: 'full' | 'local_only';
    /** Files explicitly assembled into an HTML bundle */
    bundleSourceFiles?: string[];
    /** Number of files in an HTML bundle */
    bundleFileCount?: number;
    /** Report spec version (for report_spec artifacts) */
    reportSpecVersion?: number;
    /** Source report_spec artifact ID (for document_pdf/document_pptx artifacts) */
    reportSpecArtifactId?: string;
    /** Export job ID (for document_pdf/document_pptx artifacts) */
    exportJobId?: string;
    /** Download URL for server-generated artifacts (e.g. exported PDFs/PPTX) */
    downloadUrl?: string;
    /** SHA-256 content fingerprint for generated PPTX artifacts */
    pptxHash?: string;
    /** SHA-256 content fingerprint for generated PDF artifacts */
    pdfHash?: string;
    /** SHA-256 content fingerprint for generated DOCX artifacts */
    docxHash?: string;
    /** SHA-256 content fingerprint for generated HTML artifacts */
    htmlHash?: string;
    /** Root artifact ID of the version lineage chain (report_spec and regenerated Analyze artifacts) */
    lineageRootId?: string;
    /** Previous report_spec artifact ID in the version chain */
    previousReportSpecArtifactId?: string;
    /** Previous artifact ID in the version chain (generic — Analyze regenerations) */
    previousArtifactId?: string;
    /** Monotonically increasing version number within lineage */
    versionNumber?: number;
    /** Shared ID linking companion artifacts from the same analysis output group */
    artifactGroupId?: string;
    /** Whether this artifact is a primary user-requested output or hidden report material. */
    artifactDisposition?: 'output' | 'report_material';
    /** The consolidated data workbook surfaced as the session's data deliverable. */
    datasetDeliverable?: boolean;
    /** Role of a hidden report material within a report-ready output group. */
    reportMaterialRole?: 'structured_source' | 'visual' | 'table' | 'dataset' | 'text_extract' | 'source_evidence';
    /** Primary output artifact this retained report material supports, when known. */
    sourceOutputArtifactId?: string;
    /** Independent panel recorded on a report spec (who ran the same task), carried to later versions */
    teamPanel?: {
      operatorName: string;
      panelists: Array<{ name: string; model: string; status: 'running' | 'completed' | 'failed' | 'stopped' }>;
    };
    /** Marks artifacts produced by a Salesforce workspace lens run */
    salesforceLensRun?: boolean;
    /** Selected Salesforce lens IDs / operations represented by this artifact group */
    salesforceLensIds?: string[];
    /** Role of an artifact within a Salesforce workspace analysis packet */
    salesforceRole?:
      | 'workspace_report'
      | 'artifact_manifest'
      | 'component_index'
      | 'dependency_map'
      | 'audit_report'
      | 'remediation_backlog'
      | 'signal_evidence'
      | 'evidence_ledger'
      | 'flow_drilldowns'
      | 'apex_drilldowns'
      | 'feature_reference_map'
      | 'workbench_summary'
      | 'insight_packets'
      | 'documentation_topics'
      | 'documentation_evidence'
      | 'artifact_schema'
      | 'stakeholder_visual_plan'
      | 'executive_brief'
      | 'feature_readiness_brief'
      | 'troubleshooting_brief'
      | 'vscode_handoff';
    /** Canonical dataset workbook artifact ID for this output group */
    canonicalWorkbookArtifactId?: string;
    /** Deterministic fingerprint for dataset reuse lineage */
    datasetFingerprint?: string;
    /** Number of citation rows in canonical workbook */
    citationCount?: number;
    /** Number of unique source rows in canonical workbook */
    sourceCount?: number;
    /** Dataset workbook contract version */
    datasetContractVersion?: 1;
    /** Branding applied or recorded when exporting this artifact */
    branding?: ArtifactBrandingRecord;
    /** Cloud artifact sync state for generated outputs. */
    cloudSyncState?: 'local' | 'pending' | 'synced' | 'failed' | 'quota_blocked';
    /** Number of cloud payload bytes represented by this artifact. */
    payloadBytes?: number;
    /** Whether cloud sync was blocked by the user's storage quota. */
    quotaBlocked?: boolean;
    /** Last cloud sync error shown for retry/debugging. */
    lastSyncError?: string | null;
    /**
     * Local (IndexedDB) persistence state, orthogonal to `cloudSyncState`.
     * Defaults to 'saved' when an artifact is read back from local storage.
     */
    localState?: 'pending' | 'saved' | 'failed';
    /** Last local (IndexedDB) persistence error shown for retry/debugging. */
    lastLocalError?: string | null;
    /** SHA-256 content fingerprint, computed once at persist time, used for dedup. */
    contentHash?: string;
    /** Result of pre-persistence content validation (malformed HTML/JSON, etc.). */
    validationReport?: { valid: boolean; errors: string[] };
    /** Named external data providers used (e.g. 'OpenStreetMap contributors') for attribution. */
    externalDataProviders?: string[];
    /** Compact Library preview payload stored with metadata-only artifact listings. */
    preview?: ArtifactPreviewMetadata;
  };
  /** Security/portability profile */
  profile?: ArtifactProfile;
  /** Provenance tracking */
  provenance?: ArtifactProvenance;
  /** Policy gate validation report */
  policyReport?: PolicyReport;
  /** Dependencies on other artifacts */
  dependencies?: ArtifactDependency[];
}

// ============================================================================
// Bundle Types
// ============================================================================

/** A single file within an artifact bundle */
export interface BundleFile {
  mimeType: string;
  /** Raw string for text content, base64 for binary */
  content: string;
  isBase64?: boolean;
  size: number;
}

/** Manifest describing a multi-file artifact bundle */
export interface BundleManifest {
  version: 1;
  /** Entry point file (e.g. 'index.html') */
  entryPoint: string;
  /** Map of filename to file data */
  files: Record<string, BundleFile>;
}

// ============================================================================
// Notebook Cell Types
// ============================================================================

/** Code block within a notebook cell */
export interface CellCodeBlock {
  code: string;
  language: string;
  /** If saved as an artifact, the artifact ID */
  artifactId?: string;
}

/** Execution output from running code */
export interface CellExecutionOutput {
  stdout: string;
  images: Array<{
    mimeType: string;
    base64: string;
    /** If saved as an artifact, the artifact ID */
    artifactId?: string;
  }>;
  /** Interactive HTML outputs (Bokeh, Altair charts) */
  htmlOutputs?: Array<{
    /** HTML content */
    content: string;
    /** Original filename if saved to /output/ */
    filename?: string;
    /** If saved as an artifact, the artifact ID */
    artifactId?: string;
  }>;
  /** Data files written to /output/ (CSV, JSON, Excel, etc.) */
  dataOutputs?: Array<{
    /** Output filename */
    filename: string;
    /** Base64-encoded file content */
    base64: string;
    /** File size in bytes */
    size: number;
    /** If saved as an artifact, the artifact ID */
    artifactId?: string;
  }>;
  error?: string;
  /** Timestamp when execution completed */
  executedAt?: number;
}

/** Notebook cell data - represents one prompt/response cycle */
export interface NotebookCellData {
  id: string;
  /** 1-based cell number for display */
  cellNumber: number;
  /** The user's prompt message */
  userMessage: Message;
  /** The AI operator's response message (may be streaming) */
  aiMessage?: Message;
  /** Reviewer-pass messages for this turn, shown after the operator's response */
  reviewerMessages?: Message[];
  /** Extracted code block from AI response */
  codeBlock?: CellCodeBlock;
  /** Execution output (from tool call or manual re-run) */
  executionOutput?: CellExecutionOutput;
  /** Artifacts saved from this cell */
  artifacts: Artifact[];
  /** Whether this cell is currently being processed */
  isProcessing?: boolean;
  /** Whether code is being executed */
  isExecuting?: boolean;
}

// ============================================================================
// Archive Types
// ============================================================================

/** Summary of an archived notebook session for list display */
export interface ArchivedSession {
  id: string;
  storageSource: 'cloud' | 'local' | 'pending';
  pendingSync?: boolean;
  syncedAt?: number;
  /** Display name (auto-generated from first prompt, editable) */
  name: string;
  createdAt: number;
  modifiedAt: number;
  /** Number of cells in the session */
  cellCount: number;
  /** Number of saved artifacts. Undefined unless populated on demand (see ArchiveService.getSessionArtifactCount). */
  artifactCount?: number;
  /** First user prompt for preview */
  previewPrompt: string;
  /** AI providers used */
  participants: string[];
}

// ============================================================================
// Notebook State Types
// ============================================================================

/** Active tab in the notebook layout */
export type NotebookTab = 'session' | 'reports' | 'artifacts' | 'archive';

/** Override outputs for cells that have been manually re-run */
export interface CellOutputOverrides {
  [cellId: string]: CellExecutionOutput;
}
