// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { ReportTheme } from './report-spec';
/**
 * A thin, per-report PRESENTATION layer applied at export and reflected in the
 * Preview. It is intentionally separate from the AI-authored content
 * (`analysis_artifact_spec`) so layout survives content edits: page breaks are
 * keyed by stable block ids, and the whole overlay is keyed by the report's
 * lineage root (one overlay per report, independent of content versions).
 *
 * Persisted as a hidden `presentation_overlay` artifact.
 */
export interface PresentationOverlayV1 {
    version: 1;
    kind: 'presentation_overlay';
    /** The report (analysis_artifact_spec lineage) this overlay decorates. */
    lineageRootId: string;
    /** Theme overrides merged over DEFAULT_THEME at export. */
    theme?: PresentationThemeOverride;
    /** Stable block ids that should start a new print page (a `page_break` before them). */
    pageBreakBeforeBlockIds: string[];
}
/** Partial theme override — the user sets only the fields they care about. */
export interface PresentationThemeOverride {
    pageSize?: ReportTheme['pageSize'];
    landscape?: boolean;
    colors?: Partial<ReportTheme['colors']>;
    fonts?: Partial<ReportTheme['fonts']>;
    margins?: Partial<ReportTheme['margins']>;
}
