// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Report Spec Types for Deterministic Publishing & Exports
 *
 * Defines the ReportSpecV1 format: a structured, content-addressable
 * specification for generating deterministic PDF reports from notebook artifacts.
 */

import type { Artifact, ArtifactType } from './notebook';
import type { ArtifactBrandingOptions } from './branding';

// ============================================================================
// Report Theme
// ============================================================================

export interface ReportTheme {
  pageSize: 'A4' | 'LETTER';
  landscape?: boolean;
  margins: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  fonts: {
    heading: string;
    body: string;
    mono: string;
  };
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    background: string;
  };
}

// ============================================================================
// Block Types (discriminated union on `kind`)
// ============================================================================

/** One verifiable fetch backing a source: what was requested, when, and the
 *  content fingerprint. Baked at spec creation from ToolResultProvenance. */
export interface ReportSourceFetch {
  endpoint: string;
  method: string;
  fetchedAt: string;
  cacheStatus: 'fresh' | 'cached';
  responseHash: string;
  parameterHash?: string;
  connectorId?: string;
}

export interface ReportSource {
  id: string;
  label: string;
  title?: string;
  url?: string;
  retrievedAt?: string;
  sourceArtifactId?: string;
  note?: string;
  /** Hard provenance fetch records — drives the verification panel in exports. */
  provenance?: ReportSourceFetch[];
}

/**
 * Optional, model-authored soft provenance for a block. The verifiable hard
 * provenance (endpoint/hashes/fetch time) is resolved app-side from the block's
 * citations → sources → data-artifact ToolResultProvenance; this is supplementary.
 */
export interface BlockProvenance {
  /** Source IDs that back THIS block's numbers (a superset/echo of citations). */
  sourceIds?: string[];
  /** When the block's figures were computed (ISO 8601). */
  computedAt?: string;
  /** Artifact ids / dataset fingerprints fed into the block. */
  inputs?: string[];
}

export interface CitableReportBlock {
  /** Normalized report source IDs cited by this block. */
  citations?: string[];
  /** Optional model-authored soft provenance (see BlockProvenance). */
  provenance?: BlockProvenance;
}

export interface HeadingBlock extends CitableReportBlock {
  kind: 'heading';
  level: 1 | 2 | 3;
  text: string;
}

export interface ParagraphBlock extends CitableReportBlock {
  kind: 'paragraph';
  markdown: string;
}

export type RenderIntent =
  | 'image'
  | 'dataset_preview'
  | 'json_document'
  | 'text_document'
  | 'html_snapshot';

export interface ArtifactBlock extends CitableReportBlock {
  kind: 'artifact';
  artifactId: string;
  renderIntent: RenderIntent;
  caption?: string;
  options?: {
    maxWidth?: number;
    maxHeight?: number;
    maxRows?: number;
  };
}

export interface TableBlock extends CitableReportBlock {
  kind: 'table';
  headers: string[];
  rows: string[][];
  caption?: string;
}

export interface ReportMetric {
  label: string;
  value: string;
  detail?: string;
}

/** A row of KPI cards (label, big value, optional detail) — the dashboard-opening block. */
export interface MetricGridBlock extends CitableReportBlock {
  kind: 'metric_grid';
  metrics: ReportMetric[];
}

export interface ChartBlock extends CitableReportBlock {
  kind: 'chart';
  /** Authored chart spec (data + encoding). Rendered live in-app and to an image for exports. */
  spec: { type: 'vega-lite'; spec: Record<string, unknown> };
  caption?: string;
}

/** A structural diagram (flow/architecture/sequence/ER/state) authored as Mermaid source. */
export interface DiagramBlock extends CitableReportBlock {
  kind: 'diagram';
  /** Diagram source. The app owns layout: live SVG in-app, rasterized figure in exports. */
  spec: { type: 'mermaid'; code: string };
  caption?: string;
}

/**
 * An AI-authored interactive component (HTML artifact) embedded in the report.
 * Rendered live (sandboxed iframe) in the interactive HTML export, and as a static
 * snapshot in PDF/PPTX/DOCX. The escape hatch for what Vega/structured blocks can't do.
 */
export interface EmbeddedHtmlBlock extends CitableReportBlock {
  kind: 'embedded_html';
  artifactId: string;
  caption?: string;
  height?: number;
}

export interface PageBreakBlock extends CitableReportBlock {
  kind: 'page_break';
}

export interface SpacerBlock extends CitableReportBlock {
  kind: 'spacer';
  height: number; // in pt
}

export type ExplanationSize = 's' | 'm' | 'l';

export const EXPLANATION_CHAR_LIMITS: Record<ExplanationSize, number> = {
  s: 240,
  m: 480,
  l: 900,
};

export interface ArtifactExplanationBlock extends CitableReportBlock {
  kind: 'artifact_explanation';
  artifactId: string;
  size: ExplanationSize;
  text: string;
}

export type ReportBlock =
  | HeadingBlock
  | ParagraphBlock
  | ArtifactBlock
  | TableBlock
  | MetricGridBlock
  | ChartBlock
  | DiagramBlock
  | EmbeddedHtmlBlock
  | PageBreakBlock
  | SpacerBlock
  | ArtifactExplanationBlock;

// ============================================================================
// Report Page
// ============================================================================

export interface ReportPage {
  blocks: ReportBlock[];
}

// ============================================================================
// Report Spec Options
// ============================================================================

export type CitationStyle = 'none' | 'numeric_endnotes';
export type ProvenanceDetailLevel = 'brief' | 'full';

export interface ReportChromeSlot {
  enabled?: boolean;
  left?: string;
  center?: string;
  right?: string;
}

export interface ReportSpecOptions {
  /** Best-effort: embed provenance JSON as PDF attachment (ships in M4.1) */
  includeProvenanceAttachment?: boolean;
  /** Citation rendering mode for published PDFs. */
  citationStyle?: CitationStyle;
  /** Include a provenance appendix listing cited/source artifacts. */
  includeProvenanceAppendix?: boolean;
  /** How much provenance detail to include in endnotes/appendix. */
  provenanceDetailLevel?: ProvenanceDetailLevel;
  /** Optional page header template slots. Supports {{title}}, {{date}}, {{pageNumber}}, {{totalPages}} */
  header?: ReportChromeSlot;
  /** Optional page footer template slots. Supports {{title}}, {{date}}, {{pageNumber}}, {{totalPages}} */
  footer?: ReportChromeSlot;
  /** Branding policy for generated report containers and exports. */
  branding?: ArtifactBrandingOptions;
}

// ============================================================================
// Report Spec V1
// ============================================================================

export interface ReportSpecV1 {
  version: 1;
  title: string;
  authors: string[];
  abstract?: string;
  createdAt: number;
  modifiedAt: number;
  sessionId: string;
  /** Normalized report type the deliverable was authored as (e.g. 'executive_brief').
   *  Drives per-type presentation beyond theme geometry: cover page, running header. */
  reportTypeId?: string;
  theme: ReportTheme;
  pages: ReportPage[];
  sources?: ReportSource[];
  options?: ReportSpecOptions;
}

/**
 * Branded type for a ReportSpecV1 that has been parsed, validated, and
 * normalized via canonicalizeReportSpecV1(). All defaults filled, markdown
 * normalized. Only produced by the canonicalization function.
 */
export type CanonicalReportSpecV1 = ReportSpecV1 & {
  readonly __brand: 'CanonicalReportSpecV1';
};

// ============================================================================
// Render Intent ↔ Artifact Type Mapping
// ============================================================================

/**
 * Which artifact types are valid for each render intent.
 * Used for reference validation in the UI and export pipeline.
 */
export const RENDER_INTENT_VALID_TYPES: Record<RenderIntent, readonly ArtifactType[]> = {
  image: ['image'],
  dataset_preview: ['dataset', 'data', 'table'],
  json_document: [
    'data',
    'dataset',
    'table',
    'salesforce_audit_report',
    'salesforce_component_index',
    'salesforce_dependency_map',
    'salesforce_vscode_handoff',
  ],
  text_document: ['data', 'salesforce_vscode_handoff'],
  html_snapshot: ['html', 'artifact_bundle'],
} as const;

/**
 * Check whether an artifact type is valid for a given render intent.
 */
export function isValidArtifactForIntent(
  artifactType: ArtifactType,
  renderIntent: RenderIntent,
): boolean {
  return (RENDER_INTENT_VALID_TYPES[renderIntent] as readonly string[]).includes(artifactType);
}

// ============================================================================
// Provenance Manifest (for document_pdf artifacts)
// ============================================================================

/** Describes a single input artifact used to produce the PDF */
export interface ProvenanceInputArtifact {
  id: string;
  type: ArtifactType;
  hash: string;
}

/** Provenance manifest stored alongside exported PDFs */
export interface ProvenanceManifest {
  /** Content-addressed ID of the source report_spec artifact */
  reportSpecId: string;
  /** SHA-256 hash of the canonical report spec */
  reportSpecHash: string;
  /** All input artifacts referenced by the report */
  inputArtifacts: ProvenanceInputArtifact[];
  /** Renderer versions used during export */
  rendererVersions: {
    playwright: string;
    chromium: string;
  };
  /** Warnings generated during export */
  warnings: string[];
  /** ISO timestamp of export */
  exportedAt: string;
}

// ============================================================================
// Report Template
// ============================================================================

export interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  buildSpec: (
    sessionId: string,
    title: string,
    authors: string[],
    artifacts: Artifact[],
    abstract?: string,
  ) => ReportSpecV1;
}
