// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { Artifact } from '../../types/notebook';
import type { CitationStyle, ReportBlock, ReportSpecV1 } from '../../types/report-spec';

export const INLINE_CITATION_TOKEN_REGEX = /\[cite:([^[\]\s]+)\]/g;

function collectInlineCitationIds(markdown: string): string[] {
  if (!markdown) return [];

  const seen = new Set<string>();
  const ids: string[] = [];
  let match: RegExpExecArray | null = INLINE_CITATION_TOKEN_REGEX.exec(markdown);
  while (match) {
    const artifactId = match[1];
    if (!seen.has(artifactId)) {
      seen.add(artifactId);
      ids.push(artifactId);
    }
    match = INLINE_CITATION_TOKEN_REGEX.exec(markdown);
  }
  INLINE_CITATION_TOKEN_REGEX.lastIndex = 0;
  return ids;
}

export function extractInlineCitationArtifactIds(markdown: string): string[] {
  return collectInlineCitationIds(markdown);
}

export function extractInlineCitationArtifactIdsFromValue(value: unknown): string[] {
  const seen = new Set<string>();
  const ids: string[] = [];

  const pushFromText = (text: string) => {
    for (const id of collectInlineCitationIds(text)) {
      if (seen.has(id)) continue;
      seen.add(id);
      ids.push(id);
    }
  };

  const visit = (candidate: unknown) => {
    if (typeof candidate === 'string') {
      pushFromText(candidate);
      return;
    }
    if (Array.isArray(candidate)) {
      candidate.forEach(visit);
      return;
    }
    if (candidate && typeof candidate === 'object') {
      Object.values(candidate).forEach(visit);
    }
  };

  visit(value);
  return ids;
}

function collectBlockCitationIds(block: ReportBlock): string[] {
  const explicit = block.citations ?? [];
  const inline = (() => {
    switch (block.kind) {
      case 'heading':
        return collectInlineCitationIds(block.text);
      case 'paragraph':
        return collectInlineCitationIds(block.markdown);
      case 'table':
        return extractInlineCitationArtifactIdsFromValue([
          block.caption,
          block.headers,
          block.rows,
        ]);
      case 'metric_grid':
        return extractInlineCitationArtifactIdsFromValue(block.metrics);
      case 'artifact':
        return block.caption ? collectInlineCitationIds(block.caption) : [];
      case 'artifact_explanation':
        return collectInlineCitationIds(block.text);
      case 'chart':
        return block.caption ? collectInlineCitationIds(block.caption) : [];
      case 'diagram':
        return block.caption ? collectInlineCitationIds(block.caption) : [];
      case 'embedded_html':
        return block.caption ? collectInlineCitationIds(block.caption) : [];
      case 'page_break':
      case 'spacer':
        return [];
    }
  })();
  return Array.from(new Set([...explicit, ...inline]));
}

export function buildCitationOrder(spec: ReportSpecV1): string[] {
  const order: string[] = [];
  const seen = new Set<string>();
  const pushUnique = (artifactId: string) => {
    if (!artifactId || seen.has(artifactId)) return;
    seen.add(artifactId);
    order.push(artifactId);
  };

  for (const id of collectInlineCitationIds(spec.abstract ?? '')) {
    pushUnique(id);
  }

  for (const page of spec.pages) {
    for (const block of page.blocks) {
      for (const id of collectBlockCitationIds(block)) {
        pushUnique(id);
      }
      if (block.kind === 'artifact') {
        for (const id of block.citations?.length ? block.citations : [block.artifactId]) {
          pushUnique(id);
        }
      }
    }
  }

  return order;
}

export function replaceInlineCitationTokens(
  markdown: string,
  citationStyle: CitationStyle,
  citationIndexByArtifactId: Map<string, number>,
): string {
  if (!markdown) return markdown;

  return markdown.replace(INLINE_CITATION_TOKEN_REGEX, (_full, artifactId: string) => {
    if (citationStyle !== 'numeric_endnotes') return '';
    const index = citationIndexByArtifactId.get(artifactId);
    return index ? `[${index}]` : '[?]';
  });
}

export interface CitationPreflightWarning {
  code: string;
  message: string;
  artifactIds?: string[];
}

export function analyzeCitationPreflight(
  spec: ReportSpecV1,
  artifacts: Artifact[],
): CitationPreflightWarning[] {
  const warnings: CitationPreflightWarning[] = [];
  const citationStyle = spec.options?.citationStyle ?? 'none';
  if (citationStyle !== 'numeric_endnotes') return warnings;

  const artifactIdSet = new Set(artifacts.map((artifact) => artifact.id));
  const sourceIdSet = new Set((spec.sources ?? []).map((source) => source.id));
  const inlineCitationIds = new Set<string>();

  const recordInlineCitations = (markdown: string) => {
    for (const id of collectInlineCitationIds(markdown)) {
      inlineCitationIds.add(id);
    }
  };

  recordInlineCitations(spec.abstract ?? '');

  const longUncitedParagraphs: Array<{ pageIndex: number; blockIndex: number }> = [];
  const uncitedArtifactBlockIds: string[] = [];

  spec.pages.forEach((page, pageIndex) => {
    page.blocks.forEach((block, blockIndex) => {
      collectBlockCitationIds(block).forEach(id => inlineCitationIds.add(id));

      if (block.kind === 'paragraph') {
        const ids = collectBlockCitationIds(block);
        ids.forEach(id => inlineCitationIds.add(id));

        const plainLength = block.markdown.replace(/\s+/g, ' ').trim().length;
        if (plainLength >= 140 && ids.length === 0) {
          longUncitedParagraphs.push({ pageIndex, blockIndex });
        }
      }

      if (block.kind === 'artifact') {
        const prevBlock = page.blocks[blockIndex - 1];
        const nextBlock = page.blocks[blockIndex + 1];

        const adjacentCitationIds = new Set<string>();
        if (prevBlock?.kind === 'paragraph') {
          collectBlockCitationIds(prevBlock).forEach((id) => adjacentCitationIds.add(id));
        }
        if (nextBlock?.kind === 'paragraph') {
          collectBlockCitationIds(nextBlock).forEach((id) => adjacentCitationIds.add(id));
        }
        collectBlockCitationIds(block).forEach((id) => adjacentCitationIds.add(id));

        const artifactSourceIds = (spec.sources ?? [])
          .filter((source) => source.sourceArtifactId === block.artifactId)
          .map((source) => source.id);
        const hasCitation = adjacentCitationIds.has(block.artifactId)
          || artifactSourceIds.some((sourceId) => adjacentCitationIds.has(sourceId));

        if (!hasCitation) {
          uncitedArtifactBlockIds.push(block.artifactId);
        }
      }
    });
  });

  const missingInlineSources = Array.from(inlineCitationIds).filter(id => !artifactIdSet.has(id) && !sourceIdSet.has(id));
  if (missingInlineSources.length > 0) {
    warnings.push({
      code: 'missing_inline_sources',
      message: `Some citations reference missing sources or artifacts (${missingInlineSources.length}).`,
      artifactIds: missingInlineSources,
    });
  }

  if (longUncitedParagraphs.length > 0) {
    const first = longUncitedParagraphs[0];
    warnings.push({
      code: 'uncited_paragraphs',
      message: `${longUncitedParagraphs.length} long paragraph(s) have no inline citations (first: page ${first.pageIndex + 1}, block ${first.blockIndex + 1}).`,
    });
  }

  if (uncitedArtifactBlockIds.length > 0) {
    const uniqueUncitedArtifactIds = Array.from(new Set(uncitedArtifactBlockIds));
    warnings.push({
      code: 'artifact_blocks_not_inline_cited',
      message: `${uncitedArtifactBlockIds.length} artifact${uncitedArtifactBlockIds.length === 1 ? ' is' : 's are'} shown but never cited:`,
      artifactIds: uniqueUncitedArtifactIds,
    });
  }

  return warnings;
}
