// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Report Constants
 *
 * Shared constants used by both the Zod schema and the builder service.
 * Extracted to avoid circular imports.
 */

import type { ReportTheme } from '../../types/report-spec';

export const DEFAULT_THEME: ReportTheme = {
  pageSize: 'A4',
  landscape: false,
  // Mirrors the PDF exporter's long-standing page geometry (46/54/56/54) so making the
  // exporters honor theme margins is a no-op for the default look. `bottom` includes the
  // clearance for the fixed page footer (footer bottom 24 + height 22 — see PdfExportService).
  margins: { top: 46, right: 54, bottom: 56, left: 54 },
  fonts: {
    heading: 'Helvetica',
    body: 'Helvetica',
    mono: 'Courier',
  },
  colors: {
    primary: '#0E9594',   // teal — Symposium app accent (--accent-primary)
    secondary: '#10A37F', // green — signature-gradient mid stop
    accent: '#4888F8',    // blue — signature-gradient end stop
    text: '#1f2937',      // gray-800
    background: '#ffffff',
  },
};

/**
 * Per-report-type presentation bases, keyed by the `reportTypeId` the model stamps on the
 * authored spec (Deliverable selector / self-selected). Each variant changes page GEOMETRY
 * only — orientation, margins, measure — so a report type looks like itself while colors and
 * type stay on the fixed Symposium brand (export chrome reads EXPORT_BRAND regardless).
 * Types without an entry (general_report, technical_handoff, source_grounded_audit, legacy
 * specs with no reportTypeId) use DEFAULT_THEME. An explicit Layout-menu overlay still wins
 * field-by-field over these bases (see resolveOverlayTheme).
 */
export const REPORT_TYPE_THEMES: Readonly<Partial<Record<string, ReportTheme>>> = {
  // Metric-forward: a wide landscape canvas gives KPI tables and charts room to breathe.
  data_dashboard: {
    ...DEFAULT_THEME,
    landscape: true,
    margins: { top: 40, right: 44, bottom: 56, left: 44 },
  },
  // Leadership documents: a narrower text measure with more air reads as a formal brief.
  executive_brief: {
    ...DEFAULT_THEME,
    margins: { top: 52, right: 68, bottom: 60, left: 68 },
  },
  decision_memo: {
    ...DEFAULT_THEME,
    margins: { top: 52, right: 68, bottom: 60, left: 68 },
  },
};

/**
 * Normalize a model-authored report type id (validated only as a short string) to the
 * canonical snake_case form used by REPORT_TYPE_THEMES and the preset config.
 */
export function normalizeReportTypeId(reportTypeId?: string | null): string | undefined {
  const normalized = reportTypeId?.trim().toLowerCase().replace(/[\s-]+/g, '_');
  return normalized || undefined;
}

/**
 * Resolve the presentation base for a report type id, falling back to DEFAULT_THEME for
 * anything unrecognized (including legacy specs with no reportTypeId).
 */
export function resolveReportTypeBaseTheme(reportTypeId?: string | null): ReportTheme {
  const normalized = normalizeReportTypeId(reportTypeId);
  return (normalized && REPORT_TYPE_THEMES[normalized]) || DEFAULT_THEME;
}

/**
 * Report types that get formal document chrome — a dedicated cover page and a
 * running header — in PDF/DOCX exports. Dashboards open straight into content,
 * and untyped/legacy specs keep the long-standing inline-title layout.
 */
const COVER_CHROME_TYPES = new Set([
  'executive_brief',
  'decision_memo',
  'source_grounded_audit',
  'technical_handoff',
]);

export function reportTypeHasCoverChrome(reportTypeId?: string | null): boolean {
  const normalized = normalizeReportTypeId(reportTypeId);
  return Boolean(normalized && COVER_CHROME_TYPES.has(normalized));
}

/** Human label for a normalized report type id ('executive_brief' → 'Executive Brief'). */
export function reportTypeLabel(reportTypeId?: string | null): string | undefined {
  const normalized = normalizeReportTypeId(reportTypeId);
  if (!normalized || normalized === 'auto') return undefined;
  return normalized
    .split('_')
    .map((word) => (word ? word[0].toUpperCase() + word.slice(1) : word))
    .join(' ');
}
