// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { Artifact } from '../../types/notebook';
import type { ReportBlock, ReportSource, ReportSpecV1 } from '../../types/report-spec';

function hashString(value: string): string {
  let hash = 5381;
  for (let index = 0; index < value.length; index += 1) {
    hash = ((hash << 5) + hash) ^ value.charCodeAt(index);
  }
  return (hash >>> 0).toString(36);
}

function compactText(value: string | undefined, fallback: string): string {
  const normalized = value?.replace(/\s+/g, ' ').trim();
  return normalized || fallback;
}

function isHttpEndpoint(value: string | undefined): boolean {
  return Boolean(value && /^https?:\/\//i.test(value));
}

function sourceIdForArtifactProvenance(artifactId: string, index: number, fingerprint: string): string {
  return `src_${hashString(`${artifactId}:${index}:${fingerprint}`)}`;
}

export function sourceIdsForArtifact(artifact: Artifact, sources: readonly ReportSource[] = []): string[] {
  const linkedIds = sources
    .filter((source) => source.sourceArtifactId === artifact.id)
    .map((source) => source.id);

  if (linkedIds.length > 0) return linkedIds;
  if (artifact.provenance?.sources?.length) {
    return artifact.provenance.sources.map((source, index) => sourceIdForArtifactProvenance(
      artifact.id,
      index,
      `${source.endpoint}|${source.parameterHash}|${source.responseHash}`,
    ));
  }
  if (artifact.provenance) return [artifact.id];
  return [];
}

export function artifactFallbackSource(artifact: Artifact): ReportSource {
  return {
    id: artifact.id,
    label: artifact.name,
    title: artifact.name,
    sourceArtifactId: artifact.id,
    note: artifact.provenance?.generator
      ? `Generated by ${artifact.provenance.generator}`
      : undefined,
  };
}

function provenanceSourceToReportSource(artifact: Artifact, index: number): ReportSource {
  const source = artifact.provenance!.sources![index];
  const endpoint = source.endpoint;
  const id = sourceIdForArtifactProvenance(
    artifact.id,
    index,
    `${endpoint}|${source.parameterHash}|${source.responseHash}`,
  );
  return {
    id,
    label: compactText(endpoint, artifact.name),
    title: compactText(endpoint, artifact.name),
    url: isHttpEndpoint(endpoint) ? endpoint : undefined,
    retrievedAt: source.fetchedAt,
    sourceArtifactId: artifact.id,
    note: `${source.tool}${source.cacheStatus ? ` (${source.cacheStatus})` : ''}`,
  };
}

export function deriveReportSourcesFromArtifacts(artifacts: Artifact[]): ReportSource[] {
  const sources: ReportSource[] = [];
  const seen = new Set<string>();

  const push = (source: ReportSource) => {
    if (seen.has(source.id)) return;
    seen.add(source.id);
    sources.push(source);
  };

  for (const artifact of artifacts) {
    const provenanceSources = artifact.provenance?.sources ?? [];
    if (provenanceSources.length > 0) {
      provenanceSources.forEach((_source, index) => push(provenanceSourceToReportSource(artifact, index)));
    } else if (artifact.provenance) {
      push(artifactFallbackSource(artifact));
    }
  }

  return sources;
}

export function mergeReportSources(
  existingSources: readonly ReportSource[] | undefined,
  derivedSources: readonly ReportSource[],
): ReportSource[] {
  const merged: ReportSource[] = [];
  const seen = new Set<string>();

  for (const source of [...(existingSources ?? []), ...derivedSources]) {
    if (!source.id || seen.has(source.id)) continue;
    seen.add(source.id);
    merged.push(source);
  }

  return merged;
}

export function withReportSourcesFromArtifacts(spec: ReportSpecV1, artifacts: Artifact[]): ReportSpecV1 {
  const sources = mergeReportSources(spec.sources, deriveReportSourcesFromArtifacts(artifacts));
  return sources.length > 0 ? { ...spec, sources } : spec;
}

export function getBlockCitationIds(block: ReportBlock): string[] {
  return block.citations ?? [];
}

export function updateBlockCitations(block: ReportBlock, citations: string[]): ReportBlock {
  const unique = Array.from(new Set(citations.filter(Boolean)));
  if (unique.length === 0) {
    const next = { ...block };
    delete next.citations;
    return next;
  }
  return { ...block, citations: unique };
}

export interface ReportSourceRegistry {
  sources: ReportSource[];
  sourceById: Map<string, ReportSource>;
}

export function buildReportSourceRegistry(spec: ReportSpecV1, artifacts: Artifact[]): ReportSourceRegistry {
  const sources = mergeReportSources(spec.sources, deriveReportSourcesFromArtifacts(artifacts));
  return {
    sources,
    sourceById: new Map(sources.map((source) => [source.id, source])),
  };
}
