// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * ReportBuilderService
 *
 * Creates and manipulates ReportSpecV1 objects. Handles spec construction,
 * block manipulation, and publish-snapshot creation with content-addressed IDs.
 */

import type {
  ReportSpecV1,
  ReportTheme,
  ReportBlock,
  ArtifactBlock,
  RenderIntent,
  CanonicalReportSpecV1,
} from '../../types/report-spec';
import { isValidArtifactForIntent } from '../../types/report-spec';
import type { Artifact, ArtifactType } from '../../types/notebook';
import { contentAddressReportSpec } from '../../lib/content-hash';
import { canonicalizeReportSpecV1 } from './reportSpecSchema';
import { DEFAULT_THEME } from './constants';
import { extractInlineCitationArtifactIdsFromValue } from './citations';
import {
  createArtifactBrandingRecord,
  DEFAULT_ARTIFACT_BRANDING_OPTIONS,
  formatBrandingLine,
  shouldWriteBrandingMetadata,
} from '../branding/ArtifactBrandingService';
import { sourceIdsForArtifact, withReportSourcesFromArtifacts } from './ReportSourceService';

// Re-export so existing consumers don't break
export { DEFAULT_THEME } from './constants';

/** JSON round-trip deep clone — safe for plain data objects (no functions/symbols). */
function deepClone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value));
}

// ============================================================================
// Render Intent Mapping
// ============================================================================

const ARTIFACT_TYPE_TO_RENDER_INTENT: Partial<Record<ArtifactType, RenderIntent>> = {
  image: 'image',
  dataset: 'dataset_preview',
  table: 'dataset_preview',
  data: 'dataset_preview',
  html: 'html_snapshot',
  artifact_bundle: 'html_snapshot',
  salesforce_audit_report: 'json_document',
  salesforce_component_index: 'json_document',
  salesforce_dependency_map: 'json_document',
  salesforce_vscode_handoff: 'json_document',
};

const PORTABLE_FALLBACK_PRIORITY: Array<{ type: ArtifactType; renderIntent: RenderIntent }> = [
  { type: 'image', renderIntent: 'image' },
];

/**
 * Check whether a parsed JSON value is an array of flat records
 * (i.e. tabular data suitable for dataset_preview).
 */
function isTabularJson(parsed: unknown): boolean {
  if (!Array.isArray(parsed)) return false;
  if (parsed.length === 0) return false;
  // Check that every element is an object with only primitive values
  return parsed.every(
    (item) =>
      typeof item === 'object' &&
      item !== null &&
      !Array.isArray(item) &&
      Object.values(item as Record<string, unknown>).every(
        (v) => v === null || typeof v !== 'object',
      ),
  );
}

/**
 * Decode JSON artifact content that may be stored as raw JSON string
 * or base64-encoded JSON payload.
 */
function parseJsonArtifactData(artifactData: string): unknown {
  const trimmed = artifactData.trimStart();
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    return JSON.parse(artifactData);
  }
  return JSON.parse(atob(artifactData));
}

/**
 * Map an artifact type to the appropriate render intent for report blocks.
 * Returns null for artifact types that cannot be rendered in reports
 * (e.g. code, report_spec, document_pdf).
 *
 * For JSON data artifacts ('data'/'dataset'/'table'), inspects the content
 * to decide between 'dataset_preview' (tabular) and 'json_document' (structured).
 */
export function getRenderIntent(
  artifactType: ArtifactType,
  artifactData?: string,
  mimeType?: string,
): RenderIntent | null {
  if (mimeType === 'text/plain' || mimeType === 'text/markdown' || mimeType === 'text/x-markdown') {
    return 'text_document';
  }

  // Content-aware routing for JSON-capable tabular/data artifact types
  if (
    (artifactType === 'data' || artifactType === 'dataset' || artifactType === 'table') &&
    artifactData &&
    mimeType === 'application/json'
  ) {
    try {
      const parsed = parseJsonArtifactData(artifactData);
      return isTabularJson(parsed) ? 'dataset_preview' : 'json_document';
    } catch {
      // Parse failed — fall through to default
    }
  }

  return ARTIFACT_TYPE_TO_RENDER_INTENT[artifactType] ?? null;
}

/**
 * Validate that an artifact's type is compatible with the given render intent.
 * Delegates to the canonical mapping in types/report-spec.ts.
 */
export function validateArtifactForRenderIntent(
  artifactType: ArtifactType,
  renderIntent: RenderIntent,
): boolean {
  return isValidArtifactForIntent(artifactType, renderIntent);
}

export interface PortableSpecConversionResult {
  spec: ReportSpecV1;
  convertedBlockCount: number;
  unresolvedBlockCount: number;
  /** Artifact ids of interactive components with no print-friendly fallback (so a
   *  portable export can name them and offer to make them print-friendly). */
  unresolvedArtifactIds: string[];
}

export interface PortablePublishPreflightIssue {
  code:
    | 'missing_artifact_ref'
    | 'missing_citation_ref'
    | 'html_snapshot_not_portable'
    | 'artifact_policy_errors'
    | 'artifact_policy_warnings';
  severity: 'error' | 'warning';
  artifactId: string;
  message: string;
  rules?: string[];
}

function pickPreferredPortableArtifact(
  candidates: Artifact[],
): { artifact: Artifact; renderIntent: RenderIntent } | null {
  for (const fallback of PORTABLE_FALLBACK_PRIORITY) {
    const match = candidates.find((artifact) => artifact.type === fallback.type);
    if (match) {
      return { artifact: match, renderIntent: fallback.renderIntent };
    }
  }
  return null;
}

/**
 * Convert html_snapshot artifact blocks to portable fallbacks for publish/export.
 *
 * Fallback search order:
 * 1) Same-cell artifact of type image
 * 2) Same-session artifact of type image
 *
 * The editor state remains unchanged; this should be called on a temporary spec
 * right before publish.
 */
export function convertSpecForPortablePublish(
  spec: ReportSpecV1,
  artifactPool: Artifact[],
): PortableSpecConversionResult {
  if (!spec.pages.some((page) => page.blocks.some((block) => block.kind === 'artifact' && block.renderIntent === 'html_snapshot'))) {
    return { spec, convertedBlockCount: 0, unresolvedBlockCount: 0, unresolvedArtifactIds: [] };
  }

  const artifactById = new Map<string, Artifact>(artifactPool.map((artifact) => [artifact.id, artifact]));
  const artifactsByCell = new Map<string, Artifact[]>();
  const artifactsBySession = new Map<string, Artifact[]>();

  for (const artifact of artifactPool) {
    if (artifact.cellId) {
      const existing = artifactsByCell.get(artifact.cellId) ?? [];
      existing.push(artifact);
      artifactsByCell.set(artifact.cellId, existing);
    }
    if (artifact.sessionId) {
      const existing = artifactsBySession.get(artifact.sessionId) ?? [];
      existing.push(artifact);
      artifactsBySession.set(artifact.sessionId, existing);
    }
  }

  for (const [, group] of artifactsByCell) {
    group.sort((a, b) => b.createdAt - a.createdAt);
  }
  for (const [, group] of artifactsBySession) {
    group.sort((a, b) => b.createdAt - a.createdAt);
  }

  let convertedBlockCount = 0;
  let unresolvedBlockCount = 0;
  const unresolvedArtifactIds: string[] = [];

  const nextPages = spec.pages.map((page) => {
    const nextBlocks = page.blocks.map((block) => {
      if (block.kind !== 'artifact' || block.renderIntent !== 'html_snapshot') {
        return block;
      }

      const sourceArtifact = artifactById.get(block.artifactId);
      if (!sourceArtifact) {
        unresolvedBlockCount += 1;
        unresolvedArtifactIds.push(block.artifactId);
        return block;
      }

      const sameCellCandidates = (artifactsByCell.get(sourceArtifact.cellId) ?? [])
        .filter((artifact) => artifact.id !== sourceArtifact.id);
      const sameSessionCandidates = (artifactsBySession.get(sourceArtifact.sessionId) ?? [])
        .filter((artifact) => artifact.id !== sourceArtifact.id);

      const replacement = pickPreferredPortableArtifact(sameCellCandidates)
        ?? pickPreferredPortableArtifact(sameSessionCandidates);

      if (!replacement) {
        unresolvedBlockCount += 1;
        unresolvedArtifactIds.push(block.artifactId);
        return block;
      }

      convertedBlockCount += 1;
      return {
        ...block,
        artifactId: replacement.artifact.id,
        renderIntent: replacement.renderIntent,
      };
    });

    return { ...page, blocks: nextBlocks };
  });

  if (convertedBlockCount === 0) {
    return { spec, convertedBlockCount, unresolvedBlockCount, unresolvedArtifactIds };
  }

  return {
    spec: {
      ...spec,
      pages: nextPages,
      modifiedAt: Date.now(),
    },
    convertedBlockCount,
    unresolvedBlockCount,
    unresolvedArtifactIds,
  };
}

/**
 * Portable publish preflight for report specs.
 * Flags unresolved/unsafe artifact references before publish/export.
 */
export function analyzePortablePublishPreflight(
  spec: ReportSpecV1,
  artifactPool: Artifact[],
): PortablePublishPreflightIssue[] {
  const issues: PortablePublishPreflightIssue[] = [];
  const artifactById = new Map<string, Artifact>(artifactPool.map((artifact) => [artifact.id, artifact]));
  const seen = new Set<string>();

  const pushIssue = (issue: PortablePublishPreflightIssue) => {
    const key = `${issue.code}:${issue.artifactId}`;
    if (seen.has(key)) return;
    seen.add(key);
    issues.push(issue);
  };

  for (const page of spec.pages) {
    for (const block of page.blocks) {
      if (block.kind !== 'artifact') continue;

      const artifact = artifactById.get(block.artifactId);
      if (!artifact) {
        pushIssue({
          code: 'missing_artifact_ref',
          severity: 'error',
          artifactId: block.artifactId,
          message: `Referenced artifact "${block.artifactId}" is missing from the artifact pool`,
        });
        continue;
      }

      if (block.renderIntent === 'html_snapshot' && artifact.profile === 'SESSION_INTERACTIVE') {
        pushIssue({
          code: 'html_snapshot_not_portable',
          severity: 'error',
          artifactId: artifact.id,
          message: `Artifact "${artifact.name}" is session-interactive and cannot be published as a portable HTML snapshot`,
        });
      }

      const violations = artifact.policyReport?.violations ?? [];
      const errorRules = violations.filter((violation) => violation.severity === 'error').map((violation) => violation.rule);
      const warningRules = violations.filter((violation) => violation.severity === 'warning').map((violation) => violation.rule);

      if (errorRules.length > 0) {
        pushIssue({
          code: 'artifact_policy_errors',
          severity: 'error',
          artifactId: artifact.id,
          message: `Artifact "${artifact.name}" has blocking policy findings (${errorRules.join(', ')})`,
          rules: errorRules,
        });
      } else if (warningRules.length > 0) {
        pushIssue({
          code: 'artifact_policy_warnings',
          severity: 'warning',
          artifactId: artifact.id,
          message: `Artifact "${artifact.name}" has policy warnings (${warningRules.join(', ')})`,
          rules: warningRules,
        });
      }
    }
  }

  const sourceIds = new Set((spec.sources ?? []).map((source) => source.id));
  const sourceIdToArtifactId = new Map<string, string>();
  for (const source of spec.sources ?? []) {
    if (source.sourceArtifactId) {
      sourceIdToArtifactId.set(source.id, source.sourceArtifactId);
    }
  }

  for (const citationId of extractInlineCitationArtifactIdsFromValue(spec)) {
    if (artifactById.has(citationId)) continue;

    if (sourceIds.has(citationId)) {
      const sourceArtifactId = sourceIdToArtifactId.get(citationId);
      if (!sourceArtifactId || artifactById.has(sourceArtifactId)) continue;
      pushIssue({
        code: 'missing_citation_ref',
        severity: 'error',
        artifactId: sourceArtifactId,
        message: `Inline citation references missing artifact "${sourceArtifactId}"`,
      });
      continue;
    }

    pushIssue({
      code: 'missing_citation_ref',
      severity: 'error',
      artifactId: citationId,
      message: `Inline citation references missing artifact "${citationId}"`,
    });
  }

  return issues;
}

// ============================================================================
// Spec Creation
// ============================================================================

export interface CreateReportSpecOptions {
  sessionId: string;
  title: string;
  authors?: string[];
  abstract?: string;
  theme?: Partial<ReportTheme>;
}

/**
 * Create a new empty ReportSpecV1 with defaults.
 */
export function createReportSpec(opts: CreateReportSpecOptions): ReportSpecV1 {
  const now = Date.now();
  return {
    version: 1,
    title: opts.title,
    authors: opts.authors ?? [],
    abstract: opts.abstract,
    createdAt: now,
    modifiedAt: now,
    sessionId: opts.sessionId,
    theme: { ...DEFAULT_THEME, ...opts.theme },
    pages: [{ blocks: [] }],
    options: {
      includeProvenanceAttachment: false,
      citationStyle: 'none',
      includeProvenanceAppendix: false,
      provenanceDetailLevel: 'brief',
      header: {
        enabled: false,
        left: '',
        center: '',
        right: '',
      },
      footer: {
        enabled: true,
        left: '',
        center: '{{pageNumber}} / {{totalPages}}',
        right: formatBrandingLine(),
      },
      branding: DEFAULT_ARTIFACT_BRANDING_OPTIONS,
    },
  };
}

// ============================================================================
// Block Manipulation
// ============================================================================

/**
 * Add an artifact block to a page, mapping artifact.type → renderIntent.
 * Returns a new spec (immutable). Returns the original spec unchanged
 * if the artifact type cannot be rendered in a report.
 */
export function addArtifactBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  artifact: Artifact,
): ReportSpecV1 {
  const renderIntent = getRenderIntent(artifact.type, artifact.data, artifact.mimeType);
  if (!renderIntent) return spec;

  // Reference validation: ensure the mapping is valid
  if (!validateArtifactForRenderIntent(artifact.type, renderIntent)) return spec;

  const block: ArtifactBlock = {
    kind: 'artifact',
    artifactId: artifact.id,
    renderIntent,
    caption: artifact.name,
    citations: sourceIdsForArtifact(artifact, spec.sources),
  };

  return addBlock(withReportSourcesFromArtifacts(spec, [artifact]), pageIndex, block);
}

/**
 * Add a block to a specific page. Returns a new spec.
 */
export function addBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  block: ReportBlock,
): ReportSpecV1 {
  const pages = [...spec.pages];
  // Ensure page exists
  while (pages.length <= pageIndex) {
    pages.push({ blocks: [] });
  }
  pages[pageIndex] = {
    blocks: [...pages[pageIndex].blocks, block],
  };
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Insert a block at a specific index within a page. Returns a new spec.
 */
export function insertBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  blockIndex: number,
  block: ReportBlock,
): ReportSpecV1 {
  const pages = [...spec.pages];
  while (pages.length <= pageIndex) {
    pages.push({ blocks: [] });
  }

  const pageBlocks = [...pages[pageIndex].blocks];
  const clampedIndex = Math.max(0, Math.min(blockIndex, pageBlocks.length));
  pageBlocks.splice(clampedIndex, 0, block);
  pages[pageIndex] = { blocks: pageBlocks };

  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Replace a block at the given page/index. Returns original spec on invalid index.
 */
export function updateBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  blockIndex: number,
  block: ReportBlock,
): ReportSpecV1 {
  if (pageIndex >= spec.pages.length) return spec;
  const page = spec.pages[pageIndex];
  if (blockIndex >= page.blocks.length) return spec;

  const pages = [...spec.pages];
  const blocks = [...page.blocks];
  blocks[blockIndex] = block;
  pages[pageIndex] = { blocks };

  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Remove a block from a page. Returns a new spec.
 */
export function removeBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  blockIndex: number,
): ReportSpecV1 {
  if (pageIndex >= spec.pages.length) return spec;
  const page = spec.pages[pageIndex];
  if (blockIndex >= page.blocks.length) return spec;

  const pages = [...spec.pages];
  pages[pageIndex] = {
    blocks: page.blocks.filter((_, i) => i !== blockIndex),
  };
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Reorder blocks within a page. Returns a new spec.
 */
export function reorderBlocks(
  spec: ReportSpecV1,
  pageIndex: number,
  fromIndex: number,
  toIndex: number,
): ReportSpecV1 {
  if (pageIndex >= spec.pages.length) return spec;
  const blocks = [...spec.pages[pageIndex].blocks];
  if (fromIndex >= blocks.length || toIndex >= blocks.length) return spec;

  const [moved] = blocks.splice(fromIndex, 1);
  blocks.splice(toIndex, 0, moved);

  const pages = [...spec.pages];
  pages[pageIndex] = { blocks };
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Duplicate a block within a page, inserting the copy immediately after the source.
 * Returns a new spec. Returns original spec on invalid index.
 */
export function duplicateBlock(
  spec: ReportSpecV1,
  pageIndex: number,
  blockIndex: number,
): ReportSpecV1 {
  if (pageIndex >= spec.pages.length) return spec;
  const page = spec.pages[pageIndex];
  if (blockIndex >= page.blocks.length) return spec;

  const blocks = [...page.blocks];
  const clone = deepClone(blocks[blockIndex]);
  blocks.splice(blockIndex + 1, 0, clone);

  const pages = [...spec.pages];
  pages[pageIndex] = { blocks };
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Update report metadata fields. Returns a new spec.
 */
export function updateMetadata(
  spec: ReportSpecV1,
  updates: { title?: string; authors?: string[]; abstract?: string },
): ReportSpecV1 {
  return {
    ...spec,
    ...(updates.title !== undefined && { title: updates.title }),
    ...(updates.authors !== undefined && { authors: updates.authors }),
    ...(updates.abstract !== undefined && { abstract: updates.abstract }),
    modifiedAt: Date.now(),
  };
}

/**
 * Update report theme fields. Returns a new spec.
 */
export function updateTheme(
  spec: ReportSpecV1,
  updates: Partial<ReportTheme>,
): ReportSpecV1 {
  return {
    ...spec,
    theme: {
      ...spec.theme,
      ...updates,
      margins: { ...spec.theme.margins, ...(updates.margins ?? {}) },
    },
    modifiedAt: Date.now(),
  };
}

// ============================================================================
// Page Operations
// ============================================================================

/**
 * Insert an empty page at a given index. Returns a new spec.
 */
export function insertPage(
  spec: ReportSpecV1,
  atIndex: number,
): ReportSpecV1 {
  const pages = [...spec.pages];
  const clamped = Math.max(0, Math.min(atIndex, pages.length));
  pages.splice(clamped, 0, { blocks: [] });
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Remove a page by index. Refuses to remove the last remaining page.
 * Returns original spec on invalid index or if only 1 page exists.
 */
export function removePage(
  spec: ReportSpecV1,
  pageIndex: number,
): ReportSpecV1 {
  if (spec.pages.length <= 1) return spec;
  if (pageIndex < 0 || pageIndex >= spec.pages.length) return spec;

  const pages = spec.pages.filter((_, i) => i !== pageIndex);
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Duplicate a page (deep clone) and insert the copy immediately after the source.
 * Returns original spec on invalid index.
 */
export function duplicatePage(
  spec: ReportSpecV1,
  pageIndex: number,
): ReportSpecV1 {
  if (pageIndex < 0 || pageIndex >= spec.pages.length) return spec;

  const clone = deepClone(spec.pages[pageIndex]);
  const pages = [...spec.pages];
  pages.splice(pageIndex + 1, 0, clone);
  return { ...spec, pages, modifiedAt: Date.now() };
}

/**
 * Move a page from one index to another. Returns a new spec.
 * Returns original spec on invalid indices.
 */
export function reorderPages(
  spec: ReportSpecV1,
  fromIndex: number,
  toIndex: number,
): ReportSpecV1 {
  if (fromIndex === toIndex) return spec;
  if (fromIndex < 0 || fromIndex >= spec.pages.length) return spec;
  if (toIndex < 0 || toIndex >= spec.pages.length) return spec;

  const pages = [...spec.pages];
  const [moved] = pages.splice(fromIndex, 1);
  pages.splice(toIndex, 0, moved);
  return { ...spec, pages, modifiedAt: Date.now() };
}

// ============================================================================
// Publish Snapshot
// ============================================================================

/** Lineage context passed when publishing a new version of an existing report. */
export interface PublishLineageContext {
  previousArtifactId: string;
  lineageRootId: string;
  previousVersionNumber: number;
}

/**
 * Create an immutable Artifact from a report spec with a content-addressed ID.
 *
 * Flow:
 * 1. Canonicalize the spec (validate, deep-merge defaults, normalize markdown)
 * 2. Hash the canonical form (excluding createdAt) → content-addressed ID
 * 3. Store the full canonical spec as artifact data
 *
 * When `lineage` is provided, version metadata is attached to the artifact.
 * When omitted (first-time publish), the artifact self-references as lineage root.
 *
 * Throws if the spec fails validation.
 */
export async function publishSnapshot(
  spec: ReportSpecV1,
  lineage?: PublishLineageContext,
): Promise<{
  artifact: Artifact;
  canonical: CanonicalReportSpecV1;
  hash: string;
}> {
  // 1. Canonicalize
  const canonical = canonicalizeReportSpecV1(spec);

  // 2. Content-address (hashes canonical form minus createdAt)
  const { id: contentId, hash, serialized } = await contentAddressReportSpec(canonical);

  const sourceName = spec.title.endsWith(' (source)')
    ? spec.title
    : `${spec.title} (source)`;

  // 3. Build artifact
  const artifact: Artifact = {
    id: contentId,
    cellId: '',
    sessionId: spec.sessionId,
    name: sourceName,
    type: 'report_spec',
    mimeType: 'application/json',
    data: serialized,
    createdAt: Date.now(),
    metadata: {
      reportSpecVersion: spec.version,
      ...(shouldWriteBrandingMetadata(canonical.options?.branding)
        ? { branding: createArtifactBrandingRecord(canonical.options?.branding) }
        : {}),
      ...(lineage
        ? {
            lineageRootId: lineage.lineageRootId,
            previousReportSpecArtifactId: lineage.previousArtifactId,
            versionNumber: lineage.previousVersionNumber + 1,
          }
        : {
            lineageRootId: contentId,
            versionNumber: 1,
          }),
    },
    profile: 'ARCHIVE_PORTABLE',
    provenance: {
      generator: 'ReportBuilderService',
      generatorVersion: '1.0.0',
      dataHash: hash,
    },
  };

  return { artifact, canonical, hash };
}
