// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Zod Validation Schema + Canonicalization for ReportSpecV1
 *
 * Exports:
 *   - ReportSpecV1Schema      (Zod schema)
 *   - parseReportSpec          (strict parse, throws on failure)
 *   - validateReportSpec       (safe parse with error messages)
 *   - canonicalizeReportSpecV1 (parse → deep-merge defaults → normalize md)
 *   - canonicalHashInput       (strip createdAt for deterministic hashing)
 */

import { z } from 'zod';
import type {
  ReportSpecV1,
  ReportTheme,
  CanonicalReportSpecV1,
} from '../../types/report-spec';
import { DEFAULT_THEME } from './constants';
import {
  DEFAULT_ARTIFACT_BRANDING_OPTIONS,
  formatBrandingLine,
} from '../branding/ArtifactBrandingService';

// ============================================================================
// Block Schemas
// ============================================================================

const citableBlockFields = {
  citations: z.array(z.string().min(1)).optional(),
  provenance: z.object({
    sourceIds: z.array(z.string().min(1)).optional(),
    computedAt: z.string().optional(),
    inputs: z.array(z.string()).optional(),
  }).optional(),
};

const headingBlockSchema = z.object({
  kind: z.literal('heading'),
  level: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  text: z.string().min(1),
  ...citableBlockFields,
});

const paragraphBlockSchema = z.object({
  kind: z.literal('paragraph'),
  markdown: z.string(),
  ...citableBlockFields,
});

const renderIntentSchema = z.enum([
  'image',
  'dataset_preview',
  'json_document',
  'text_document',
  'html_snapshot',
]);

const artifactBlockSchema = z.object({
  kind: z.literal('artifact'),
  artifactId: z.string().min(1),
  renderIntent: renderIntentSchema,
  caption: z.string().optional(),
  options: z.object({
    maxWidth: z.number().positive().optional(),
    maxHeight: z.number().positive().optional(),
    maxRows: z.number().int().positive().optional(),
  }).optional(),
  ...citableBlockFields,
});

const tableBlockSchema = z.object({
  kind: z.literal('table'),
  headers: z.array(z.string()).min(1),
  rows: z.array(z.array(z.string())),
  caption: z.string().optional(),
  ...citableBlockFields,
});

// Field limits mirror the authoring-side metricGridBlockSchema so a bridged
// authoring block can never fail publish validation.
const metricGridBlockSchema = z.object({
  kind: z.literal('metric_grid'),
  metrics: z.array(z.object({
    label: z.string().min(1),
    value: z.string().min(1),
    detail: z.string().optional(),
  })).min(1),
  ...citableBlockFields,
});

const pageBreakBlockSchema = z.object({
  kind: z.literal('page_break'),
  ...citableBlockFields,
});

const spacerBlockSchema = z.object({
  kind: z.literal('spacer'),
  height: z.number().positive(),
  ...citableBlockFields,
});

const explanationSizeSchema = z.enum(['s', 'm', 'l']);

const artifactExplanationBlockSchema = z.object({
  kind: z.literal('artifact_explanation'),
  artifactId: z.string().min(1),
  size: explanationSizeSchema,
  text: z.string(),
  ...citableBlockFields,
});

const chartBlockSchema = z.object({
  kind: z.literal('chart'),
  spec: z.object({
    type: z.literal('vega-lite'),
    spec: z.object({}).passthrough(),
  }),
  caption: z.string().optional(),
  ...citableBlockFields,
});

// Field limits mirror the authoring-side diagramBlockSchema so a bridged
// authoring block can never fail publish validation.
const diagramBlockSchema = z.object({
  kind: z.literal('diagram'),
  spec: z.object({
    type: z.literal('mermaid'),
    code: z.string().min(1),
  }),
  caption: z.string().optional(),
  ...citableBlockFields,
});

const embeddedHtmlBlockSchema = z.object({
  kind: z.literal('embedded_html'),
  artifactId: z.string().min(1),
  caption: z.string().optional(),
  height: z.number().positive().optional(),
  ...citableBlockFields,
});

const reportBlockSchema = z.discriminatedUnion('kind', [
  headingBlockSchema,
  paragraphBlockSchema,
  artifactBlockSchema,
  tableBlockSchema,
  metricGridBlockSchema,
  chartBlockSchema,
  diagramBlockSchema,
  embeddedHtmlBlockSchema,
  pageBreakBlockSchema,
  spacerBlockSchema,
  artifactExplanationBlockSchema,
]);

// ============================================================================
// Theme & Page Schemas
// ============================================================================

const reportThemeSchema = z.object({
  pageSize: z.enum(['A4', 'LETTER']),
  landscape: z.boolean().optional(),
  margins: z.object({
    top: z.number().nonnegative(),
    right: z.number().nonnegative(),
    bottom: z.number().nonnegative(),
    left: z.number().nonnegative(),
  }),
  fonts: z.object({
    heading: z.string().min(1),
    body: z.string().min(1),
    mono: z.string().min(1),
  }),
  colors: z.object({
    primary: z.string().min(1),
    secondary: z.string().min(1),
    accent: z.string().min(1),
    text: z.string().min(1),
    background: z.string().min(1),
  }),
});

const reportPageSchema = z.object({
  blocks: z.array(reportBlockSchema),
});

const reportSourceSchema = z.object({
  id: z.string().min(1),
  label: z.string().min(1),
  title: z.string().optional(),
  url: z.string().url().optional(),
  retrievedAt: z.string().optional(),
  sourceArtifactId: z.string().optional(),
  note: z.string().optional(),
  provenance: z.array(z.object({
    endpoint: z.string().min(1),
    method: z.string().min(1),
    fetchedAt: z.string(),
    cacheStatus: z.enum(['fresh', 'cached']),
    responseHash: z.string(),
    parameterHash: z.string().optional(),
    connectorId: z.string().optional(),
  })).optional(),
});

// ============================================================================
// Options Schema
// ============================================================================

const artifactBrandingOptionsSchema = z.object({
  visibility: z.enum(['visible', 'metadata', 'off']).optional(),
  includeLogo: z.boolean().optional(),
  includeUrl: z.boolean().optional(),
}).optional();

const reportSpecOptionsSchema = z.object({
  /** Best-effort: embed provenance JSON as PDF attachment (M4.1) */
  includeProvenanceAttachment: z.boolean().optional(),
  /** Citation rendering style in published output */
  citationStyle: z.enum(['none', 'numeric_endnotes']).optional(),
  /** Include a provenance appendix with source artifact lineage */
  includeProvenanceAppendix: z.boolean().optional(),
  /** Provenance detail level for notes/appendix */
  provenanceDetailLevel: z.enum(['brief', 'full']).optional(),
  /** Header layout/content controls */
  header: z.object({
    enabled: z.boolean().optional(),
    left: z.string().optional(),
    center: z.string().optional(),
    right: z.string().optional(),
  }).optional(),
  /** Footer layout/content controls */
  footer: z.object({
    enabled: z.boolean().optional(),
    left: z.string().optional(),
    center: z.string().optional(),
    right: z.string().optional(),
  }).optional(),
  /** Branding policy for generated report exports */
  branding: artifactBrandingOptionsSchema,
});

// ============================================================================
// ReportSpecV1 Schema (with hard limits)
// ============================================================================

export const reportSpecV1Schema = z.object({
  version: z.literal(1),
  title: z.string().min(1),
  authors: z.array(z.string()),
  abstract: z.string().optional(),
  createdAt: z.number(),
  modifiedAt: z.number(),
  sessionId: z.string().min(1),
  // zod strips unknown keys, so without this the type id would silently vanish
  // at canonicalization.
  reportTypeId: z.string().optional(),
  theme: reportThemeSchema,
  pages: z.array(reportPageSchema).min(1),
  sources: z.array(reportSourceSchema).optional(),
  options: reportSpecOptionsSchema.optional(),
});

/** Inferred type from the Zod schema (equivalent to ReportSpecV1) */
export type ReportSpecV1Parsed = z.infer<typeof reportSpecV1Schema>;

// ============================================================================
// Parse & Validate Helpers
// ============================================================================

/**
 * Parse and validate a ReportSpecV1. Throws on failure.
 */
export function parseReportSpec(data: unknown): ReportSpecV1 {
  return reportSpecV1Schema.parse(data) as ReportSpecV1;
}

/**
 * Safe parse with error messages. Returns success/errors.
 */
export function validateReportSpec(data: unknown): { success: boolean; errors?: string[] } {
  const result = reportSpecV1Schema.safeParse(data);
  if (result.success) {
    return { success: true };
  }
  return {
    success: false,
    errors: result.error.issues.map(
      (issue) => `${issue.path.join('.')}: ${issue.message}`
    ),
  };
}

// ============================================================================
// Canonicalization
// ============================================================================

/**
 * Normalize markdown: CRLF → LF, trim trailing whitespace per line,
 * strip trailing empty lines.
 */
function normalizeMarkdown(md: string): string {
  return md
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n+$/, '');
}

/**
 * Deep-merge a partial theme with DEFAULT_THEME.
 * Merges at the nested object level (margins, fonts, colors) rather than
 * wholesale replacing the default.
 */
function deepMergeTheme(
  defaults: ReportTheme,
  partial?: Record<string, unknown>,
): ReportTheme {
  if (!partial) return { ...defaults };

  return {
    pageSize: (partial.pageSize as ReportTheme['pageSize']) ?? defaults.pageSize,
    landscape: typeof partial.landscape === 'boolean' ? partial.landscape : defaults.landscape,
    margins: {
      ...defaults.margins,
      ...((partial.margins as Partial<ReportTheme['margins']>) ?? {}),
    },
    fonts: {
      ...defaults.fonts,
      ...((partial.fonts as Partial<ReportTheme['fonts']>) ?? {}),
    },
    colors: {
      ...defaults.colors,
      ...((partial.colors as Partial<ReportTheme['colors']>) ?? {}),
    },
  };
}

/**
 * Pre-process raw input: deep-merge theme defaults and fill options defaults
 * before Zod validation. This avoids relying on Zod's .default() for nested
 * objects, which replaces the entire object rather than merging.
 */
function applyDefaults(input: unknown): unknown {
  if (!input || typeof input !== 'object') return input;
  const data = { ...(input as Record<string, unknown>) };

  // Deep-merge theme
  data.theme = deepMergeTheme(
    DEFAULT_THEME,
    data.theme as Record<string, unknown> | undefined,
  );

  // Fill options with defaults
  const existingOptions = (data.options as Record<string, unknown>) ?? {};
  const existingHeader = (
    existingOptions.header && typeof existingOptions.header === 'object'
      ? existingOptions.header
      : {}
  ) as Record<string, unknown>;
  const existingFooter = (
    existingOptions.footer && typeof existingOptions.footer === 'object'
      ? existingOptions.footer
      : {}
  ) as Record<string, unknown>;
  const existingBranding = (
    existingOptions.branding && typeof existingOptions.branding === 'object'
      ? existingOptions.branding
      : {}
  ) as Record<string, unknown>;
  const resolvedBranding = {
    ...DEFAULT_ARTIFACT_BRANDING_OPTIONS,
    ...existingBranding,
  };
  const defaultFooterRight = resolvedBranding.visibility === 'visible'
    ? formatBrandingLine(resolvedBranding)
    : '';

  data.options = {
    includeProvenanceAttachment: false,
    citationStyle: 'none',
    includeProvenanceAppendix: false,
    provenanceDetailLevel: 'brief',
    ...existingOptions,
    header: {
      enabled: false,
      left: '',
      center: '',
      right: '',
      ...existingHeader,
    },
    footer: {
      enabled: true,
      left: '',
      center: '{{pageNumber}} / {{totalPages}}',
      right: defaultFooterRight,
      ...existingFooter,
    },
    branding: resolvedBranding,
  };

  return data;
}

/**
 * Normalize all markdown content in the spec (abstract + paragraph blocks).
 */
function normalizeAllMarkdown(spec: ReportSpecV1): ReportSpecV1 {
  return {
    ...spec,
    abstract: spec.abstract ? normalizeMarkdown(spec.abstract) : spec.abstract,
    pages: spec.pages.map(page => ({
      blocks: page.blocks.map(block =>
        block.kind === 'paragraph'
          ? { ...block, markdown: normalizeMarkdown(block.markdown) }
          : block
      ),
    })),
  };
}

/**
 * Canonicalize a report spec:
 * 1. Pre-process: deep-merge defaults into raw input
 * 2. Parse with Zod (validates structure + hard limits)
 * 3. Normalize markdown (CRLF → LF, trim trailing whitespace)
 * 4. Return branded CanonicalReportSpecV1
 *
 * Throws ZodError on invalid input.
 */
export function canonicalizeReportSpecV1(input: unknown): CanonicalReportSpecV1 {
  const withDefaults = applyDefaults(input);
  const parsed = reportSpecV1Schema.parse(withDefaults) as ReportSpecV1;
  const normalized = normalizeAllMarkdown(parsed);
  return normalized as CanonicalReportSpecV1;
}

// ============================================================================
// Canonical Hash Input
// ============================================================================

/**
 * Strip fields that should not affect the content hash.
 *
 * `createdAt` is excluded because it is set once when the spec is first
 * created and should not change the hash when the spec is edited and
 * re-published. `modifiedAt` IS included because it represents the
 * content-modification timestamp.
 *
 * Returns a plain object suitable for stable serialization + sha256.
 */
export function canonicalHashInput(
  spec: CanonicalReportSpecV1,
): Omit<ReportSpecV1, 'createdAt'> {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { createdAt, ...rest } = spec as ReportSpecV1;
  return rest;
}
