// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * File Storage Types
 *
 * Type definitions for the file storage service.
 */
import type { ArtifactType } from '../../types/notebook';
export type FileSourceKind = 'upload' | 'artifact';
export interface FileSourceMetadata {
    /** Whether this file came from a direct upload or a prior artifact */
    sourceKind?: FileSourceKind;
    /** Original artifact ID when imported from the artifact library */
    sourceArtifactId?: string;
    /** Original artifact type when imported from the artifact library */
    sourceArtifactType?: ArtifactType;
    /** Original artifact session when imported from another analysis */
    sourceArtifactSessionId?: string;
    /** Original artifact name when imported from the artifact library */
    sourceArtifactName?: string;
}
/**
 * Record for a file stored in IndexedDB.
 */
export interface FileRecord extends FileSourceMetadata {
    /** Composite key: `${sessionId}:${filename}` */
    id: string;
    /** Session this file belongs to */
    sessionId: string;
    /** Original filename */
    filename: string;
    /** MIME type of the file */
    mimeType: string;
    /** File contents */
    data: ArrayBuffer;
    /** File size in bytes */
    size: number;
    /** Timestamp when file was uploaded */
    uploadedAt: number;
    /** Path in the Python sandbox filesystem */
    pythonPath: string;
}
/**
 * Metadata for a file (without the binary data).
 */
export interface FileMetadata extends FileSourceMetadata {
    id: string;
    sessionId: string;
    filename: string;
    mimeType: string;
    size: number;
    uploadedAt: number;
    pythonPath: string;
}
/**
 * Options for uploading a file.
 */
export interface UploadOptions {
    /** Stored display/path filename (defaults to original File.name) */
    filename?: string;
    /** Custom path in the Python filesystem (defaults to /uploads/filename) */
    pythonPath?: string;
    /** Source metadata for files derived from generated artifacts */
    source?: FileSourceMetadata;
}
