// Auto-generated by scripts/demo/build-recordings-manifest.js
// Do not edit directly.
import type { DemoChat, DemoCompare, DemoDebate } from '@/types/demo';
import { expectDemoChat, expectDemoCompare, expectDemoDebate } from '@/services/demo/demoRecordingGuards';
import recording_chat_c_itinerary_v1 from './recordings/chat_c_itinerary_v1.json';
import recording_chat_c_refactor_v1 from './recordings/chat_c_refactor_v1.json';
import recording_chat_cg_itinerary_v1 from './recordings/chat_cg_itinerary_v1.json';
import recording_chat_cg_refactor_v1 from './recordings/chat_cg_refactor_v1.json';
import recording_chat_co_itinerary_v1 from './recordings/chat_co_itinerary_v1.json';
import recording_chat_co_refactor_v1 from './recordings/chat_co_refactor_v1.json';
import recording_chat_cog_itinerary_v1 from './recordings/chat_cog_itinerary_v1.json';
import recording_chat_cog_refactor_v1 from './recordings/chat_cog_refactor_v1.json';
import recording_chat_g_itinerary_v1 from './recordings/chat_g_itinerary_v1.json';
import recording_chat_g_refactor_v1 from './recordings/chat_g_refactor_v1.json';
import recording_chat_o_itinerary_v1 from './recordings/chat_o_itinerary_v1.json';
import recording_chat_o_refactor_v1 from './recordings/chat_o_refactor_v1.json';
import recording_chat_og_itinerary_v1 from './recordings/chat_og_itinerary_v1.json';
import recording_chat_og_refactor_v1 from './recordings/chat_og_refactor_v1.json';
import recording_compare_cg_dinosaurs_v1 from './recordings/compare_cg_dinosaurs_v1.json';
import recording_compare_cg_roadtrip_v1 from './recordings/compare_cg_roadtrip_v1.json';
import recording_compare_co_bali_v1 from './recordings/compare_co_bali_v1.json';
import recording_compare_co_bestthaifood_v1 from './recordings/compare_co_bestthaifood_v1.json';
import recording_compare_og_disneyworld_v1 from './recordings/compare_og_disneyworld_v1.json';
import recording_compare_og_vaccines_v1 from './recordings/compare_og_vaccines_v1.json';
import recording_debate_cg_default_1 from './recordings/debate_cg_default_1.json';
import recording_debate_cg_george_1 from './recordings/debate_cg_george_1.json';
import recording_debate_cg_sage_1 from './recordings/debate_cg_sage_1.json';
import recording_debate_co_default_1 from './recordings/debate_co_default_1.json';
import recording_debate_co_george_1 from './recordings/debate_co_george_1.json';
import recording_debate_co_sage_1 from './recordings/debate_co_sage_1.json';
import recording_debate_og_default_1 from './recordings/debate_og_default_1.json';
import recording_debate_og_george_1 from './recordings/debate_og_george_1.json';
import recording_debate_og_sage_1 from './recordings/debate_og_sage_1.json';

export type DemoRecordingType = 'chat' | 'compare' | 'debate';

interface DemoRecordingEntryBase {
  id: string;
  providers: string[];
  title?: string | null;
  topic?: string | null;
}

export type DemoChatEntry = DemoRecordingEntryBase & { type: 'chat'; data: DemoChat };
export type DemoCompareEntry = DemoRecordingEntryBase & { type: 'compare'; data: DemoCompare };
export type DemoDebateEntry = DemoRecordingEntryBase & { type: 'debate'; data: DemoDebate };
export type DemoRecordingEntry = DemoChatEntry | DemoCompareEntry | DemoDebateEntry;
export type DemoRecordingEntryOf<K extends DemoRecordingType> = Extract<DemoRecordingEntry, { type: K }>;

// Each recording is validated against its domain type at load (see demoRecordingGuards).
export const demoRecordings: DemoRecordingEntry[] = [
  {
    id: 'chat_c_itinerary_v1',
    type: 'chat',
    providers: ['claude'],
    title: "Boston itinerary (Claude)",
    data: expectDemoChat(recording_chat_c_itinerary_v1, 'chat_c_itinerary_v1'),
  },
  {
    id: 'chat_c_refactor_v1',
    type: 'chat',
    providers: ['claude'],
    title: "Refactor ChatInput (Claude)",
    data: expectDemoChat(recording_chat_c_refactor_v1, 'chat_c_refactor_v1'),
  },
  {
    id: 'chat_cg_itinerary_v1',
    type: 'chat',
    providers: ['claude', 'google'],
    title: "NYC itinerary (Claude+Gemini)",
    data: expectDemoChat(recording_chat_cg_itinerary_v1, 'chat_cg_itinerary_v1'),
  },
  {
    id: 'chat_cg_refactor_v1',
    type: 'chat',
    providers: ['claude', 'google'],
    title: "Improve LiveTranscript (Claude + Gemini)",
    data: expectDemoChat(recording_chat_cg_refactor_v1, 'chat_cg_refactor_v1'),
  },
  {
    id: 'chat_co_itinerary_v1',
    type: 'chat',
    providers: ['claude', 'openai'],
    title: "Kyoto itinerary (Claude+OpenAI)",
    data: expectDemoChat(recording_chat_co_itinerary_v1, 'chat_co_itinerary_v1'),
  },
  {
    id: 'chat_co_refactor_v1',
    type: 'chat',
    providers: ['claude', 'openai'],
    title: "Code review: VoiceRecorder (Claude + ChatGPT)",
    data: expectDemoChat(recording_chat_co_refactor_v1, 'chat_co_refactor_v1'),
  },
  {
    id: 'chat_cog_itinerary_v1',
    type: 'chat',
    providers: ['claude', 'openai', 'google'],
    title: "San Francisco itinerary (Claude+OpenAI+Gemini)",
    data: expectDemoChat(recording_chat_cog_itinerary_v1, 'chat_cog_itinerary_v1'),
  },
  {
    id: 'chat_cog_refactor_v1',
    type: 'chat',
    providers: ['claude', 'openai', 'google'],
    title: "Collaborative refactor: PromptComposer (All AIs)",
    data: expectDemoChat(recording_chat_cog_refactor_v1, 'chat_cog_refactor_v1'),
  },
  {
    id: 'chat_g_itinerary_v1',
    type: 'chat',
    providers: ['google'],
    title: "Boston itinerary (Gemini)",
    data: expectDemoChat(recording_chat_g_itinerary_v1, 'chat_g_itinerary_v1'),
  },
  {
    id: 'chat_g_refactor_v1',
    type: 'chat',
    providers: ['google'],
    title: "Optimize FeedList (Gemini)",
    data: expectDemoChat(recording_chat_g_refactor_v1, 'chat_g_refactor_v1'),
  },
  {
    id: 'chat_o_itinerary_v1',
    type: 'chat',
    providers: ['openai'],
    title: "Boston itinerary (OpenAI)",
    data: expectDemoChat(recording_chat_o_itinerary_v1, 'chat_o_itinerary_v1'),
  },
  {
    id: 'chat_o_refactor_v1',
    type: 'chat',
    providers: ['openai'],
    title: "Add skeleton + tests (OpenAI)",
    data: expectDemoChat(recording_chat_o_refactor_v1, 'chat_o_refactor_v1'),
  },
  {
    id: 'chat_og_itinerary_v1',
    type: 'chat',
    providers: ['openai', 'google'],
    title: "Austin itinerary (OpenAI+Gemini)",
    data: expectDemoChat(recording_chat_og_itinerary_v1, 'chat_og_itinerary_v1'),
  },
  {
    id: 'chat_og_refactor_v1',
    type: 'chat',
    providers: ['openai', 'google'],
    title: "Redesign PersonaSheet (ChatGPT + Gemini)",
    data: expectDemoChat(recording_chat_og_refactor_v1, 'chat_og_refactor_v1'),
  },
  {
    id: 'compare_cg_dinosaurs_v1',
    type: 'compare',
    providers: ['claude', 'google'],
    title: "Dinosaur Extinction (Claude vs Gemini)",
    data: expectDemoCompare(recording_compare_cg_dinosaurs_v1, 'compare_cg_dinosaurs_v1'),
  },
  {
    id: 'compare_cg_roadtrip_v1',
    type: 'compare',
    providers: ['claude', 'google'],
    title: "Roadtrip to NYC (Claude vs Gemini)",
    data: expectDemoCompare(recording_compare_cg_roadtrip_v1, 'compare_cg_roadtrip_v1'),
  },
  {
    id: 'compare_co_bali_v1',
    type: 'compare',
    providers: ['claude', 'openai'],
    title: "Trip to Bali (Claude vs ChatGPT)",
    data: expectDemoCompare(recording_compare_co_bali_v1, 'compare_co_bali_v1'),
  },
  {
    id: 'compare_co_bestthaifood_v1',
    type: 'compare',
    providers: ['claude', 'openai'],
    title: "Best Thai Food in Austin (Claude vs ChatGPT)",
    data: expectDemoCompare(recording_compare_co_bestthaifood_v1, 'compare_co_bestthaifood_v1'),
  },
  {
    id: 'compare_og_disneyworld_v1',
    type: 'compare',
    providers: ['openai', 'google'],
    title: "Trip to Disney World (ChatGPT vs Gemini)",
    data: expectDemoCompare(recording_compare_og_disneyworld_v1, 'compare_og_disneyworld_v1'),
  },
  {
    id: 'compare_og_vaccines_v1',
    type: 'compare',
    providers: ['openai', 'google'],
    title: "Are Vaccines Safe? (ChatGPT vs Gemini)",
    data: expectDemoCompare(recording_compare_og_vaccines_v1, 'compare_og_vaccines_v1'),
  },
  {
    id: 'debate_cg_default_1',
    type: 'debate',
    providers: ['claude', 'google'],
    title: "Motion: Humanity has a moral imperative to colonize Mars. (Default)",
    topic: "Motion: Humanity has a moral imperative to colonize Mars.",
    data: expectDemoDebate(recording_debate_cg_default_1, 'debate_cg_default_1'),
  },
  {
    id: 'debate_cg_george_1',
    type: 'debate',
    providers: ['claude', 'google'],
    title: "Motion: A hot dog is a sandwich. (George persona)",
    topic: "Motion: A hot dog is a sandwich.",
    data: expectDemoDebate(recording_debate_cg_george_1, 'debate_cg_george_1'),
  },
  {
    id: 'debate_cg_sage_1',
    type: 'debate',
    providers: ['claude', 'google'],
    title: "Motion: We should ban animal testing. (Sage persona)",
    topic: "Motion: We should ban animal testing.",
    data: expectDemoDebate(recording_debate_cg_sage_1, 'debate_cg_sage_1'),
  },
  {
    id: 'debate_co_default_1',
    type: 'debate',
    providers: ['claude', 'openai'],
    title: "Motion: Homework should be abolished. (Default)",
    topic: "Motion: Homework should be abolished.",
    data: expectDemoDebate(recording_debate_co_default_1, 'debate_co_default_1'),
  },
  {
    id: 'debate_co_george_1',
    type: 'debate',
    providers: ['claude', 'openai'],
    title: "Motion: Social media should be regulated. (George persona)",
    topic: "Motion: Social media should be regulated.",
    data: expectDemoDebate(recording_debate_co_george_1, 'debate_co_george_1'),
  },
  {
    id: 'debate_co_sage_1',
    type: 'debate',
    providers: ['claude', 'openai'],
    title: "Motion: Money can buy happiness. (Sage persona)",
    topic: "Motion: Money can buy happiness.",
    data: expectDemoDebate(recording_debate_co_sage_1, 'debate_co_sage_1'),
  },
  {
    id: 'debate_og_default_1',
    type: 'debate',
    providers: ['openai', 'google'],
    title: "Motion: the Fairness Doctrine should be reinstated. (Default)",
    topic: "Motion: the Fairness Doctrine should be reinstated.",
    data: expectDemoDebate(recording_debate_og_default_1, 'debate_og_default_1'),
  },
  {
    id: 'debate_og_george_1',
    type: 'debate',
    providers: ['openai', 'google'],
    title: "Motion: Video Games are art. (George persona)",
    topic: "Motion: Video Games are art.",
    data: expectDemoDebate(recording_debate_og_george_1, 'debate_og_george_1'),
  },
  {
    id: 'debate_og_sage_1',
    type: 'debate',
    providers: ['openai', 'google'],
    title: "Motion: There should be a universal basic income. (Sage persona)",
    topic: "Motion: There should be a universal basic income.",
    data: expectDemoDebate(recording_debate_og_sage_1, 'debate_og_sage_1'),
  }
];

export const recordingsById = new Map(demoRecordings.map((entry) => [entry.id, entry]));

export function getRecordingsByProviders<K extends DemoRecordingType>(
  type: K,
  providers: string[]
): DemoRecordingEntryOf<K>[] {
  const normalized = comboKey(providers);
  return demoRecordings.filter(
    (entry): entry is DemoRecordingEntryOf<K> => entry.type === type && comboKey(entry.providers) === normalized
  );
}

export function comboKey(providers: string[]): string {
  const allowed = ['claude', 'openai', 'google'];
  const normalized = Array.from(new Set(providers.map((p) => p.toLowerCase()))).filter((p) => allowed.includes(p));
  normalized.sort((a, b) => allowed.indexOf(a) - allowed.indexOf(b));
  return normalized.join('+');
}
