// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Self-hosted map boundaries for Vega-Lite chart maps (docs/analyze-maps-plan.md).
 * Built by scripts/generate-boundaries.mjs into public/data/boundaries/ — TopoJSON in the
 * original us-atlas / world-atlas layout (same object names and ids) plus join-friendly
 * properties, and verbatim vega-datasets copies. Maps never depend on a third party.
 */

export const BOUNDARY_BASE_PATH = '/data/boundaries/';

export const BOUNDARY_FILES = {
  usStates: 'us-states@2.json',
  usCounties: 'us-counties@1.json',
  worldCountries: 'world-countries@1.json',
  vegaUs10m: 'vega-us-10m@1.json',
  vegaWorld110m: 'vega-world-110m@1.json',
} as const;

const hosted = (file: string) => `${BOUNDARY_BASE_PATH}${file}`;

const PACKAGE_CDN = String.raw`https?://(?:cdn\.jsdelivr\.net/npm|unpkg\.com)`;
const VEGA_DATASETS = String.raw`(?:https?://(?:vega\.github\.io/vega-datasets|(?:cdn\.jsdelivr\.net/npm|unpkg\.com)/vega-datasets(?:@[^/]+)?|raw\.githubusercontent\.com/vega/vega-datasets/[^/]+)/|\.?/?)`;

/**
 * Public boundary URLs models copy from examples → our hosted copy with the same layout.
 * Only layout-compatible rewrites: us-atlas v3 / world-atlas v2 files map to our enriched
 * copies (same objects + ids); vega-datasets maps (numeric ids, older layout) map to
 * verbatim copies — including the relative `data/us-10m.json` form from the Vega-Lite
 * examples, which otherwise resolves to an app route. Pre-projected `*-albers-*` files
 * are not hosted and stay untouched.
 */
const REWRITES: Array<{ pattern: RegExp; file: string }> = [
  { pattern: new RegExp(String.raw`^${PACKAGE_CDN}/us-atlas(?:@3[^/]*)?/(?:states|nation)-10m\.json(?:[?#].*)?$`), file: BOUNDARY_FILES.usStates },
  { pattern: new RegExp(String.raw`^${PACKAGE_CDN}/us-atlas(?:@3[^/]*)?/counties-10m\.json(?:[?#].*)?$`), file: BOUNDARY_FILES.usCounties },
  { pattern: new RegExp(String.raw`^${PACKAGE_CDN}/world-atlas(?:@2[^/]*)?/(?:countries|land)-(?:110m|50m|10m)\.json(?:[?#].*)?$`), file: BOUNDARY_FILES.worldCountries },
  { pattern: new RegExp(String.raw`^${VEGA_DATASETS}data/us-10m\.json(?:[?#].*)?$`), file: BOUNDARY_FILES.vegaUs10m },
  { pattern: new RegExp(String.raw`^${VEGA_DATASETS}data/world-110m\.json(?:[?#].*)?$`), file: BOUNDARY_FILES.vegaWorld110m },
];

export function rehostBoundaryUrl(url: string): string {
  const match = REWRITES.find(({ pattern }) => pattern.test(url.trim()));
  return match ? hosted(match.file) : url;
}

type LooseRecord = Record<string, unknown>;
const isRecord = (value: unknown): value is LooseRecord =>
  !!value && typeof value === 'object' && !Array.isArray(value);

// Inline data can be large and never holds a data-source url — don't walk it.
const SKIP_KEYS = new Set(['values', 'datasets']);

/** Map an object's string `url` fields through `rewrite`, anywhere in a Vega-Lite spec
 *  (top-level/layer data, lookup `from.data`, nested views). Returns the input object
 *  itself when nothing changed. */
function mapDataUrls(node: unknown, rewrite: (url: string) => string): unknown {
  if (Array.isArray(node)) {
    const mapped = node.map((item) => mapDataUrls(item, rewrite));
    return mapped.some((item, i) => item !== node[i]) ? mapped : node;
  }
  if (!isRecord(node)) return node;
  let out: LooseRecord | undefined;
  for (const [key, value] of Object.entries(node)) {
    if (SKIP_KEYS.has(key)) continue;
    const next = key === 'url' && typeof value === 'string' ? rewrite(value) : mapDataUrls(value, rewrite);
    if (next !== value) (out ??= { ...node })[key] = next;
  }
  return out ?? node;
}

/** Point every known public boundary URL in a spec at our hosted copy. */
export function rehostBoundaryUrls<T>(spec: T): T {
  return mapDataUrls(spec, rehostBoundaryUrl) as T;
}

/** Hosted boundary files a spec loads (file names under BOUNDARY_BASE_PATH). */
export function boundaryFilesIn(spec: unknown): string[] {
  const files = new Set<string>();
  const known = new Set<string>(Object.values(BOUNDARY_FILES));
  mapDataUrls(spec, (url) => {
    const path = url.trim().replace(/^https?:\/\/[^/]+/, '').split(/[?#]/)[0];
    if (path.startsWith(BOUNDARY_BASE_PATH)) {
      const file = path.slice(BOUNDARY_BASE_PATH.length);
      if (known.has(file)) files.add(file);
    }
    return url;
  });
  return [...files];
}
