// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import { decodeBase64ToUtf8, looksLikeBase64 } from '../../../lib/encoding/utf8Base64';
import type { Artifact } from '../../../types/notebook';

/**
 * Charts whose data is a session file (`"data": {"url": "/output/x.csv"}`) get
 * that file's rows inline (`"data": {"values": [...]}`).
 *
 * The output contract asks for inline `data.values`, but models sometimes point
 * at the CSV they just saved instead. That path exists only in the sandbox, so
 * the browser loads nothing and draws empty axes; exports can't load it either.
 * Applied when a report is captured (the round's files are in hand) and when a
 * stored report is rendered or published (the session's artifacts), which also
 * heals reports saved before this existed.
 */

/** Text of a session file by the path a chart named, or null when it isn't known. */
export type ChartFileReader = (path: string) => string | null;

type LooseRecord = Record<string, unknown>;

const isRecord = (value: unknown): value is LooseRecord =>
  !!value && typeof value === 'object' && !Array.isArray(value);

/**
 * A sandbox path a chart may name: /output, /data (except the app-hosted map
 * boundaries, which really are URLs), /uploads, with or without the leading
 * slash or the sandbox home. Returns the path relative to its folder.
 */
export function sessionDataPath(url: string): string | null {
  const trimmed = url.trim().replace(/^\.\//, '').replace(/^\/home\/user(?=\/)/, '');
  const match = /^\/?(output|data|uploads)\/(.+)$/.exec(trimmed);
  if (!match || /^https?:/i.test(trimmed)) return null;
  if (match[1] === 'data' && match[2].startsWith('boundaries/')) return null;
  return match[2];
}

function inferType(path: string, format: LooseRecord | undefined): string | null {
  const declared = typeof format?.type === 'string' ? format.type.toLowerCase() : null;
  if (declared) return declared;
  const ext = path.split('.').pop()?.toLowerCase();
  if (ext === 'csv') return 'csv';
  if (ext === 'tsv') return 'tsv';
  if (ext === 'json') return 'json';
  return null;
}

/** RFC 4180 rows: quoted fields, doubled quotes, delimiters and newlines inside quotes. */
function splitDelimited(text: string, delimiter: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    if (quoted) {
      if (char === '"' && text[i + 1] === '"') {
        field += '"';
        i += 1;
      } else if (char === '"') {
        quoted = false;
      } else {
        field += char;
      }
    } else if (char === '"' && field === '') {
      quoted = true;
    } else if (char === delimiter) {
      row.push(field);
      field = '';
    } else if (char === '\n' || char === '\r') {
      if (char === '\r' && text[i + 1] === '\n') i += 1;
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else {
      field += char;
    }
  }
  if (field !== '' || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows.filter((cells) => cells.some((cell) => cell.trim() !== ''));
}

const NUMBER = /^[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?$/;

/**
 * Delimited text as row objects, typed per column the way Vega's `parse: "auto"`
 * reads a CSV it loads: numbers and booleans when every value in the column is one,
 * empty cells as null, everything else (dates included) as strings.
 */
export function parseDelimitedRows(text: string, delimiter: string): LooseRecord[] {
  const [header, ...body] = splitDelimited(text.replace(/^﻿/, ''), delimiter);
  if (!header) return [];
  const names = header.map((name) => name.trim());
  const kinds = names.map((_, column) => {
    const values = body.map((cells) => (cells[column] ?? '').trim()).filter((value) => value !== '');
    if (values.length === 0) return 'string';
    if (values.every((value) => NUMBER.test(value))) return 'number';
    if (values.every((value) => value === 'true' || value === 'false')) return 'boolean';
    return 'string';
  });
  return body.map((cells) => {
    const record: LooseRecord = {};
    names.forEach((name, column) => {
      const raw = cells[column] ?? '';
      const value = raw.trim();
      record[name] = value === ''
        ? null
        : kinds[column] === 'number'
          ? Number(value)
          : kinds[column] === 'boolean'
            ? value === 'true'
            : raw;
    });
    return record;
  });
}

function valueAtProperty(value: unknown, property: unknown): unknown {
  if (typeof property !== 'string' || !property) return value;
  return property.split('.').reduce<unknown>((node, key) => (isRecord(node) ? node[key] : undefined), value);
}

/** The data definition with the file's rows inline, or null when it can't be inlined. */
function inlineDataDefinition(data: LooseRecord, read: ChartFileReader): LooseRecord | null {
  if (typeof data.url !== 'string') return null;
  const path = sessionDataPath(data.url);
  if (!path) return null;
  const format = isRecord(data.format) ? data.format : undefined;
  const type = inferType(path, format);
  if (type !== 'csv' && type !== 'tsv' && type !== 'dsv' && type !== 'json') return null;
  const text = read(data.url);
  if (text === null) return null;

  let values: unknown;
  if (type === 'json') {
    try {
      values = valueAtProperty(JSON.parse(text), format?.property);
    } catch {
      return null;
    }
    if (!Array.isArray(values)) return null;
  } else {
    const delimiter = type === 'tsv' ? '\t' : type === 'dsv' && typeof format?.delimiter === 'string' ? format.delimiter : ',';
    values = parseDelimitedRows(text, delimiter);
  }

  const inlined: LooseRecord = { ...data, values };
  delete inlined.url;
  delete inlined.format;
  // A declared field parse (e.g. dates) still applies to inline rows.
  if (format?.parse) inlined.format = { parse: format.parse };
  return inlined;
}

// Inline rows never name a file; don't walk them.
const SKIP_KEYS = new Set(['values', 'datasets']);

/** Every data definition in a Vega-Lite spec (top level, layers, lookups, nested views). */
export function inlineVegaLiteDataFiles<T>(spec: T, read: ChartFileReader): T {
  const walk = (node: unknown): unknown => {
    if (Array.isArray(node)) {
      const mapped = node.map(walk);
      return mapped.some((item, index) => item !== node[index]) ? mapped : node;
    }
    if (!isRecord(node)) return node;
    let out: LooseRecord | undefined;
    for (const [key, value] of Object.entries(node)) {
      if (SKIP_KEYS.has(key)) continue;
      const next = key === 'data' && isRecord(value)
        ? inlineDataDefinition(value, read) ?? walk(value)
        : walk(value);
      if (next !== value) (out ??= { ...node })[key] = next;
    }
    return out ?? node;
  };
  return walk(spec) as T;
}

/** Every chart block of a report spec. Returns the input itself when nothing changed. */
export function inlineChartDataFiles<T>(spec: T, read: ChartFileReader): T {
  if (!isRecord(spec) || !Array.isArray(spec.pages)) return spec;
  let changed = false;
  const pages = spec.pages.map((page) => {
    if (!isRecord(page) || !Array.isArray(page.blocks)) return page;
    let pageChanged = false;
    const blocks = page.blocks.map((block) => {
      if (!isRecord(block) || block.kind !== 'chart' || !isRecord(block.spec)) return block;
      const vega = block.spec.spec;
      const inlined = inlineVegaLiteDataFiles(vega, read);
      if (inlined === vega) return block;
      pageChanged = true;
      return { ...block, spec: { ...block.spec, spec: inlined } };
    });
    if (!pageChanged) return page;
    changed = true;
    return { ...page, blocks };
  });
  return changed ? ({ ...spec, pages } as T) : spec;
}

function baseName(path: string): string {
  return path.split('/').pop() ?? path;
}

/** Text of a stored file artifact (datasets are stored base64; text types raw). */
function artifactText(data: string): string {
  if (!looksLikeBase64(data)) return data;
  try {
    return decodeBase64ToUtf8(data);
  } catch {
    return data;
  }
}

/** Reads chart files from the session's artifacts, by file name. */
export function chartFileReaderFromArtifacts(artifacts: Artifact[] | undefined): ChartFileReader {
  const byName = new Map<string, Artifact>();
  for (const artifact of artifacts ?? []) {
    if (artifact.name && typeof artifact.data === 'string' && !artifact.data.startsWith('__')) {
      byName.set(artifact.name, artifact);
    }
  }
  return (url) => {
    const path = sessionDataPath(url);
    if (!path) return null;
    const artifact = byName.get(path) ?? byName.get(baseName(path));
    return artifact ? artifactText(artifact.data) : null;
  };
}
