// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { ModelParameters } from '../../config/modelConfigs';
import type { ProviderInfo } from '../../config/providers';
/**
 * Mode for AI selection - determines visual styling and behavior
 */
export type AISelectionMode = 'chat' | 'debate' | 'compare';
/**
 * Position in a debate (FOR or AGAINST the motion)
 */
export type DebatePosition = 'for' | 'against';
/**
 * Unified configuration for a single AI participant.
 * Used across Chat, Debate, and Compare modes.
 */
export interface AISelectionConfig {
    providerId: string;
    modelId: string;
    personalityId: string;
    parameters?: ModelParameters;
}
/**
 * Props for individual AI selection card
 */
export interface AISelectionCardProps {
    /** Current configuration for this AI */
    config: AISelectionConfig;
    /** Callback when configuration changes */
    onChange: (config: AISelectionConfig) => void;
    /** List of providers available for selection (those with API keys) */
    availableProviders: ProviderInfo[];
    /** Provider IDs to show duplicate warning for (other AIs' providers) */
    excludeProviders?: string[];
    /** Check if a personality is available (for premium gating) */
    canUsePersonality: (id: string) => boolean;
    /** The mode this card is being used in */
    mode?: AISelectionMode;
    /** Debate position (only for debate mode) */
    position?: DebatePosition;
    /** Custom label for the card (e.g., "AI 1", "AI 2") */
    label?: string;
    /** Index for default labeling (used if label not provided) */
    index?: number;
    /** Whether to show the selection summary footer */
    showSummary?: boolean;
    /** Whether the card is disabled */
    disabled?: boolean;
    /** Additional CSS classes */
    className?: string;
}
/**
 * Props for the parameter slider component
 */
export interface ParameterSliderProps {
    label: string;
    value: number;
    min: number;
    max: number;
    step: number;
    description: string;
    onChange: (value: number) => void;
}
/**
 * Visual styling configuration derived from mode and position
 */
export interface CardStyling {
    borderColor: string;
    badgeColor: string;
    badgeText: string;
    summaryBg: string;
    summaryBorder: string;
}
/**
 * Props for the selectable AI tile in the tile row
 */
export interface SelectableAITileProps {
    /** Provider ID */
    providerId: string;
    /** Whether this provider has an API key configured */
    hasApiKey: boolean;
    /** Selection number (1, 2, 3) or undefined if not selected */
    selectionNumber?: number;
    /** Callback when tile is clicked */
    onSelect: () => void;
    /** Callback to navigate to settings for unconfigured providers */
    onNavigateToSettings?: () => void;
    /** Tile size */
    size?: 'sm' | 'md';
}
/**
 * Props for the AI tile row component
 */
export interface AITileRowProps {
    /** Function to check if a provider has an API key */
    hasApiKey: (providerId: string) => boolean;
    /** Ordered array of selected provider IDs */
    selectedProviderIds: string[];
    /** Maximum number of selections allowed */
    maxSelections: number;
    /** Callback when a tile is toggled */
    onToggleSelection: (providerId: string) => void;
    /** Callback to navigate to settings */
    onNavigateToSettings?: () => void;
    /** Tile size */
    size?: 'sm' | 'md';
    /** Additional CSS classes */
    className?: string;
}
/**
 * Props for individual AI customization column
 */
export interface AICustomizationColumnProps {
    /** Current configuration for this AI */
    config: AISelectionConfig;
    /** Callback when configuration changes */
    onChange: (config: AISelectionConfig) => void;
    /** Selection slot number (1, 2, or 3) */
    selectionNumber: number;
    /** Check if a personality is available */
    canUsePersonality: (id: string) => boolean;
    /** Position label (e.g. "FOR", "AGAINST") — replaces the numbered badge */
    positionLabel?: string;
    /** Position color (e.g. "#22c55e") — overrides brandColor for border, glow, and accents */
    positionColor?: string;
    /** Additional CSS classes */
    className?: string;
}
/**
 * Props for the AI customization panel
 */
export interface AICustomizationPanelProps {
    /** Array of AI configurations */
    configs: AISelectionConfig[];
    /** Callback when any configuration changes */
    onChange: (configs: AISelectionConfig[]) => void;
    /** Check if a personality is available */
    canUsePersonality: (id: string) => boolean;
    /** Position labels per column (e.g. ["FOR", "AGAINST"]) */
    positionLabels?: string[];
    /** Position colors per column (e.g. ["#22c55e", "#ef4444"]) */
    positionColors?: string[];
    /** Additional CSS classes */
    className?: string;
}
/**
 * Props for the ChatAISelector component
 */
export interface ChatAISelectorProps {
    /** Array of AI configurations */
    configs: AISelectionConfig[];
    /** Callback when configurations change */
    onChange: (configs: AISelectionConfig[]) => void;
    /** Maximum number of AIs allowed (default: 3) */
    maxAIs?: number;
    /** Minimum number of AIs required (default: 0) */
    minAIs?: number;
    /** Disable all selection interactions */
    disabled?: boolean;
    /** Mode context for empty state messaging (default: 'chat') */
    mode?: 'chat' | 'compare';
    /** Check if a personality is available */
    canUsePersonality: (id: string) => boolean;
    /** Callback to navigate to settings page */
    onNavigateToSettings?: () => void;
    /** Additional CSS classes */
    className?: string;
}
/**
 * Props for the DebateAISelector component
 */
export interface DebateAISelectorProps {
    /** Configuration for the FOR debater */
    forConfig: AISelectionConfig;
    /** Configuration for the AGAINST debater */
    againstConfig: AISelectionConfig;
    /** Callback when the FOR debater changes */
    onForChange: (config: AISelectionConfig) => void;
    /** Callback when the AGAINST debater changes */
    onAgainstChange: (config: AISelectionConfig) => void;
    /** Check if a personality is available */
    canUsePersonality: (id: string) => boolean;
    /** Label for the FOR role badge */
    forRoleLabel?: string;
    /** Label for the AGAINST role badge */
    againstRoleLabel?: string;
    /** Description for the FOR role card */
    forRoleDescription?: string;
    /** Description for the AGAINST role card */
    againstRoleDescription?: string;
    /** Test id for the FOR card */
    forTestId?: string;
    /** Test id for the AGAINST card */
    againstTestId?: string;
    /** Additional CSS classes */
    className?: string;
}
