// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import { z } from 'zod';
import type {
  AnalysisArtifactBlock,
  AnalysisArtifactCalloutTone,
  AnalysisArtifactPage,
  AnalysisArtifactSource,
  AnalysisArtifactSpecV1,
  AnalysisArtifactSpecValidationResult,
} from '../../../types/analysis-artifact-spec';
import type { Artifact, BundleManifest } from '../../../types/notebook';
import type { ReportBlock, ReportSource, ReportSpecV1 } from '../../../types/report-spec';
import { decodePossiblyBase64Json, repairUtf8Mojibake } from '../../../lib/encoding/utf8Base64';
import { repairVegaLiteSpec } from '../charts/repairVegaLite';
import { chartFileReaderFromArtifacts, inlineChartDataFiles } from '../charts/inlineChartData';
import type { PresentationOverlayV1 } from '../../../types/presentation-overlay';
import { resolveOverlayTheme } from './PresentationOverlayService';
import {
  DEFAULT_ARTIFACT_BRANDING_OPTIONS,
  formatBrandingLine,
} from '../../branding/ArtifactBrandingService';
import { getRenderIntent } from '../../reports/ReportBuilderService';
import { normalizeReportTypeId, reportTypeHasCoverChrome, resolveReportTypeBaseTheme } from '../../reports/constants';
import { buildCitationOrder } from '../../reports/citations';

const PLACEHOLDER_PATTERNS = [
  /content omitted from history/i,
  /code omitted from history/i,
  /arguments omitted from history/i,
  /\[write_output_file\b/i,
  /\[execute_python\b/i,
];

const citationIdRegex = /^S\d+$/;
const citationMarkerRegex = /\[(S\d+)\]/g;
const slugRegex = /^[a-z0-9][a-z0-9-]*$/;

const baseBlockSchema = z.object({
  id: z.string().min(1).optional(),
  title: z.string().min(1).optional(),
  citations: z.array(z.string().regex(citationIdRegex)).optional(),
  provenance: z.object({
    sourceIds: z.array(z.string().regex(citationIdRegex)).optional(),
    computedAt: z.string().optional(),
    inputs: z.array(z.string()).optional(),
  }).optional(),
});

const markdownBlockSchema = baseBlockSchema.extend({
  kind: z.literal('markdown'),
  markdown: z.string().min(1),
});

const calloutBlockSchema = baseBlockSchema.extend({
  kind: z.literal('callout'),
  tone: z.enum(['info', 'success', 'warning', 'risk']).optional(),
  body: z.string().min(1),
});

const metricGridBlockSchema = baseBlockSchema.extend({
  kind: z.literal('metric_grid'),
  metrics: z.array(z.object({
    label: z.string().min(1),
    value: z.string().min(1),
    detail: z.string().optional(),
  })).min(1),
});

const tableBlockSchema = baseBlockSchema.extend({
  kind: z.literal('table'),
  headers: z.array(z.string()).min(1),
  rows: z.array(z.array(z.string())),
  caption: z.string().optional(),
});

const artifactRefBlockSchema = baseBlockSchema.extend({
  kind: z.literal('artifact_ref'),
  artifactId: z.string().min(1),
  caption: z.string().optional(),
});

// A Vega-Lite top-level spec, kept loose (the full grammar is large) but guarded
// against empty/garbage. No size limit: inline data is the chart. vega-lite
// compiles it at render/export.
const vegaLiteSpecSchema = z.object({}).passthrough()
  .refine(
    (s) => ['mark', 'layer', 'facet', 'hconcat', 'vconcat', 'concat', 'repeat', 'spec']
      .some((key) => key in (s as Record<string, unknown>)),
    { message: 'Vega-Lite spec must define a `mark` or a composition (layer/facet/concat/repeat)' },
  );

const chartBlockSchema = baseBlockSchema.extend({
  kind: z.literal('chart'),
  spec: z.object({
    type: z.literal('vega-lite'),
    spec: vegaLiteSpecSchema,
  }),
  caption: z.string().optional(),
});

// Mermaid source text. No mermaid.parse here — validation stays sync and the
// heavy renderer stays out of this path; invalid code degrades gracefully at
// render time (code-block fallback) instead of sinking the spec.
const diagramBlockSchema = baseBlockSchema.extend({
  kind: z.literal('diagram'),
  spec: z.object({
    type: z.literal('mermaid'),
    code: z.string().min(1),
  }),
  caption: z.string().optional(),
});

const embeddedHtmlBlockSchema = baseBlockSchema.extend({
  kind: z.literal('embedded_html'),
  artifactId: z.string().min(1),
  caption: z.string().optional(),
  height: z.number().positive().optional(),
});

const blockSchema = z.discriminatedUnion('kind', [
  markdownBlockSchema,
  calloutBlockSchema,
  metricGridBlockSchema,
  tableBlockSchema,
  artifactRefBlockSchema,
  chartBlockSchema,
  diagramBlockSchema,
  embeddedHtmlBlockSchema,
]);

const pageSchema = z.object({
  slug: z.string().regex(slugRegex),
  title: z.string().min(1),
  summary: z.string().optional(),
  blocks: z.array(blockSchema).min(1),
  relatedPageSlugs: z.array(z.string().regex(slugRegex)).optional(),
});

// App-injected verifiable fetch provenance (see injectSourceProvenance). Not
// model-authored, but validated here since the enriched spec is re-parsed on read.
const sourceFetchSchema = z.object({
  endpoint: z.string(),
  method: z.string(),
  fetchedAt: z.string(),
  cacheStatus: z.enum(['fresh', 'cached']),
  responseHash: z.string(),
  parameterHash: z.string().optional(),
  connectorId: z.string().optional(),
});

const sourceSchema = z.object({
  id: z.string().regex(citationIdRegex),
  label: z.string().min(1),
  title: z.string().optional(),
  url: z.string().url().optional(),
  retrievedAt: z.string().optional(),
  sourceArtifactId: z.string().optional(),
  note: z.string().optional(),
  provenance: z.array(sourceFetchSchema).optional(),
});

export const analysisArtifactSpecV1Schema = z.object({
  version: z.literal(1),
  kind: z.literal('analysis_artifact_spec'),
  title: z.string().min(1),
  audience: z.string().optional(),
  // Report type the model chose/was pinned to (e.g. 'data_dashboard'). Free-form + capped so a
  // slightly-off value never fails validation; the app reads it for the UI hint and per-type theming.
  reportTypeId: z.string().optional(),
  summary: z.string().min(1),
  createdAt: z.string().optional(),
  pages: z.array(pageSchema).min(1),
  sources: z.array(sourceSchema).optional(),
}).superRefine((spec, ctx) => {
  const serialized = JSON.stringify(spec);
  for (const pattern of PLACEHOLDER_PATTERNS) {
    if (pattern.test(serialized)) {
      ctx.addIssue({
        code: 'custom',
        message: 'Spec contains a history-compaction placeholder instead of real content',
      });
      break;
    }
  }

  const pageSlugs = new Set<string>();
  for (const page of spec.pages) {
    if (pageSlugs.has(page.slug)) {
      ctx.addIssue({
        code: 'custom',
        path: ['pages'],
        message: `Duplicate page slug "${page.slug}"`,
      });
    }
    pageSlugs.add(page.slug);
  }

  for (const page of spec.pages) {
    for (const relatedSlug of page.relatedPageSlugs || []) {
      if (!pageSlugs.has(relatedSlug)) {
        ctx.addIssue({
          code: 'custom',
          path: ['pages', page.slug, 'relatedPageSlugs'],
          message: `Related page slug "${relatedSlug}" does not exist`,
        });
      }
    }
  }

  const sourceIds = new Set((spec.sources || []).map((source) => source.id));
  if (sourceIds.size !== (spec.sources || []).length) {
    ctx.addIssue({
      code: 'custom',
      path: ['sources'],
      message: 'Source IDs must be unique',
    });
  }

  for (const citationId of collectCitationIds(spec)) {
    if (!sourceIds.has(citationId)) {
      ctx.addIssue({
        code: 'custom',
        path: ['sources'],
        message: `Citation "${citationId}" does not resolve to a source`,
      });
    }
  }
});

export function parseAnalysisArtifactSpec(input: unknown): AnalysisArtifactSpecV1 {
  return analysisArtifactSpecV1Schema.parse(input) as AnalysisArtifactSpecV1;
}

export function validateAnalysisArtifactSpec(input: unknown): AnalysisArtifactSpecValidationResult {
  const result = analysisArtifactSpecV1Schema.safeParse(input);
  if (result.success) {
    return { success: true, errors: [] };
  }

  return {
    success: false,
    errors: result.error.issues.map((issue) => (
      issue.path.length > 0
        ? `${issue.path.join('.')}: ${issue.message}`
        : issue.message
    )),
  };
}

type LooseRecord = Record<string, unknown>;

function slugifyTitle(input: string, fallback: string): string {
  const slug = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '');
  return slugRegex.test(slug) ? slug : fallback;
}

// Models naturally emit JSON scalars (numbers, booleans) where the schema wants
// display strings — a numeric table column is the canonical case, and one such
// cell used to fail the whole spec and silently downgrade the report to a plain
// data file. Coerce only finite scalars; objects/arrays stay untouched so
// genuinely malformed shapes still fail validation. A null cell means "empty".
function coerceScalarToString(value: unknown): unknown {
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'boolean') return String(value);
  if (value === null) return '';
  return value;
}

// Models write `"field": null` to mean "not applicable" — a live spec sank to a
// plain data file over `"sourceArtifactId": null` on two sources. `null` is
// valid NOWHERE in this schema (optional fields must be absent, required fields
// present), so dropping null-valued keys is always a strict improvement: the
// optional case becomes what the model meant, the required case fails with the
// same clarity as before. Array ELEMENTS are never removed (table cell
// positions must hold; null cells are handled by coerceScalarToString).
function stripNullFields(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripNullFields);
  if (value && typeof value === 'object') {
    const out: LooseRecord = {};
    for (const [key, entry] of Object.entries(value)) {
      if (entry === null) continue;
      out[key] = stripNullFields(entry);
    }
    return out;
  }
  return value;
}

function normalizeSpecBlock(block: unknown): unknown {
  if (!block || typeof block !== 'object') return block;
  const b = block as LooseRecord;

  // markdown blocks: accept `text` as an alias for the required `markdown`.
  if (b.kind === 'markdown' && typeof b.markdown !== 'string' && typeof b.text === 'string') {
    const { text, ...rest } = b;
    return { ...rest, markdown: text };
  }
  // callout blocks: accept `text` as an alias for the required `body`.
  if (b.kind === 'callout' && typeof b.body !== 'string' && typeof b.text === 'string') {
    const { text, ...rest } = b;
    return { ...rest, body: text };
  }
  // metric_grid: accept metric `sub` as an alias for the optional `detail`, and
  // scalar (numeric/boolean) label/value/detail.
  if (b.kind === 'metric_grid' && Array.isArray(b.metrics)) {
    return {
      ...b,
      metrics: b.metrics.map((metric) => {
        if (!metric || typeof metric !== 'object') return metric;
        const m = { ...(metric as LooseRecord) };
        if (m.detail === undefined && typeof m.sub === 'string') {
          m.detail = m.sub;
          delete m.sub;
        }
        m.label = coerceScalarToString(m.label);
        m.value = coerceScalarToString(m.value);
        if (m.detail !== undefined) m.detail = coerceScalarToString(m.detail);
        return m;
      }),
    };
  }
  // table blocks: accept scalar (numeric/boolean) headers and cells.
  if (b.kind === 'table') {
    return {
      ...b,
      headers: Array.isArray(b.headers) ? b.headers.map(coerceScalarToString) : b.headers,
      rows: Array.isArray(b.rows)
        ? b.rows.map((row) => (Array.isArray(row) ? row.map(coerceScalarToString) : row))
        : b.rows,
    };
  }
  // chart blocks: accept the raw Vega-Lite at `spec` (or a `vegaLite`/`vega_lite`/
  // `chart` alias) and wrap it in the canonical `{ type:'vega-lite', spec }` envelope.
  if (b.kind === 'chart') {
    const s = b.spec as LooseRecord | undefined;
    const alreadyWrapped = !!s && s.type === 'vega-lite' && !!s.spec && typeof s.spec === 'object';
    if (alreadyWrapped) return { ...b, spec: { ...s, spec: repairVegaLiteSpec(s.spec) } };

    const aliasKeys = ['spec', 'vegaLite', 'vega_lite', 'vegaLiteSpec', 'chart'];
    const raw = aliasKeys
      .map((key) => b[key])
      .find((v) => v && typeof v === 'object') as LooseRecord | undefined;
    if (raw) {
      const rest: LooseRecord = {};
      for (const [key, value] of Object.entries(b)) {
        if (!aliasKeys.includes(key)) rest[key] = value;
      }
      return { ...rest, spec: { type: 'vega-lite', spec: repairVegaLiteSpec(raw) } };
    }
  }
  // diagram blocks: accept `kind:'mermaid'` and bare Mermaid code at `code`/
  // `mermaid`/`mermaidCode`, wrapping into the canonical `{ type:'mermaid', code }`
  // envelope.
  if (b.kind === 'diagram' || b.kind === 'mermaid') {
    const s = b.spec as LooseRecord | undefined;
    const alreadyWrapped =
      b.kind === 'diagram' && !!s && s.type === 'mermaid' && typeof s.code === 'string';
    if (alreadyWrapped) return block;

    const aliasKeys = ['code', 'mermaid', 'mermaidCode', 'source'];
    const raw = [
      ...aliasKeys.map((key) => b[key]),
      s?.code,
    ].find((v) => typeof v === 'string' && v.trim().length > 0) as string | undefined;
    if (raw) {
      const rest: LooseRecord = {};
      for (const [key, value] of Object.entries(b)) {
        if (!aliasKeys.includes(key) && key !== 'spec') rest[key] = value;
      }
      return { ...rest, kind: 'diagram', spec: { type: 'mermaid', code: raw } };
    }
  }
  // markdown blocks that are entirely one ```mermaid fence: models emit these
  // unprompted — promote them to a first-class diagram block.
  if (b.kind === 'markdown' && typeof b.markdown === 'string') {
    const fence = /^\s*```mermaid\s*\n([\s\S]+?)\n?```\s*$/.exec(b.markdown);
    if (fence) {
      const rest = { ...b };
      delete rest.markdown;
      return { ...rest, kind: 'diagram', spec: { type: 'mermaid', code: fence[1] } };
    }
  }
  return block;
}

/**
 * Map common, reasonable field-name variations a model emits onto the strict
 * schema before validation: markdown/callout `text` → `markdown`/`body`, metric
 * `sub` → `detail`, and derive a unique `slug` for pages that omit one. Keeps the
 * canonical-artifact detector robust to prompt drift instead of silently
 * downgrading a valid report to a generic `data` file.
 */
export function normalizeAnalysisArtifactSpecCandidate(candidate: unknown): unknown {
  if (!candidate || typeof candidate !== 'object') return candidate;
  const spec = stripNullFields(candidate) as LooseRecord;
  if (!Array.isArray(spec.pages)) return candidate;

  const usedSlugs = new Set<string>();
  const pages = spec.pages.map((page, pageIndex) => {
    if (!page || typeof page !== 'object') return page;
    const p = page as LooseRecord;

    const baseSlug = typeof p.slug === 'string' && slugRegex.test(p.slug)
      ? p.slug
      : slugifyTitle(typeof p.title === 'string' ? p.title : '', `page-${pageIndex + 1}`);
    let unique = baseSlug;
    let suffix = 2;
    while (usedSlugs.has(unique)) {
      unique = `${baseSlug}-${suffix}`;
      suffix += 1;
    }
    usedSlugs.add(unique);

    let blocks = p.blocks;
    if (Array.isArray(blocks)) {
      const normalized = blocks.map(normalizeSpecBlock);
      const expanded = normalized.flatMap(splitMarkdownPipeTables);
      // Page cap is 80 blocks; if expansion would overflow, keep the un-split form.
      blocks = expanded.length <= 80 ? expanded : normalized;
    }
    return { ...p, slug: unique, blocks };
  });

  return normalizeSpecSourceIds(normalizeSpecSources({ ...spec, pages }));
}

const pipeRowRegex = /^\s*\|.*\|\s*$/;
const pipeSeparatorRegex = /^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)+\|?\s*$/;

function parsePipeRow(line: string): string[] {
  let trimmed = line.trim();
  if (trimmed.startsWith('|')) trimmed = trimmed.slice(1);
  if (trimmed.endsWith('|')) trimmed = trimmed.slice(0, -1);
  return trimmed.split(/(?<!\\)\|/).map((cell) => cell.trim().replace(/\\\|/g, '|'));
}

/**
 * Models author GFM pipe tables inside `markdown` blocks despite the contract
 * saying to use `table` blocks. The web viewer renders them (remark-gfm), but
 * the PDF/DOCX/PPTX markdown subsets don't — raw `| … | … |` text leaked into
 * a live ARB deck. Split such blocks into markdown + first-class `table`
 * blocks so every surface renders a real table. A table that can't fit the
 * table schema (columns/rows/cell caps) is left as markdown — never worse.
 */
function splitMarkdownPipeTables(block: unknown): unknown[] {
  if (!block || typeof block !== 'object') return [block];
  const b = block as LooseRecord;
  const isMarkdownBlock = b.kind === 'markdown' && typeof b.markdown === 'string';
  // Callouts leak too (live case: a "Suppression latency summary" table inside
  // a warning callout printed as raw pipes) — same split; the first prose
  // segment keeps the callout kind + tone, trailing prose becomes markdown.
  const isCalloutBlock = b.kind === 'callout' && typeof b.body === 'string';
  if (!isMarkdownBlock && !isCalloutBlock) return [block];
  const sourceText = (isMarkdownBlock ? b.markdown : b.body) as string;
  if (!sourceText.includes('|')) return [block];

  const lines = sourceText.split('\n');
  type Segment = { kind: 'prose'; lines: string[] } | { kind: 'table'; headers: string[]; rows: string[][] };
  const segments: Segment[] = [];
  let prose: string[] = [];
  let index = 0;
  while (index < lines.length) {
    const line = lines[index];
    const next = lines[index + 1];
    if (pipeRowRegex.test(line) && next !== undefined && pipeSeparatorRegex.test(next)) {
      const headers = parsePipeRow(line);
      const rows: string[][] = [];
      let bodyIndex = index + 2;
      while (bodyIndex < lines.length && pipeRowRegex.test(lines[bodyIndex])) {
        const cells = parsePipeRow(lines[bodyIndex]);
        rows.push(headers.map((_, column) => cells[column] ?? ''));
        bodyIndex += 1;
      }
      const fitsTableSchema =
        headers.length >= 2 && headers.length <= 12 &&
        rows.length >= 1 && rows.length <= 200 &&
        headers.every((header) => header.length > 0 && header.length <= 240) &&
        rows.every((row) => row.every((cell) => cell.length <= 1_000));
      if (fitsTableSchema) {
        if (prose.length > 0) {
          segments.push({ kind: 'prose', lines: prose });
          prose = [];
        }
        segments.push({ kind: 'table', headers, rows });
        index = bodyIndex;
        continue;
      }
    }
    prose.push(line);
    index += 1;
  }
  if (prose.length > 0) segments.push({ kind: 'prose', lines: prose });
  if (!segments.some((segment) => segment.kind === 'table')) return [block];

  const out: LooseRecord[] = [];
  let proseEmitted = false;
  for (const segment of segments) {
    if (segment.kind === 'prose') {
      const prose = segment.lines.join('\n').trim();
      if (prose.length === 0) continue;
      if (isCalloutBlock && !proseEmitted) {
        out.push({ kind: 'callout', ...(typeof b.tone === 'string' ? { tone: b.tone } : {}), body: prose });
      } else {
        out.push({ kind: 'markdown', markdown: prose });
      }
      proseEmitted = true;
    } else {
      out.push({ kind: 'table', headers: segment.headers, rows: segment.rows });
    }
  }
  if (out.length === 0) return [block];

  // The original block's id/title/citations/provenance ride on the first
  // emitted block; table-cell [S#] markers are collected by the bridge anyway.
  const carried = { ...b };
  delete carried.markdown;
  delete carried.body;
  delete carried.tone;
  delete carried.kind;
  out[0] = { ...carried, ...out[0] };
  return out;
}

/**
 * Repair model-authored source entries that are semantically right but
 * schema-fatal. The live case: two internal documents cited as
 * `"url": "internal"` — correct meaning, but `url` requires a real link, and
 * that one word sank a whole 10-page report to a plain data file. A non-URL
 * `url` is really a note, so it moves there (when no note exists) and the
 * field is dropped; empty-string urls are dropped outright.
 */
function normalizeSpecSources(spec: LooseRecord): LooseRecord {
  const sources = spec.sources;
  if (!Array.isArray(sources) || sources.length === 0) return spec;

  const isParseableUrl = (value: string): boolean => {
    try {
      new URL(value);
      return true;
    } catch {
      return false;
    }
  };

  return {
    ...spec,
    sources: sources.map((source) => {
      if (!source || typeof source !== 'object') return source;
      const s = { ...(source as LooseRecord) };
      if (typeof s.url === 'string' && !isParseableUrl(s.url)) {
        if (s.note === undefined && s.url.trim().length > 0) s.note = s.url.trim();
        delete s.url;
      }
      return s;
    }),
  };
}

/**
 * Losslessly renumber model-invented citation id schemes onto the canonical
 * `S1, S2, …` ids the schema and renderers require. GPT-5.6's first live report
 * cited sources as `SF-D2`, `SF-D5`, … — internally consistent and perfectly
 * usable, but `/^S\d+$/` rejected the whole spec and the report silently became
 * a plain `data` artifact. Ids are internal references, so renaming them AND
 * rewriting every inline `[oldId]` marker in the same pass preserves meaning
 * exactly. Applies only when sources exist with unique string ids and at least
 * one id is non-conforming; no-op otherwise.
 */
function normalizeSpecSourceIds(spec: LooseRecord): LooseRecord {
  const sources = spec.sources;
  if (!Array.isArray(sources) || sources.length === 0) return spec;

  const ids = sources.map((source) =>
    source && typeof source === 'object' ? (source as LooseRecord).id : undefined,
  );
  const allStrings = ids.every((id): id is string => typeof id === 'string' && id.trim().length > 0);
  if (!allStrings) return spec;
  if (new Set(ids).size !== ids.length) return spec;
  if (ids.every((id) => /^S\d+$/.test(id))) return spec;

  const idMap = new Map(ids.map((id, index) => [id, `S${index + 1}`]));
  const markerPattern = new RegExp(
    `\\[(${ids.map((id) => id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\]`,
    'g',
  );
  const rewriteMarkers = (value: unknown): unknown => {
    if (typeof value === 'string') {
      return value.replace(markerPattern, (_match, oldId: string) => `[${idMap.get(oldId)}]`);
    }
    if (Array.isArray(value)) return value.map(rewriteMarkers);
    if (value && typeof value === 'object') {
      return Object.fromEntries(
        Object.entries(value as LooseRecord).map(([key, entry]) => [key, rewriteMarkers(entry)]),
      );
    }
    return value;
  };

  return {
    ...spec,
    pages: rewriteMarkers(spec.pages),
    sources: sources.map((source) => {
      if (!source || typeof source !== 'object') return source;
      const record = source as LooseRecord;
      return { ...record, id: idMap.get(record.id as string) };
    }),
  };
}

export function tryParseAnalysisArtifactSpecText(raw: string): AnalysisArtifactSpecV1 | null {
  try {
    // Heal legacy/echoed mojibake (UTF-8 decoded as Latin-1, e.g. ’ → â€™) before
    // parsing. This is the single chokepoint for both rendering (fixes already-
    // corrupted reports on display) and capture (a model that copies visible
    // mojibake from a prior version gets it repaired before we persist the spec),
    // so the corruption can't self-perpetuate across edits. Safe no-op on clean text.
    const parsed = JSON.parse(repairUtf8Mojibake(decodePossiblyBase64Json(raw))) as unknown;
    if (!parsed || typeof parsed !== 'object') return null;
    const candidate = parsed as { version?: unknown; kind?: unknown };
    if (candidate.version !== 1 || candidate.kind !== 'analysis_artifact_spec') return null;
    return ensureBlockIds(parseAnalysisArtifactSpec(normalizeAnalysisArtifactSpecCandidate(candidate)));
  } catch {
    return null;
  }
}

/**
 * Assigns a stable, NON-positional id (`b<seq>`) to every block lacking one, so a
 * block keeps its identity across reorders, edits, and versions. Positional ids
 * (`block-<page>-<index>`) would defeat that, so we use a monotonic counter that
 * skips ids already present. Preserves existing ids; idempotent (returns the same
 * reference when nothing changes). App-owned: the model rarely sets ids, never
 * stably — Phase 3 targeted edits + reorder depend on this.
 */
export function ensureBlockIds(spec: AnalysisArtifactSpecV1): AnalysisArtifactSpecV1 {
  const used = new Set<string>();
  for (const page of spec.pages) {
    for (const block of page.blocks) {
      if (block.id) used.add(block.id);
    }
  }
  let seq = 0;
  const nextId = (): string => {
    let id: string;
    do { seq += 1; id = `b${seq}`; } while (used.has(id));
    used.add(id);
    return id;
  };

  let changed = false;
  const pages = spec.pages.map((page) => {
    let pageChanged = false;
    const blocks = page.blocks.map((block) => {
      if (block.id) return block;
      pageChanged = true;
      changed = true;
      return { ...block, id: nextId() };
    });
    return pageChanged ? { ...page, blocks } : page;
  });

  return changed ? { ...spec, pages } : spec;
}

function collectCitationIds(spec: AnalysisArtifactSpecV1): Set<string> {
  const ids = new Set<string>();
  const addFromText = (text: string | undefined) => {
    if (!text) return;
    // matchAll clones the regex internally, so the shared global `citationMarkerRegex`
    // never carries `lastIndex` state between calls (the prior exec() loop did).
    for (const match of text.matchAll(citationMarkerRegex)) {
      ids.add(match[1]);
    }
  };

  addFromText(spec.summary);
  for (const page of spec.pages) {
    addFromText(page.summary);
    for (const block of page.blocks) {
      for (const citation of block.citations || []) ids.add(citation);
      if (block.kind === 'markdown') addFromText(block.markdown);
      if (block.kind === 'callout') addFromText(block.body);
      if (block.kind === 'table') addFromText(block.caption);
      if (block.kind === 'chart') addFromText(block.caption);
      if (block.kind === 'diagram') addFromText(block.caption);
      if (block.kind === 'artifact_ref') addFromText(block.caption);
    }
  }

  return ids;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function slugToFilename(slug: string): string {
  return slug === 'index' ? 'index.html' : `${slug}.html`;
}

function renderCitationLinks(text: string, sources: AnalysisArtifactSource[]): string {
  const sourceIds = new Set(sources.map((source) => source.id));
  return escapeHtml(text).replace(/\[(S\d+)\]/g, (match, sourceId) => {
    if (!sourceIds.has(sourceId)) return match;
    return `<a class="citation" href="sources.html#${sourceId}">[${sourceId}]</a>`;
  });
}

function renderInlineMarkdown(text: string, sources: AnalysisArtifactSource[]): string {
  return renderCitationLinks(text, sources)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>');
}

function renderMarkdownLite(markdown: string, sources: AnalysisArtifactSource[]): string {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n');
  const html: string[] = [];
  let listOpen = false;

  const closeList = () => {
    if (listOpen) {
      html.push('</ul>');
      listOpen = false;
    }
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      closeList();
      continue;
    }
    if (trimmed.startsWith('### ')) {
      closeList();
      html.push(`<h3>${renderInlineMarkdown(trimmed.slice(4), sources)}</h3>`);
      continue;
    }
    if (trimmed.startsWith('## ')) {
      closeList();
      html.push(`<h2>${renderInlineMarkdown(trimmed.slice(3), sources)}</h2>`);
      continue;
    }
    if (trimmed.startsWith('- ')) {
      if (!listOpen) {
        html.push('<ul>');
        listOpen = true;
      }
      html.push(`<li>${renderInlineMarkdown(trimmed.slice(2), sources)}</li>`);
      continue;
    }
    closeList();
    html.push(`<p>${renderInlineMarkdown(trimmed, sources)}</p>`);
  }

  closeList();
  return html.join('\n');
}

function renderNavigation(spec: AnalysisArtifactSpecV1, currentSlug: string): string {
  const pageLinks = spec.pages.map((page) => {
    const filename = slugToFilename(page.slug);
    const activeClass = page.slug === currentSlug ? ' class="active"' : '';
    return `<a${activeClass} href="${filename}">${escapeHtml(page.title)}</a>`;
  });
  if ((spec.sources || []).length > 0) {
    pageLinks.push(`<a${currentSlug === 'sources' ? ' class="active"' : ''} href="sources.html">Sources</a>`);
  }
  return `<nav class="site-nav">${pageLinks.join('')}</nav>`;
}

function renderBlock(block: AnalysisArtifactBlock, sources: AnalysisArtifactSource[]): string {
  const title = block.title ? `<h2>${escapeHtml(block.title)}</h2>` : '';

  if (block.kind === 'markdown') {
    return `<section class="content-block">${title}<div class="markdown">${renderMarkdownLite(block.markdown, sources)}</div></section>`;
  }

  if (block.kind === 'callout') {
    const tone = block.tone || 'info';
    return `<section class="callout ${tone}">${title}<p>${renderInlineMarkdown(block.body, sources)}</p></section>`;
  }

  if (block.kind === 'metric_grid') {
    const metrics = block.metrics.map((metric) => [
      '<div class="metric">',
      `<div class="metric-value">${escapeHtml(metric.value)}</div>`,
      `<div class="metric-label">${escapeHtml(metric.label)}</div>`,
      metric.detail ? `<div class="metric-detail">${escapeHtml(metric.detail)}</div>` : '',
      '</div>',
    ].join(''));
    return `<section class="content-block">${title}<div class="metric-grid">${metrics.join('')}</div></section>`;
  }

  if (block.kind === 'table') {
    const header = block.headers.map((cell) => `<th>${escapeHtml(cell)}</th>`).join('');
    const rows = block.rows.map((row) => `<tr>${row.map((cell) => `<td>${renderInlineMarkdown(cell, sources)}</td>`).join('')}</tr>`).join('');
    const caption = block.caption ? `<caption>${renderInlineMarkdown(block.caption, sources)}</caption>` : '';
    return `<section class="content-block">${title}<div class="table-wrap"><table>${caption}<thead><tr>${header}</tr></thead><tbody>${rows}</tbody></table></div></section>`;
  }

  if (block.kind === 'chart') {
    // The standalone-HTML path is sync; live chart rendering happens in the app
    // and in image-based exports. Emit a labelled placeholder + caption here.
    return [
      '<section class="content-block chart-block">',
      title,
      '<div class="chart-placeholder"><em>Interactive chart — view in the app or an export.</em></div>',
      block.caption ? `<p class="figcaption">${renderInlineMarkdown(block.caption, sources)}</p>` : '',
      '</section>',
    ].join('');
  }

  if (block.kind === 'diagram') {
    // Same sync constraint as charts: no live Mermaid here. Emit the source so
    // the diagram's content is never lost in this legacy path.
    return [
      '<section class="content-block diagram-block">',
      title,
      `<pre class="diagram-source">${escapeHtml(block.spec.code)}</pre>`,
      block.caption ? `<p class="figcaption">${renderInlineMarkdown(block.caption, sources)}</p>` : '',
      '</section>',
    ].join('');
  }

  if (block.kind === 'embedded_html') {
    return [
      '<section class="content-block embedded-html-ref">',
      title,
      '<div class="artifact-ref-card">',
      '<strong>Interactive component</strong>',
      `<code>${escapeHtml(block.artifactId)}</code>`,
      block.caption ? `<p>${renderInlineMarkdown(block.caption, sources)}</p>` : '',
      '</div>',
      '</section>',
    ].join('');
  }

  return [
    '<section class="content-block artifact-ref">',
    title,
    '<div class="artifact-ref-card">',
    '<strong>Referenced artifact</strong>',
    `<code>${escapeHtml(block.artifactId)}</code>`,
    block.caption ? `<p>${renderInlineMarkdown(block.caption, sources)}</p>` : '',
    '</div>',
    '</section>',
  ].join('');
}

function renderPageHtml(spec: AnalysisArtifactSpecV1, page: AnalysisArtifactPage): string {
  const sources = spec.sources || [];
  const blocks = page.blocks.map((block) => renderBlock(block, sources)).join('\n');
  const related = (page.relatedPageSlugs || [])
    .map((slug) => spec.pages.find((candidate) => candidate.slug === slug))
    .filter((relatedPage): relatedPage is AnalysisArtifactPage => Boolean(relatedPage))
    .map((relatedPage) => `<a href="${slugToFilename(relatedPage.slug)}">${escapeHtml(relatedPage.title)}</a>`)
    .join('');

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${escapeHtml(page.title)} - ${escapeHtml(spec.title)}</title>`,
    '<link rel="stylesheet" href="styles.css">',
    '</head>',
    '<body>',
    '<div class="app-shell">',
    '<aside>',
    `<div class="brand">${escapeHtml(spec.title)}</div>`,
    spec.audience ? `<div class="audience">${escapeHtml(spec.audience)}</div>` : '',
    renderNavigation(spec, page.slug),
    '</aside>',
    '<main>',
    '<header class="page-header">',
    `<p class="eyebrow">${escapeHtml(spec.audience || 'Analysis')}</p>`,
    `<h1>${escapeHtml(page.title)}</h1>`,
    page.summary ? `<p class="summary">${renderInlineMarkdown(page.summary, sources)}</p>` : '',
    '</header>',
    blocks,
    related ? `<section class="related"><h2>Related</h2><div>${related}</div></section>` : '',
    '</main>',
    '</div>',
    '</body>',
    '</html>',
  ].filter(Boolean).join('\n');
}

function renderSourceFetchRows(source: AnalysisArtifactSource): string {
  const fetches = source.provenance ?? [];
  if (fetches.length === 0) return '';
  const rows = fetches.map((fetch) => [
    '<div class="source-fetch">',
    `<code class="source-fetch-req">${escapeHtml(fetch.method)} ${escapeHtml(fetch.endpoint.replace(/^https?:\/\//i, ''))}</code>`,
    '<div class="source-fetch-meta">',
    `<span>${escapeHtml(fetch.fetchedAt)}</span>`,
    `<span class="source-chip source-chip--${fetch.cacheStatus === 'fresh' ? 'fresh' : 'cached'}">${fetch.cacheStatus}</span>`,
    `<span class="source-chip source-chip--hash" title="sha-256 ${escapeHtml(fetch.responseHash)}">sha-256 ${escapeHtml(fetch.responseHash.slice(0, 12))}</span>`,
    '</div>',
    '</div>',
  ].join('\n')).join('\n');
  return `<div class="source-fetches"><p class="source-meta">Data provenance</p>${rows}</div>`;
}

function renderSourcesHtml(spec: AnalysisArtifactSpecV1): string {
  const sources = spec.sources || [];
  const sourceItems = sources.map((source) => [
    `<article id="${source.id}" class="source-card">`,
    `<div class="source-id">${source.id}</div>`,
    `<h2>${escapeHtml(source.title || source.label)}</h2>`,
    `<p>${escapeHtml(source.label)}</p>`,
    source.url ? `<a href="${escapeHtml(source.url)}" rel="noreferrer noopener" target="_blank">${escapeHtml(source.url)}</a>` : '',
    source.retrievedAt ? `<p class="source-meta">Retrieved: ${escapeHtml(source.retrievedAt)}</p>` : '',
    source.sourceArtifactId ? `<p class="source-meta">Artifact: ${escapeHtml(source.sourceArtifactId)}</p>` : '',
    source.note ? `<p>${escapeHtml(source.note)}</p>` : '',
    renderSourceFetchRows(source),
    '</article>',
  ].filter(Boolean).join('\n'));

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>Sources - ${escapeHtml(spec.title)}</title>`,
    '<link rel="stylesheet" href="styles.css">',
    '</head>',
    '<body>',
    '<div class="app-shell">',
    '<aside>',
    `<div class="brand">${escapeHtml(spec.title)}</div>`,
    renderNavigation(spec, 'sources'),
    '</aside>',
    '<main>',
    '<header class="page-header">',
    '<p class="eyebrow">Provenance</p>',
    '<h1>Sources</h1>',
    '<p class="summary">Only sources declared in the validated structured source are listed here.</p>',
    '</header>',
    `<section class="sources-list">${sourceItems}</section>`,
    '</main>',
    '</div>',
    '</body>',
    '</html>',
  ].join('\n');
}

function renderStyles(): string {
  return `
:root {
  color-scheme: light;
  --bg: #f7f8fb;
  --panel: #ffffff;
  --ink: #172033;
  --muted: #637083;
  --border: #d9e0ea;
  --brand: #3157d5;
  --brand-soft: #e7edff;
  --accent: #0f9f9a;
  --risk: #b42318;
  --warning: #a15c07;
  --success: #067647;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  color: var(--ink);
  background: var(--bg);
}
.app-shell {
  min-height: 100vh;
  display: grid;
  grid-template-columns: minmax(220px, 280px) minmax(0, 1fr);
}
aside {
  border-right: 1px solid var(--border);
  background: var(--panel);
  padding: 24px 18px;
  position: sticky;
  top: 0;
  height: 100vh;
}
main {
  width: min(1120px, 100%);
  padding: 40px clamp(20px, 5vw, 64px) 72px;
}
.brand { font-size: 16px; font-weight: 800; line-height: 1.2; }
.audience, .eyebrow, .source-meta { color: var(--muted); font-size: 13px; }
.site-nav { display: grid; gap: 6px; margin-top: 24px; }
.site-nav a {
  color: var(--muted);
  text-decoration: none;
  padding: 9px 10px;
  border-radius: 8px;
  font-size: 14px;
}
.site-nav a.active, .site-nav a:hover {
  color: var(--brand);
  background: var(--brand-soft);
}
.page-header {
  border-bottom: 1px solid var(--border);
  padding-bottom: 24px;
  margin-bottom: 28px;
}
h1 { font-size: clamp(34px, 5vw, 58px); line-height: 1.02; margin: 8px 0 0; letter-spacing: 0; }
h2 { font-size: 22px; margin: 0 0 12px; letter-spacing: 0; }
h3 { font-size: 17px; margin: 20px 0 8px; letter-spacing: 0; }
p, li { line-height: 1.65; }
.summary { color: var(--muted); max-width: 860px; font-size: 18px; }
.content-block, .callout, .related, .source-card {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 22px;
  margin: 18px 0;
}
.callout { border-left: 5px solid var(--brand); }
.callout.risk { border-left-color: var(--risk); }
.callout.warning { border-left-color: var(--warning); }
.callout.success { border-left-color: var(--success); }
.metric-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 12px;
}
.metric {
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 16px;
  background: #fbfcff;
}
.metric-value { font-size: 28px; font-weight: 800; color: var(--brand); }
.metric-label { font-weight: 700; margin-top: 4px; }
.metric-detail { color: var(--muted); font-size: 13px; margin-top: 6px; line-height: 1.45; }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; font-size: 14px; }
caption { text-align: left; color: var(--muted); padding-bottom: 10px; }
th, td { border-bottom: 1px solid var(--border); text-align: left; padding: 10px 8px; vertical-align: top; }
th { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
.citation { color: var(--brand); font-weight: 700; text-decoration: none; }
.artifact-ref-card code { display: block; margin-top: 8px; color: var(--brand); }
.related div { display: flex; flex-wrap: wrap; gap: 8px; }
.related a {
  color: var(--brand);
  background: var(--brand-soft);
  border-radius: 999px;
  padding: 6px 10px;
  text-decoration: none;
}
.sources-list { display: grid; gap: 14px; }
.source-id { color: var(--brand); font-weight: 800; font-size: 13px; }
.source-fetches { margin-top: 12px; border-top: 1px dashed var(--border); padding-top: 10px; display: grid; gap: 8px; }
.source-fetch-req { display: block; font-size: 12px; word-break: break-all; background: var(--bg); border-radius: 6px; padding: 4px 8px; }
.source-fetch-meta { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-top: 4px; color: var(--muted); font-size: 12px; }
.source-chip { display: inline-flex; align-items: center; border-radius: 999px; padding: 2px 9px; font-size: 11px; font-weight: 600; }
.source-chip--fresh { background: rgba(6, 118, 71, 0.12); color: var(--success); }
.source-chip--cached { background: rgba(161, 92, 7, 0.12); color: var(--warning); }
.source-chip--hash { background: var(--brand-soft); color: var(--brand); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-weight: 500; cursor: help; }
@media (max-width: 760px) {
  .app-shell { grid-template-columns: 1fr; }
  aside { position: static; height: auto; border-right: 0; border-bottom: 1px solid var(--border); }
  main { padding: 28px 18px 48px; }
}
`.trim();
}

function makeBundleFile(content: string, mimeType: string) {
  return {
    mimeType,
    content,
    size: new TextEncoder().encode(content).byteLength,
  };
}

export function renderAnalysisArtifactSpecToHtmlBundle(spec: AnalysisArtifactSpecV1): BundleManifest {
  const files: BundleManifest['files'] = {
    'styles.css': makeBundleFile(renderStyles(), 'text/css'),
  };

  for (const page of spec.pages) {
    files[slugToFilename(page.slug)] = makeBundleFile(renderPageHtml(spec, page), 'text/html');
  }

  if ((spec.sources || []).length > 0) {
    files['sources.html'] = makeBundleFile(renderSourcesHtml(spec), 'text/html');
  }

  const entryPoint = files['index.html']
    ? 'index.html'
    : slugToFilename(spec.pages[0].slug);

  return {
    version: 1,
    entryPoint,
    files,
  };
}

export function renderAnalysisArtifactSpecToSingleHtml(spec: AnalysisArtifactSpecV1): string {
  const bundle = renderAnalysisArtifactSpecToHtmlBundle(spec);
  const styles = bundle.files['styles.css']?.content || '';
  const pages = spec.pages.map((page) => [
    `<section class="single-page-section" id="${page.slug}">`,
    `<h1>${escapeHtml(page.title)}</h1>`,
    page.summary ? `<p class="summary">${renderInlineMarkdown(page.summary, spec.sources || [])}</p>` : '',
    page.blocks.map((block) => renderBlock(block, spec.sources || [])).join('\n'),
    '</section>',
  ].filter(Boolean).join('\n')).join('\n');

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${escapeHtml(spec.title)}</title>`,
    `<style>${styles}\n.single-page-section { margin-bottom: 40px; }</style>`,
    '</head>',
    '<body>',
    '<main>',
    `<header class="page-header"><p class="eyebrow">${escapeHtml(spec.audience || 'Analysis')}</p><h1>${escapeHtml(spec.title)}</h1><p class="summary">${renderInlineMarkdown(spec.summary, spec.sources || [])}</p></header>`,
    pages,
    (spec.sources || []).length > 0 ? renderSourcesHtml(spec).replace(/^[\s\S]*<main>/, '').replace(/<\/main>[\s\S]*$/, '') : '',
    '</main>',
    '</body>',
    '</html>',
  ].join('\n');
}

function buildSourceMap(sources: AnalysisArtifactSource[]): Map<string, AnalysisArtifactSource> {
  return new Map(sources.map((source) => [source.id, source]));
}

function renderReportCitationMarker(sourceId: string, sourceById: Map<string, AnalysisArtifactSource>): string {
  return sourceById.has(sourceId) ? `[cite:${sourceId}]` : `[${sourceId}]`;
}

function replaceSpecCitationMarkers(
  text: string,
  sourceById: Map<string, AnalysisArtifactSource>,
): string {
  return text.replace(/\[(S\d+)\]/g, (_match, sourceId: string) => (
    renderReportCitationMarker(sourceId, sourceById)
  ));
}

function appendBlockCitationMarkers(
  markdown: string,
  block: AnalysisArtifactBlock,
  sourceById: Map<string, AnalysisArtifactSource>,
  originalText: string,
): string {
  const markers = (block.citations || [])
    .filter((sourceId) => !originalText.includes(`[${sourceId}]`))
    .map((sourceId) => renderReportCitationMarker(sourceId, sourceById));

  if (markers.length === 0) return markdown;
  return `${markdown.trimEnd()} ${markers.join(' ')}`;
}

function collectSourceIdsFromText(text: string | undefined): string[] {
  if (!text) return [];
  return Array.from(new Set(Array.from(text.matchAll(/\[(S\d+)\]/g)).map((match) => match[1])));
}

function mergeSourceIds(...groups: Array<readonly string[] | undefined>): string[] | undefined {
  const merged = Array.from(new Set(groups.flatMap((group) => group ?? []).filter(Boolean)));
  return merged.length > 0 ? merged : undefined;
}

function analysisSourcesToReportSources(sources: AnalysisArtifactSource[]): ReportSource[] {
  return sources.map((source) => ({
    id: source.id,
    label: source.label,
    title: source.title,
    url: source.url,
    retrievedAt: source.retrievedAt,
    sourceArtifactId: source.sourceArtifactId,
    note: source.note,
    // Hard provenance rides along so exports can render the verification panel.
    provenance: source.provenance?.length ? source.provenance.map((fetch) => ({ ...fetch })) : undefined,
  }));
}

function normalizeToneLabel(tone?: AnalysisArtifactCalloutTone): string {
  if (tone === 'success') return 'Success';
  if (tone === 'warning') return 'Warning';
  if (tone === 'risk') return 'Risk';
  return 'Note';
}

function createArtifactReferenceBlock(
  block: Extract<AnalysisArtifactBlock, { kind: 'artifact_ref' }>,
  artifactById: Map<string, Artifact>,
): ReportBlock | null {
  const artifact = artifactById.get(block.artifactId);
  if (!artifact) return null;
  const renderIntent = getRenderIntent(artifact.type, artifact.data, artifact.mimeType);
  if (!renderIntent) return null;

  return {
    kind: 'artifact',
    // Use the RESOLVED artifact's real id (the spec referenced it by filename);
    // downstream exporters resolve report blocks by id.
    artifactId: artifact.id,
    renderIntent,
    caption: block.caption || artifact.name,
    citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.caption)),
  };
}

function ensureTerminalPeriod(text: string): string {
  const trimmed = text.trim();
  return /[.!?)\]]$/.test(trimmed) ? trimmed : `${trimmed}.`;
}

/** "October 7, 2026" from an ISO timestamp (UTC date); passthrough for non-ISO text. */
export function formatAccessDate(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
}

/** "2026-10-07 06:02:41 UTC" from an ISO timestamp; passthrough for non-ISO text. */
export function formatFetchTime(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return `${date.toISOString().slice(0, 19).replace('T', ' ')} UTC`;
}

type MarkdownSegment =
  | { kind: 'heading'; level: 2 | 3; text: string }
  | { kind: 'paragraph'; markdown: string };

/**
 * Promote `#` heading lines inside a markdown block to real heading blocks.
 * Models routinely sub-head prose with `### Search and selection`; as one
 * paragraph block those headings were flattened into the following sentence
 * in every export ("Search and selection Targeted searches…"). As heading
 * blocks they get heading typography, keep-with-next, and PPTX slide titles.
 * `#`/`##` map to the block-title level (2), deeper levels to 3 — the page
 * title is the only level 1. Fenced code is left untouched.
 */
export function splitMarkdownHeadings(markdown: string): MarkdownSegment[] {
  const segments: MarkdownSegment[] = [];
  let buffer: string[] = [];
  let inFence = false;
  const flush = () => {
    const text = buffer.join('\n').trim();
    if (text) segments.push({ kind: 'paragraph', markdown: text });
    buffer = [];
  };
  for (const line of markdown.replace(/\r\n/g, '\n').split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    const heading = inFence ? null : /^\s{0,3}(#{1,6})\s+(.+?)(?:\s+#+)?\s*$/.exec(line);
    if (heading) {
      flush();
      segments.push({ kind: 'heading', level: heading[1].length <= 2 ? 2 : 3, text: heading[2] });
    } else {
      buffer.push(line);
    }
  }
  flush();
  return segments;
}

function blockToReportBlocks(
  block: AnalysisArtifactBlock,
  sourceById: Map<string, AnalysisArtifactSource>,
  artifactById: Map<string, Artifact>,
): ReportBlock[] {
  const blocks: ReportBlock[] = [];
  if (block.title) {
    blocks.push({ kind: 'heading', level: 2, text: block.title });
  }

  if (block.kind === 'markdown') {
    const markdown = appendBlockCitationMarkers(
      replaceSpecCitationMarkers(block.markdown, sourceById),
      block,
      sourceById,
      block.markdown,
    );
    const citations = mergeSourceIds(block.citations, collectSourceIdsFromText(block.markdown));
    const segments = splitMarkdownHeadings(markdown);
    const lastParagraph = segments.map((segment) => segment.kind).lastIndexOf('paragraph');
    segments.forEach((segment, index) => {
      if (segment.kind === 'heading') {
        blocks.push({ kind: 'heading', level: segment.level, text: segment.text });
      } else {
        // Block-level citations ride on the final paragraph only, so endnote
        // suffixes aren't repeated per sub-section.
        blocks.push({ kind: 'paragraph', markdown: segment.markdown, ...(index === lastParagraph && citations ? { citations } : {}) });
      }
    });
  } else if (block.kind === 'callout') {
    const body = replaceSpecCitationMarkers(block.body, sourceById);
    const toneLabel = normalizeToneLabel(block.tone);
    blocks.push({
      kind: 'paragraph',
      markdown: appendBlockCitationMarkers(`> **${toneLabel}:** ${body}`, block, sourceById, block.body),
      citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.body)),
    });
  } else if (block.kind === 'metric_grid') {
    blocks.push({
      kind: 'metric_grid',
      metrics: block.metrics.map((metric) => ({
        label: replaceSpecCitationMarkers(metric.label, sourceById),
        value: metric.value,
        detail: metric.detail ? replaceSpecCitationMarkers(metric.detail, sourceById) : undefined,
      })),
      citations: mergeSourceIds(
        block.citations,
        block.metrics.flatMap((metric) => [
          ...collectSourceIdsFromText(metric.label),
          ...collectSourceIdsFromText(metric.detail),
        ]),
      ),
    });
    if ((block.citations || []).length > 0) {
      blocks.push({
        kind: 'paragraph',
        markdown: `Sources: ${block.citations!.map((sourceId) => renderReportCitationMarker(sourceId, sourceById)).join(' ')}`,
      });
    }
  } else if (block.kind === 'table') {
    blocks.push({
      kind: 'table',
      headers: block.headers,
      rows: block.rows.map((row) => row.map((cell) => replaceSpecCitationMarkers(cell, sourceById))),
      caption: block.caption ? replaceSpecCitationMarkers(block.caption, sourceById) : undefined,
      citations: mergeSourceIds(
        block.citations,
        collectSourceIdsFromText(block.caption),
        block.rows.flatMap((row) => row.flatMap((cell) => collectSourceIdsFromText(cell))),
      ),
    });
    if ((block.citations || []).length > 0) {
      blocks.push({
        kind: 'paragraph',
        markdown: `Sources: ${block.citations!.map((sourceId) => renderReportCitationMarker(sourceId, sourceById)).join(' ')}`,
      });
    }
  } else if (block.kind === 'artifact_ref') {
    const artifactBlock = createArtifactReferenceBlock(block, artifactById);
    if (artifactBlock) {
      blocks.push(artifactBlock);
    } else {
      const caption = block.caption ? replaceSpecCitationMarkers(block.caption, sourceById) : '';
      blocks.push({
        kind: 'paragraph',
        markdown: appendBlockCitationMarkers(
          caption
            ? `${caption}\n\nReferenced artifact: \`${block.artifactId}\``
            : `Referenced artifact: \`${block.artifactId}\``,
          block,
          sourceById,
          block.caption || '',
        ),
        citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.caption)),
      });
    }
  } else if (block.kind === 'chart') {
    blocks.push({
      kind: 'chart',
      spec: block.spec,
      caption: block.caption ? replaceSpecCitationMarkers(block.caption, sourceById) : undefined,
      citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.caption)),
    });
  } else if (block.kind === 'diagram') {
    blocks.push({
      kind: 'diagram',
      spec: block.spec,
      caption: block.caption ? replaceSpecCitationMarkers(block.caption, sourceById) : undefined,
      citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.caption)),
    });
  } else if (block.kind === 'embedded_html') {
    blocks.push({
      kind: 'embedded_html',
      artifactId: block.artifactId,
      caption: block.caption ? replaceSpecCitationMarkers(block.caption, sourceById) : undefined,
      height: block.height,
      citations: mergeSourceIds(block.citations, collectSourceIdsFromText(block.caption)),
    });
  }

  return blocks;
}

export function analysisArtifactSpecToReportSpec(
  spec: AnalysisArtifactSpecV1,
  sessionId: string,
  artifactPool: Artifact[] = [],
  overlay?: PresentationOverlayV1 | null,
): ReportSpecV1 {
  // Charts that name a session file get its rows inline (exports can't load sandbox paths).
  spec = inlineChartDataFiles(spec, chartFileReaderFromArtifacts(artifactPool));
  const now = Date.now();
  const sources = spec.sources || [];
  const sourceById = buildSourceMap(sources);
  // Presentation overlay: page breaks are keyed by stable block id and injected at
  // the spec-block boundary (before each block expands into multiple ReportBlocks),
  // so the break lands in the right place without tracking ids through expansion.
  const pageBreakBeforeBlockIds = new Set(overlay?.pageBreakBeforeBlockIds ?? []);
  // Resolve artifact_ref by id OR by name (the model references figures by the
  // filename it saved). Name keys first so id keys win on collision.
  const artifactById = new Map<string, Artifact>();
  for (const artifact of artifactPool) {
    if (artifact.name) artifactById.set(artifact.name, artifact);
  }
  for (const artifact of artifactPool) {
    artifactById.set(artifact.id, artifact);
  }
  const pages: ReportSpecV1['pages'] = spec.pages.map((page) => ({
    blocks: [
      { kind: 'heading', level: 1, text: page.title } as ReportBlock,
      ...(page.summary ? [{
        kind: 'paragraph',
        markdown: replaceSpecCitationMarkers(page.summary, sourceById),
        citations: mergeSourceIds(collectSourceIdsFromText(page.summary)),
      } as ReportBlock] : []),
      ...page.blocks.flatMap((block) => [
        ...(block.id && pageBreakBeforeBlockIds.has(block.id)
          ? [{ kind: 'page_break' } as ReportBlock]
          : []),
        ...blockToReportBlocks(block, sourceById, artifactById),
      ]),
      ...((page.relatedPageSlugs || []).length > 0
        ? [{
            kind: 'paragraph',
            markdown: `Related pages: ${page.relatedPageSlugs!.map((slug) => {
              const relatedPage = spec.pages.find((candidate) => candidate.slug === slug);
              return relatedPage ? relatedPage.title : slug;
            }).join(', ')}`,
          } as ReportBlock]
        : []),
    ],
  }));

  const abstractText = replaceSpecCitationMarkers(spec.summary, sourceById);

  if (sources.length > 0) {
    // Number the references by inline-citation order so the list lines up with the
    // `[N]` markers the exporters render (numeric_endnotes uses the same order).
    const citationOrder = buildCitationOrder({ abstract: abstractText, pages } as unknown as ReportSpecV1)
      .filter((id) => sourceById.has(id));
    const numberById = new Map(citationOrder.map((id, index) => [id, index + 1]));
    const orderedSources = [
      ...citationOrder.map((id) => sourceById.get(id)!),
      ...sources.filter((source) => !numberById.has(source.id)),
    ];
    // Sources render as stacked reference entries (marker + title line, then the
    // URL on its own full-width line), NOT as a URL column in a table. An ~85-char
    // API URL is one unbreakable token to @react-pdf's line breaker (it only breaks
    // at ASCII spaces), so any fixed-width table cell overflows into the next
    // column; a full-width line is the only place it reliably fits. Standard
    // heading+paragraph blocks, so every exporter carries it with no changes.
    const sourceMarker = (sourceId: string) =>
      numberById.has(sourceId) ? `[${numberById.get(sourceId)}]` : '—';
    // Reference entries read like a bibliography: the full citation, any note,
    // then the link with a human access date (raw ISO timestamps are machine
    // bookkeeping — the exact fetch instant lives in Data Provenance below).
    const referenceBlocks: ReportBlock[] = [
      { kind: 'heading', level: 1, text: 'Sources and Citations' },
      ...orderedSources.map((source) => {
        const citation = ensureTerminalPeriod(source.title || source.label);
        const note = source.note ? ` ${ensureTerminalPeriod(source.note)}` : '';
        const lines = [`**${sourceMarker(source.id)}** ${citation}${note}`];
        const accessed = formatAccessDate(source.retrievedAt);
        if (source.url) lines.push(accessed ? `${source.url} (accessed ${accessed})` : source.url);
        else if (accessed) lines.push(`Accessed ${accessed}.`);
        return { kind: 'paragraph', markdown: lines.join('\n\n') } as ReportBlock;
      }),
    ];

    // Data Provenance appendix: the verifiable hard provenance per cited source
    // (endpoint/method/fetch time/cache status/response fingerprint), baked at
    // spec creation. Same stacked shape: the request line carries the full
    // endpoint, so it gets the full text width. Present only when fetches were
    // actually captured.
    // Entries key to the reference numbers above, so they carry the short
    // label rather than repeating the full citation.
    const provenanceBlocks: ReportBlock[] = orderedSources.flatMap((source) =>
      (source.provenance ?? []).map((fetch) => ({
        kind: 'paragraph',
        markdown: [
          `**${sourceMarker(source.id)}** ${source.label} — fetched ${formatFetchTime(fetch.fetchedAt)} · ${fetch.cacheStatus === 'cached' ? 'served from cache' : 'live response'} · fingerprint ${fetch.responseHash.slice(0, 16)}`,
          `${fetch.method} ${fetch.endpoint}`,
        ].join('\n\n'),
      } as ReportBlock)),
    );
    if (provenanceBlocks.length > 0) {
      referenceBlocks.push(
        { kind: 'heading', level: 2, text: 'Data Provenance' },
        {
          kind: 'paragraph',
          markdown: 'Each entry records the request behind a numbered reference: when it was fetched, whether the response was live or cached, and a fingerprint (hash prefix) of the response body, so every cited figure can be re-fetched and verified.',
        } as ReportBlock,
        ...provenanceBlocks,
      );
    }

    pages.push({ blocks: referenceBlocks });
  }

  const reportSources = analysisSourcesToReportSources(sources);
  const reportTypeId = normalizeReportTypeId(spec.reportTypeId);
  // Formal document types (briefs, memos, audits, handoffs) get a running header;
  // the exporters interpolate the {{title}}/{{date}} tokens.
  const hasCoverChrome = reportTypeHasCoverChrome(reportTypeId);

  return {
    version: 1,
    title: spec.title,
    authors: ['Symposium AI'],
    abstract: abstractText,
    createdAt: now,
    modifiedAt: now,
    sessionId,
    reportTypeId,
    // Presentation base comes from the report type the model stamped on the spec
    // (data_dashboard → landscape, briefs → narrower measure, …); an explicit
    // Layout-menu overlay still wins field-by-field.
    theme: resolveOverlayTheme(overlay?.theme, resolveReportTypeBaseTheme(spec.reportTypeId)),
    pages,
    sources: reportSources.length > 0 ? reportSources : undefined,
    options: {
      citationStyle: sources.length > 0 ? 'numeric_endnotes' : 'none',
      includeProvenanceAppendix: sources.length > 0,
      provenanceDetailLevel: sources.some((source) => source.provenance?.length) ? 'full' : 'brief',
      includeProvenanceAttachment: false,
      header: hasCoverChrome
        ? { enabled: true, left: '{{title}}', center: '', right: '{{date}}' }
        : { enabled: false, left: '', center: '', right: '' },
      footer: { enabled: true, left: '', center: '{{pageNumber}} / {{totalPages}}', right: formatBrandingLine() },
      branding: DEFAULT_ARTIFACT_BRANDING_OPTIONS,
    },
  };
}
