// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { Artifact } from '../../../types/notebook';
import type { PresentationOverlayV1, PresentationThemeOverride } from '../../../types/presentation-overlay';
import type { ReportTheme } from '../../../types/report-spec';
import { DEFAULT_THEME } from '../../reports/constants';
import { decodePossiblyBase64Json } from '../../../lib/encoding/utf8Base64';

/** Deterministic id so editing a report's overlay upserts (ADD_ARTIFACT) in place. */
export function overlayArtifactId(lineageRootId: string): string {
  return `presentation_overlay_${lineageRootId}`;
}

export function emptyOverlay(lineageRootId: string): PresentationOverlayV1 {
  return {
    version: 1,
    kind: 'presentation_overlay',
    lineageRootId,
    pageBreakBeforeBlockIds: [],
  };
}

export function parseOverlay(artifact: Artifact): PresentationOverlayV1 | null {
  if (artifact.type !== 'presentation_overlay') return null;
  try {
    const parsed = JSON.parse(decodePossiblyBase64Json(artifact.data));
    if (parsed && parsed.kind === 'presentation_overlay' && typeof parsed.lineageRootId === 'string') {
      return {
        version: 1,
        kind: 'presentation_overlay',
        lineageRootId: parsed.lineageRootId,
        theme: parsed.theme,
        pageBreakBeforeBlockIds: Array.isArray(parsed.pageBreakBeforeBlockIds) ? parsed.pageBreakBeforeBlockIds : [],
      };
    }
  } catch {
    // fall through
  }
  return null;
}

/** Find the overlay for a report lineage (by deterministic id or lineage metadata). */
export function findOverlayForLineage(lineageRootId: string, artifacts: Artifact[]): PresentationOverlayV1 | null {
  const id = overlayArtifactId(lineageRootId);
  const artifact = artifacts.find(
    (a) => a.type === 'presentation_overlay' && (a.id === id || a.metadata?.lineageRootId === lineageRootId),
  );
  return artifact ? parseOverlay(artifact) : null;
}

export function buildOverlayArtifact(
  overlay: PresentationOverlayV1,
  sessionId: string,
  now: number = Date.now(),
): Artifact {
  return {
    id: overlayArtifactId(overlay.lineageRootId),
    cellId: 'overlay',
    sessionId,
    name: 'presentation.overlay.json',
    type: 'presentation_overlay',
    mimeType: 'application/json',
    data: JSON.stringify(overlay),
    createdAt: now,
    metadata: { lineageRootId: overlay.lineageRootId },
  };
}

/**
 * Merge a partial theme override over a base theme (nested fields merge). The base is the
 * report type's presentation base (resolveReportTypeBaseTheme) when the caller has one;
 * explicit Layout-menu choices always win field-by-field.
 */
export function resolveOverlayTheme(
  override?: PresentationThemeOverride | null,
  base: ReportTheme = DEFAULT_THEME,
): ReportTheme {
  return {
    pageSize: override?.pageSize ?? base.pageSize,
    landscape: override?.landscape ?? base.landscape,
    margins: { ...base.margins, ...override?.margins },
    fonts: { ...base.fonts, ...override?.fonts },
    colors: { ...base.colors, ...override?.colors },
  };
}
