// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * Content-Hashing Utilities
 *
 * Shared SHA-256 hashing and stable serialization for content-addressing
 * artifacts (report specs, map specs, etc.).
 */

import type { CanonicalReportSpecV1 } from '../types/report-spec';

/**
 * Compute SHA-256 hex digest of a string.
 * Falls back to 'unavailable' if crypto.subtle is not present.
 */
export async function sha256(input: string): Promise<string> {
  if (typeof crypto !== 'undefined' && crypto.subtle) {
    const encoder = new TextEncoder();
    const hashBuffer = await crypto.subtle.digest('SHA-256', encoder.encode(input));
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  }
  return 'unavailable';
}

/**
 * Recursively sort object keys for deterministic serialization.
 * Arrays are preserved in order; only plain-object keys are sorted.
 */
function sortKeysDeep(val: unknown): unknown {
  if (val === null || val === undefined || typeof val !== 'object') return val;
  if (Array.isArray(val)) return val.map(sortKeysDeep);

  const obj = val as Record<string, unknown>;
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = sortKeysDeep(obj[key]);
  }
  return sorted;
}

/**
 * Stable JSON serialization with recursively sorted keys.
 * Produces deterministic output regardless of property insertion order.
 */
export function stableSerialize(value: unknown): string {
  return JSON.stringify(sortKeysDeep(value));
}

/**
 * Content-address a canonical report spec.
 *
 * Hashing rule (A2): the hash input is the canonical spec with `createdAt`
 * stripped, so that re-publishing an edited spec produces a new ID only
 * when the actual content changes. The full canonical spec (including
 * `createdAt`) is stored as the artifact data.
 *
 * Returns `report_spec:<sha256>`.
 */
export async function contentAddressReportSpec(
  spec: CanonicalReportSpecV1,
): Promise<{ id: string; hash: string; serialized: string }> {
  // Strip createdAt for hash (it doesn't change between edits)
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { createdAt, __brand, ...hashInput } = spec as CanonicalReportSpecV1 & { __brand?: unknown };
  const hashSerialized = stableSerialize(hashInput);
  const hash = await sha256(hashSerialized);

  // Full canonical spec for storage (includes createdAt)
  const fullSerialized = stableSerialize(spec);

  return {
    id: `report_spec:${hash}`,
    hash,
    serialized: fullSerialized,
  };
}
