// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import { ARTIFACT_BRANDING, DEFAULT_ARTIFACT_BRANDING_OPTIONS } from '../../config/artifact-branding';
import { isLikelyGeoMapHtml, repairModelAuthoredHtml } from '../artifacts/htmlProfiles';
import type { Artifact } from '../../types/notebook';
import type {
  ArtifactBrandingOptions,
  ArtifactBrandingRecord,
  ArtifactBrandingVisibility,
  HtmlBrandingMode,
} from '../../types/branding';
import type { BundleManifest } from '../../types/notebook';

export { ARTIFACT_BRANDING, DEFAULT_ARTIFACT_BRANDING_OPTIONS };

export const HTML_BRANDING_MARKER = 'data-symposium-artifact-branding';
export const HTML_BRAND_SHELL_MARKER = 'data-symposium-html-brand-shell';
const HTML_BRAND_SHELL_STYLE_MARKER = 'data-symposium-html-brand-shell-style';
const HTML_DOCUMENT_KIT_STYLE_MARKER = 'data-symposium-document-kit-style';

export interface HtmlBrandingContext {
  mode?: HtmlBrandingMode;
  artifactName?: string;
  filename?: string;
  profile?: Artifact['profile'];
}

export interface SymposiumExportManifest {
  version: 1;
  generatedAt: string;
  source: string;
  branding: ArtifactBrandingRecord;
  artifacts?: Array<{
    id: string;
    name: string;
    type: Artifact['type'];
    mimeType: string;
  }>;
}

export function normalizeArtifactBrandingOptions(
  options?: ArtifactBrandingOptions | null,
): Required<ArtifactBrandingOptions> {
  return {
    ...DEFAULT_ARTIFACT_BRANDING_OPTIONS,
    ...(options ?? {}),
  };
}

export function isVisibleBranding(options?: ArtifactBrandingOptions | null): boolean {
  return normalizeArtifactBrandingOptions(options).visibility === 'visible';
}

export function shouldWriteBrandingMetadata(options?: ArtifactBrandingOptions | null): boolean {
  const visibility = normalizeArtifactBrandingOptions(options).visibility;
  return visibility === 'visible' || visibility === 'metadata';
}

export function createArtifactBrandingRecord(
  options?: ArtifactBrandingOptions | null,
  appliedAt: Date = new Date(),
): ArtifactBrandingRecord {
  const resolved = normalizeArtifactBrandingOptions(options);
  return {
    version: ARTIFACT_BRANDING.version,
    visibility: resolved.visibility,
    brandName: ARTIFACT_BRANDING.brandName,
    attribution: ARTIFACT_BRANDING.attribution,
    url: ARTIFACT_BRANDING.url,
    logoPath: ARTIFACT_BRANDING.logoPath,
    appliedAt: appliedAt.toISOString(),
  };
}

export function formatBrandingLine(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  if (!resolved.includeUrl) return ARTIFACT_BRANDING.attribution;
  return `${ARTIFACT_BRANDING.attribution} | ${ARTIFACT_BRANDING.hostLabel}`;
}

export function formatGeneratedByLine(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  if (!resolved.includeUrl) return ARTIFACT_BRANDING.generatedBy;
  return `${ARTIFACT_BRANDING.generatedBy} (${ARTIFACT_BRANDING.hostLabel})`;
}

export function formatBrandingMarkdown(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  if (!resolved.includeUrl) return `*${ARTIFACT_BRANDING.attribution}*`;
  return `*${ARTIFACT_BRANDING.attribution}: [${ARTIFACT_BRANDING.brandName}](${ARTIFACT_BRANDING.url})*`;
}

export function svgToDataUri(svg = ARTIFACT_BRANDING.logoSvg): string {
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function htmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function injectBeforeBodyClose(html: string, insertion: string): string {
  const bodyCloseIdx = lastIndexOfIgnoreCase(html, '</body>');
  if (bodyCloseIdx !== -1) {
    return html.slice(0, bodyCloseIdx) + insertion + html.slice(bodyCloseIdx);
  }

  const htmlCloseIdx = lastIndexOfIgnoreCase(html, '</html>');
  if (htmlCloseIdx !== -1) {
    return html.slice(0, htmlCloseIdx) + insertion + html.slice(htmlCloseIdx);
  }

  return `${html}${insertion}`;
}

function injectIntoHead(html: string, insertion: string): string {
  const headIdx = indexOfIgnoreCase(html, '<head>');
  if (headIdx !== -1) {
    const insertPos = headIdx + '<head>'.length;
    return html.slice(0, insertPos) + insertion + html.slice(insertPos);
  }

  const htmlIdx = searchIgnoreCase(html, /<html\b/);
  if (htmlIdx !== -1) {
    const closeTag = html.indexOf('>', htmlIdx);
    if (closeTag !== -1) {
      const insertPos = closeTag + 1;
      return html.slice(0, insertPos) + `<head>${insertion}</head>` + html.slice(insertPos);
    }
  }

  return `${insertion}${html}`;
}

function injectBeforeHeadClose(html: string, insertion: string): string {
  const headCloseIdx = indexOfIgnoreCase(html, '</head>');
  if (headCloseIdx !== -1) {
    return html.slice(0, headCloseIdx) + insertion + html.slice(headCloseIdx);
  }

  return injectIntoHead(html, insertion);
}

function indexOfIgnoreCase(value: string, search: string): number {
  return value.toLowerCase().indexOf(search.toLowerCase());
}

function lastIndexOfIgnoreCase(value: string, search: string): number {
  return value.toLowerCase().lastIndexOf(search.toLowerCase());
}

function searchIgnoreCase(value: string, pattern: RegExp): number {
  const match = pattern.exec(value);
  return match?.index ?? -1;
}

function buildHtmlBrandingStyle(): string {
  return `<style data-symposium-artifact-branding-style>
.symposium-artifact-branding{box-sizing:border-box;width:100%;margin:32px 0 0;padding:12px 16px;border-top:1px solid ${ARTIFACT_BRANDING.colors.border};background:${ARTIFACT_BRANDING.colors.background};color:${ARTIFACT_BRANDING.colors.muted};font:12px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:center;letter-spacing:0}
.symposium-artifact-branding a{color:${ARTIFACT_BRANDING.colors.text};text-decoration:none;font-weight:600}
.symposium-artifact-branding__inner{display:inline-flex;align-items:center;justify-content:center;gap:8px;max-width:100%}
.symposium-artifact-branding__logo{width:18px;height:18px;border-radius:4px;display:block;flex:0 0 auto}
</style>`;
}

function buildHtmlBrandingFooter(options?: ArtifactBrandingOptions | null): string {
  const resolved = normalizeArtifactBrandingOptions(options);
  const logo = resolved.includeLogo
    ? `<img class="symposium-artifact-branding__logo" alt="" src="${svgToDataUri()}" />`
    : '';
  const line = htmlEscape(formatBrandingLine(options));
  const url = htmlEscape(ARTIFACT_BRANDING.url);

  return `<footer ${HTML_BRANDING_MARKER}="visible" class="symposium-artifact-branding"><div class="symposium-artifact-branding__inner">${logo}<a href="${url}" target="_blank" rel="noopener noreferrer">${line}</a></div></footer>`;
}

function stripTags(value: string): string {
  return value
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function decodeBasicEntities(value: string): string {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function prettifyName(value: string): string {
  const filename = value.split(/[\\/]/).pop() || value;
  const withoutExtension = filename.replace(/\.[^.]+$/, '');
  const pretty = withoutExtension
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  return pretty.replace(/\b\w/g, (char) => char.toUpperCase());
}

function deriveHtmlReportTitle(html: string, context: HtmlBrandingContext): string {
  const h1Match = /<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(html);
  const titleMatch = /<title\b[^>]*>([\s\S]*?)<\/title>/i.exec(html);
  const candidates = [
    h1Match?.[1] ? decodeBasicEntities(stripTags(h1Match[1])) : '',
    titleMatch?.[1] ? decodeBasicEntities(stripTags(titleMatch[1])) : '',
    context.artifactName ? prettifyName(context.artifactName) : '',
    context.filename ? prettifyName(context.filename) : '',
  ].filter(Boolean);

  return candidates[0] || 'Analysis Report';
}

function normalizeHeadingText(value: string): string {
  return decodeBasicEntities(stripTags(value))
    .replace(/[‘’]/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function removeDuplicateShellTitleHeading(html: string, title: string): string {
  const normalizedTitle = normalizeHeadingText(title);
  if (!normalizedTitle) return html;

  return html.replace(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i, (fullMatch, headingContent: string) => {
    return normalizeHeadingText(headingContent) === normalizedTitle ? '' : fullMatch;
  });
}

export function isVisualizationHeavyHtml(html: string): boolean {
  const patterns = [
    /\bPlotly\.newPlot\b/i,
    /\bplotly(?:\.js|-graph-div|_plot)\b/i,
    /\bBokeh\b|\bbk-root\b|data-root-id\s*=/i,
    /\bvegaEmbed\b|\bvega-embed\b|\bvega-lite\b/i,
    /\bfolium-map\b|\bleaflet\b|\bL\.map\s*\(/i,
    /\bmapboxgl\b|\bmaplibregl\b|\bnew\s+ol\.Map\b|\bdeck\.gl\b/i,
    /id\s*=\s*["']map(?:_[^"']*)?["'][\s\S]{0,800}(?:height\s*:\s*100%|position\s*:\s*absolute)/i,
    /(?:html|body)\s*\{[^}]*height\s*:\s*100%[^}]*overflow\s*:\s*hidden/i,
  ];

  return patterns.some((pattern) => pattern.test(html));
}

function buildHtmlReportShellStyle(): string {
  const { colors } = ARTIFACT_BRANDING;
  return `<style ${HTML_BRAND_SHELL_STYLE_MARKER} ${HTML_DOCUMENT_KIT_STYLE_MARKER}>
:root{color-scheme:light}
body.symposium-report-shell-body{margin:0;background:#eef2f7;color:#172033;font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Inter,Arial,sans-serif;letter-spacing:0}
body.symposium-report-shell-body *{box-sizing:border-box}
.symposium-report-shell{min-height:100vh;padding:28px;background:linear-gradient(180deg,#f8fafc 0%,#eef2f7 100%)}
.symposium-report-shell__frame{max-width:1080px;margin:0 auto;background:#fff;border:1px solid ${colors.border};border-radius:18px;box-shadow:0 18px 50px rgba(15,23,42,.08);overflow:hidden}
.symposium-report-shell__header{padding:26px 30px 22px;border-bottom:1px solid ${colors.border};background:linear-gradient(135deg,#ffffff 0%,#f8fafc 68%,rgba(99,102,241,.08) 100%)}
.symposium-report-shell__brand{display:flex;align-items:center;gap:10px;margin-bottom:16px;color:${colors.muted};font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}
.symposium-report-shell__brand img{width:24px;height:24px;border-radius:7px;display:block}
.symposium-report-shell__title{margin:0;color:#0f172a;font-size:28px;line-height:1.18;font-weight:760;letter-spacing:0}
.symposium-report-shell__meta{margin:8px 0 0;color:${colors.muted};font-size:13px}
.symposium-report-shell__content{padding:30px;max-width:100%;overflow-wrap:anywhere}
.symposium-report-shell__content>:first-child{margin-top:0}
.symposium-report-shell__content h1,.symposium-report-shell__content h2,.symposium-report-shell__content h3{color:#0f172a;line-height:1.25;letter-spacing:0}
.symposium-report-shell__content h1{font-size:28px;margin:0 0 18px}
.symposium-report-shell__content h2{font-size:21px;margin:34px 0 12px;padding-top:6px;border-top:1px solid #edf2f7}
.symposium-report-shell__content h3{font-size:17px;margin:24px 0 10px}
.symposium-report-shell__content p,.symposium-report-shell__content li{color:#334155}
.symposium-report-shell__content a{color:${colors.primary};font-weight:600;text-decoration:none}
.symposium-report-shell__content a:hover{text-decoration:underline}
.symposium-report-shell__content table{width:100%;border-collapse:collapse;margin:18px 0;border:1px solid ${colors.border};border-radius:10px;overflow:hidden;font-size:14px}
.symposium-report-shell__content th{background:#f8fafc;color:#0f172a;text-align:left;font-weight:700}
.symposium-report-shell__content th,.symposium-report-shell__content td{padding:10px 12px;border-bottom:1px solid ${colors.border};vertical-align:top}
.symposium-report-shell__content tr:last-child td{border-bottom:0}
.symposium-report-shell__content .symposium-doc-kicker{margin:0 0 8px;color:${colors.primary};font-size:12px;font-weight:800;letter-spacing:0;text-transform:uppercase}
.symposium-report-shell__content .symposium-doc-meta{display:flex;flex-wrap:wrap;gap:8px 14px;margin:8px 0 20px;color:${colors.muted};font-size:13px}
.symposium-report-shell__content .symposium-doc-toc{margin:18px 0 24px;padding:14px 16px;border:1px solid ${colors.border};border-radius:8px;background:#f8fafc}
.symposium-report-shell__content .symposium-doc-toc ol,.symposium-report-shell__content .symposium-doc-toc ul{margin:8px 0 0;padding-left:20px}
.symposium-report-shell__content .symposium-doc-toc li{margin:4px 0;color:#334155}
.symposium-report-shell__content .symposium-doc-metric-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:18px 0}
.symposium-report-shell__content .symposium-doc-metric{min-width:0;padding:14px;border:1px solid ${colors.border};border-radius:8px;background:#fff}
.symposium-report-shell__content .symposium-doc-metric__label{margin:0;color:${colors.muted};font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0}
.symposium-report-shell__content .symposium-doc-metric__value{margin:4px 0 0;color:#0f172a;font-size:24px;line-height:1.15;font-weight:760}
.symposium-report-shell__content .symposium-doc-metric__delta{margin:6px 0 0;color:#475569;font-size:12px}
.symposium-report-shell__content .symposium-doc-callout{margin:18px 0;padding:14px 16px;border:1px solid ${colors.border};border-left:4px solid ${colors.primary};border-radius:8px;background:#f8fafc;color:#334155}
.symposium-report-shell__content .symposium-doc-callout[data-tone="risk"],.symposium-report-shell__content .symposium-doc-callout.is-risk{border-left-color:#dc2626;background:#fff7f7}
.symposium-report-shell__content .symposium-doc-callout[data-tone="success"],.symposium-report-shell__content .symposium-doc-callout.is-success{border-left-color:#16a34a;background:#f0fdf4}
.symposium-report-shell__content .symposium-doc-callout[data-tone="warning"],.symposium-report-shell__content .symposium-doc-callout.is-warning{border-left-color:#d97706;background:#fffbeb}
.symposium-report-shell__content .symposium-doc-evidence{margin:16px 0;padding:12px 14px;border:1px solid ${colors.border};border-radius:8px;background:#fbfdff;color:#334155}
.symposium-report-shell__content .symposium-doc-evidence__source{display:block;margin-top:8px;color:${colors.muted};font-size:12px;font-weight:700}
.symposium-report-shell__content .symposium-doc-risk-matrix{width:100%;margin:18px 0;border:1px solid ${colors.border};border-radius:8px;overflow:hidden}
.symposium-report-shell__content table.symposium-doc-risk-matrix,.symposium-report-shell__content .symposium-doc-risk-matrix table{margin:0;border:0;border-radius:0}
.symposium-report-shell__content .symposium-doc-figure{margin:20px 0}
.symposium-report-shell__content .symposium-doc-figure>figcaption,.symposium-report-shell__content figcaption.symposium-doc-caption{margin-top:8px;color:${colors.muted};font-size:12px;line-height:1.45}
.symposium-report-shell__content .symposium-doc-source-list{margin:18px 0;padding:14px 16px;border:1px solid ${colors.border};border-radius:8px;background:#f8fafc}
.symposium-report-shell__content .symposium-doc-source-list li{margin:6px 0}
.symposium-report-shell__content table.symposium-doc-table--compact{font-size:12px}
.symposium-report-shell__content table.symposium-doc-table--compact th,.symposium-report-shell__content table.symposium-doc-table--compact td{padding:7px 8px}
.symposium-report-shell__content .symposium-doc-page-break{break-before:page;height:0;margin:0;padding:0;border:0}
.symposium-report-shell__content blockquote,.symposium-report-shell__content .callout,.symposium-report-shell__content .card{margin:18px 0;padding:14px 16px;border:1px solid ${colors.border};border-left:4px solid ${colors.primary};border-radius:10px;background:#f8fafc;color:#334155}
.symposium-report-shell__content img,.symposium-report-shell__content svg,.symposium-report-shell__content canvas{max-width:100%;height:auto}
.symposium-report-shell__content code{border-radius:5px;background:#f1f5f9;padding:2px 5px;color:#1e293b}
.symposium-report-shell__content pre{overflow:auto;border-radius:10px;background:#0f172a;color:#e2e8f0;padding:14px}
.symposium-artifact-branding{box-sizing:border-box;width:100%;margin:0;padding:14px 18px;border-top:1px solid ${colors.border};background:${colors.background};color:${colors.muted};font:12px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;text-align:center;letter-spacing:0}
.symposium-artifact-branding a{color:${colors.text};text-decoration:none;font-weight:600}
.symposium-artifact-branding__inner{display:inline-flex;align-items:center;justify-content:center;gap:8px;max-width:100%}
.symposium-artifact-branding__logo{width:18px;height:18px;border-radius:4px;display:block;flex:0 0 auto}
@media (max-width:640px){.symposium-report-shell{padding:12px}.symposium-report-shell__header,.symposium-report-shell__content{padding-left:18px;padding-right:18px}.symposium-report-shell__content .symposium-doc-meta{display:block}.symposium-report-shell__content .symposium-doc-metric__value{font-size:21px}}
@media print{body.symposium-report-shell-body{background:#fff;color:#111827;font-size:11pt}.symposium-report-shell{min-height:0;padding:0;background:#fff}.symposium-report-shell__frame{max-width:none;border:0;border-radius:0;box-shadow:none}.symposium-report-shell__header{position:static;padding:0 0 14pt;background:#fff;border-bottom:1px solid #d1d5db}.symposium-report-shell__content{padding:18pt 0 0}.symposium-report-shell__brand{color:#4b5563}.symposium-report-shell__title{font-size:22pt}.symposium-report-shell__content table,.symposium-report-shell__content figure,.symposium-report-shell__content blockquote,.symposium-report-shell__content .callout,.symposium-report-shell__content .card,.symposium-report-shell__content .symposium-doc-toc,.symposium-report-shell__content .symposium-doc-metric,.symposium-report-shell__content .symposium-doc-callout,.symposium-report-shell__content .symposium-doc-evidence,.symposium-report-shell__content .symposium-doc-source-list,.symposium-artifact-branding{break-inside:avoid}.symposium-report-shell__content .symposium-doc-page-break{break-before:page}.symposium-report-shell__content a{color:#111827;text-decoration:underline}.symposium-artifact-branding{background:#fff;padding:10pt 0 0}}
</style>`;
}

function buildHtmlReportShellOpening(title: string): string {
  return `<div ${HTML_BRAND_SHELL_MARKER}="v1" class="symposium-report-shell"><div class="symposium-report-shell__frame"><header class="symposium-report-shell__header"><div class="symposium-report-shell__brand"><img alt="" src="${svgToDataUri()}" /><span>${htmlEscape(ARTIFACT_BRANDING.brandName)}</span></div><div class="symposium-report-shell__title">${htmlEscape(title)}</div><p class="symposium-report-shell__meta">Generated analysis report</p></header><main class="symposium-report-shell__content">`;
}

function buildHtmlReportShellClosing(options?: ArtifactBrandingOptions | null, includeFooter = true): string {
  const footer = includeFooter ? buildHtmlBrandingFooter(options) : '';
  return `</main>${footer}</div></div>`;
}

function withReportShellStyle(html: string): string {
  if (html.includes(HTML_BRAND_SHELL_STYLE_MARKER)) return html;
  return injectBeforeHeadClose(html, buildHtmlReportShellStyle());
}

function enhanceBodyTag(bodyTag: string): string {
  let next = bodyTag;
  if (/\bclass\s*=/.test(next)) {
    next = next.replace(/\bclass\s*=\s*(["'])(.*?)\1/i, (_match, quote: string, classes: string) => {
      const classList = classes.split(/\s+/).filter(Boolean);
      if (!classList.includes('symposium-report-shell-body')) {
        classList.push('symposium-report-shell-body');
      }
      return `class=${quote}${classList.join(' ')}${quote}`;
    });
  } else {
    next = next.replace(/<body\b/i, '<body class="symposium-report-shell-body"');
  }

  if (!/\bdata-symposium-html-brand-surface=/.test(next)) {
    next = next.replace(/<body\b/i, '<body data-symposium-html-brand-surface="report"');
  }

  return next;
}

function wrapFullHtmlDocumentWithReportShell(
  html: string,
  title: string,
  options?: ArtifactBrandingOptions | null,
): string | null {
  const bodyOpenMatch = /<body\b[^>]*>/i.exec(html);
  if (!bodyOpenMatch || bodyOpenMatch.index === undefined) return null;

  const styledHtml = withReportShellStyle(html);
  const styledBodyMatch = /<body\b[^>]*>/i.exec(styledHtml);
  if (!styledBodyMatch || styledBodyMatch.index === undefined) return null;

  const bodyStart = styledBodyMatch.index;
  const bodyTag = styledBodyMatch[0];
  const afterBodyTag = styledHtml.slice(bodyStart + bodyTag.length);
  const bodyCloseIndex = lastIndexOfIgnoreCase(afterBodyTag, '</body>');
  if (bodyCloseIndex === -1) return null;
  const bodyContent = removeDuplicateShellTitleHeading(
    afterBodyTag.slice(0, bodyCloseIndex),
    title,
  );

  const hasFooter = styledHtml.includes(`${HTML_BRANDING_MARKER}="visible"`);
  return [
    styledHtml.slice(0, bodyStart),
    enhanceBodyTag(bodyTag),
    buildHtmlReportShellOpening(title),
    bodyContent,
    buildHtmlReportShellClosing(options, !hasFooter),
    afterBodyTag.slice(bodyCloseIndex),
  ].join('');
}

function buildReportShellDocumentFromFragment(
  html: string,
  title: string,
  options?: ArtifactBrandingOptions | null,
): string {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    `<title>${htmlEscape(title)}</title>`,
    buildHtmlReportShellStyle(),
    '</head>',
    '<body class="symposium-report-shell-body" data-symposium-html-brand-surface="report">',
    buildHtmlReportShellOpening(title),
    removeDuplicateShellTitleHeading(html, title),
    buildHtmlReportShellClosing(options),
    '</body>',
    '</html>',
  ].join('');
}

function shouldUseReportShell(html: string, context: HtmlBrandingContext): boolean {
  if (context.profile === 'ARCHIVE_PORTABLE') return false;
  if (isVisualizationHeavyHtml(html)) return false;
  return context.mode === 'report_shell_v1' || context.mode === 'auto' || !context.mode;
}

export function applyBrandingToHtml(
  html: string,
  options?: ArtifactBrandingOptions | null,
): string {
  if (!isVisibleBranding(options) || !html.trim()) return html;
  if (html.includes(`${HTML_BRANDING_MARKER}="visible"`)) return html;
  // Defense in depth: geo maps are full-bleed; an injected footer overlaps the map. Never brand them.
  if (isLikelyGeoMapHtml(html)) return html;

  const withStyle = html.includes('data-symposium-artifact-branding-style')
    ? html
    : injectIntoHead(html, buildHtmlBrandingStyle());

  return injectBeforeBodyClose(withStyle, buildHtmlBrandingFooter(options));
}

export function finalizeHtmlArtifactBranding(
  html: string,
  options?: ArtifactBrandingOptions | null,
  context: HtmlBrandingContext = {},
): string {
  // Before any branding decision: old stored artifacts can still carry hallucinated
  // SRI hashes (the strip runs at render + creation, but pre-fix artifacts persist).
  // Every finalized copy — downloads, ZIP bundles, new-tab — must lose them or the
  // standalone file breaks (browser blocks leaflet.css → scattered map tiles).
  html = repairModelAuthoredHtml(html);
  if (!isVisibleBranding(options) || !html.trim()) return html;
  if (html.includes(`${HTML_BRAND_SHELL_MARKER}="v1"`)) return html;
  // Geo maps are full-bleed surfaces; injecting a branding footer overlaps the map and
  // corrupts the container geometry Leaflet relies on. Leave maps unbranded entirely.
  if (isLikelyGeoMapHtml(html)) return html;
  if (context.mode === 'footer_only' || !shouldUseReportShell(html, context)) {
    return applyBrandingToHtml(html, options);
  }

  const title = deriveHtmlReportTitle(html, context);
  return wrapFullHtmlDocumentWithReportShell(html, title, options)
    ?? buildReportShellDocumentFromFragment(html, title, options);
}

export function applyBrandingToBundleManifest(
  manifest: BundleManifest,
  options?: ArtifactBrandingOptions | null,
  context: Omit<HtmlBrandingContext, 'filename'> = {},
): BundleManifest {
  if (!isVisibleBranding(options)) return manifest;

  const files: BundleManifest['files'] = {};
  for (const [path, file] of Object.entries(manifest.files)) {
    if (file.mimeType === 'text/html' && !file.isBase64) {
      const content = finalizeHtmlArtifactBranding(file.content, options, {
        ...context,
        filename: path,
      });
      files[path] = {
        ...file,
        content,
        size: content.length,
      };
    } else {
      files[path] = { ...file };
    }
  }

  return {
    ...manifest,
    files,
  };
}

export function createSymposiumExportManifest({
  artifacts,
  source,
  branding,
}: {
  artifacts?: Artifact[];
  source: string;
  branding?: ArtifactBrandingOptions | null;
}): SymposiumExportManifest {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    source,
    branding: createArtifactBrandingRecord(branding),
    artifacts: artifacts?.map((artifact) => ({
      id: artifact.id,
      name: artifact.name,
      type: artifact.type,
      mimeType: artifact.mimeType,
    })),
  };
}

export function toArtifactBrandingVisibility(value: string): ArtifactBrandingVisibility {
  if (value === 'metadata' || value === 'off') return value;
  return 'visible';
}
