// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { Artifact } from '../../types/notebook';

export type ArtifactDisposition = NonNullable<NonNullable<Artifact['metadata']>['artifactDisposition']>;
export type ReportMaterialRole = NonNullable<NonNullable<Artifact['metadata']>['reportMaterialRole']>;

export function getArtifactDisposition(artifact: Artifact): ArtifactDisposition {
  return artifact.metadata?.artifactDisposition ?? 'output';
}

export function isReportMaterialArtifact(artifact: Artifact): boolean {
  return getArtifactDisposition(artifact) === 'report_material';
}

export function isOutputVisibleArtifact(artifact: Artifact): boolean {
  return !isReportMaterialArtifact(artifact);
}

// Source/config artifacts that are NOT finished deliverables and would break a session if
// deleted: the editable report, its publish bridge, and its layout overlay.
const REPORT_SOURCE_TYPES = new Set<string>(['analysis_artifact_spec', 'report_spec', 'presentation_overlay']);

/**
 * The Library shows finished, shareable deliverables only — Create images and Analyze
 * exports (PDF/PPTX/DOCX/HTML, the data workbook). It excludes report-material backing
 * (figures/datasets/HTML a report references) and the report's source/config artifacts,
 * so deleting from the Library can't break an analysis session.
 */
export function isLibraryDeliverable(artifact: Artifact): boolean {
  return isOutputVisibleArtifact(artifact) && !REPORT_SOURCE_TYPES.has(artifact.type);
}

export function filterOutputVisibleArtifacts(artifacts: Artifact[]): Artifact[] {
  return artifacts.filter(isOutputVisibleArtifact);
}

export function getReportMaterialRole(artifact: Artifact): ReportMaterialRole | null {
  return artifact.metadata?.reportMaterialRole ?? null;
}

export function resolveReportMaterialsForOutput(outputArtifact: Artifact, artifactPool: Artifact[]): Artifact[] {
  const outputGroupId = outputArtifact.metadata?.artifactGroupId;
  return artifactPool.filter((artifact) => {
    if (!isReportMaterialArtifact(artifact)) return false;
    if (artifact.metadata?.sourceOutputArtifactId === outputArtifact.id) return true;
    return Boolean(outputGroupId && artifact.metadata?.artifactGroupId === outputGroupId);
  });
}

export function resolveReportMaterialsForGroup(artifactGroupId: string | null | undefined, artifactPool: Artifact[]): Artifact[] {
  if (!artifactGroupId) return [];
  return artifactPool.filter((artifact) => (
    isReportMaterialArtifact(artifact)
    && artifact.metadata?.artifactGroupId === artifactGroupId
  ));
}
