// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import { decodePossiblyBase64Json, decodeBase64ToUtf8 } from '../../lib/encoding/utf8Base64';
import type { Artifact, ArtifactPreviewMetadata, BundleManifest } from '../../types/notebook';

const MAX_EXCERPT_CHARS = 360;
const MAX_CODE_LINES = 10;
const MAX_TABLE_COLUMNS = 5;
const MAX_TABLE_ROWS = 4;
const MAX_CELL_CHARS = 80;

type PreviewInput = Pick<Artifact, 'name' | 'type' | 'mimeType' | 'data' | 'metadata'>;

function compactWhitespace(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function truncate(value: string, maxChars: number): string {
  const normalized = compactWhitespace(value);
  if (normalized.length <= maxChars) return normalized;
  return `${normalized.slice(0, Math.max(0, maxChars - 1)).trimEnd()}...`;
}

function truncateMultiline(value: string, maxChars: number): string {
  const trimmed = value.trim();
  if (trimmed.length <= maxChars) return trimmed;
  return `${trimmed.slice(0, Math.max(0, maxChars - 1)).trimEnd()}...`;
}

function stripMarkdown(value: string): string {
  return value
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/!\[[^\]]*]\([^)]+\)/g, ' ')
    .replace(/\[([^\]]+)]\([^)]+\)/g, '$1')
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^\s*[-*+]\s+/gm, '')
    .replace(/^\s*\d+\.\s+/gm, '');
}

/** Repeat a removal until nothing matches, so removing one span can't splice a new one together. */
function removeAll(value: string, pattern: RegExp, replacement: string): string {
  let previous: string;
  let current = value;
  do {
    previous = current;
    current = current.replace(pattern, replacement);
  } while (current !== previous);
  return current;
}

/** Plain text for preview titles and excerpts (rendered as text, never as HTML). */
function stripHtml(value: string): string {
  let text = removeAll(value, /<script\b[\s\S]*?<\/script\s*>/gi, ' ');
  text = removeAll(text, /<style\b[\s\S]*?<\/style\s*>/gi, ' ');
  // &amp; last, so "&amp;lt;" decodes once to "&lt;", not twice to "<".
  return removeAll(text, /<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/gi, '&');
}

function maybeDecodeText(data: string, mimeType: string): string {
  if (!data) return '';
  if (
    mimeType.startsWith('text/')
    || mimeType === 'application/json'
    || mimeType === 'application/javascript'
    || mimeType === 'image/svg+xml'
  ) {
    if (data.includes('\n') || data.includes('<') || data.trimStart().startsWith('{') || data.trimStart().startsWith('[')) {
      return data;
    }
    try {
      return decodeBase64ToUtf8(data);
    } catch {
      return data;
    }
  }
  return data;
}

function scalarCell(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return truncate(JSON.stringify(value), MAX_CELL_CHARS);
  return truncate(String(value), MAX_CELL_CHARS);
}

function tablePreviewFromRows(
  rows: Record<string, unknown>[],
  columns?: string[],
): ArtifactPreviewMetadata['table'] | undefined {
  if (rows.length === 0 && (!columns || columns.length === 0)) return undefined;

  const columnNames = (columns && columns.length > 0)
    ? columns
    : Array.from(rows.reduce((set, row) => {
        Object.keys(row).forEach((key) => set.add(key));
        return set;
      }, new Set<string>()));

  const visibleColumns = columnNames.slice(0, MAX_TABLE_COLUMNS);
  return {
    columns: visibleColumns,
    rows: rows.slice(0, MAX_TABLE_ROWS).map((row) => visibleColumns.map((column) => scalarCell(row[column]))),
    totalRows: rows.length,
    totalColumns: columnNames.length,
  };
}

function parseJsonTablePreview(text: string): {
  table?: ArtifactPreviewMetadata['table'];
  excerpt?: string;
} {
  const parsed = JSON.parse(decodePossiblyBase64Json(text));
  if (Array.isArray(parsed)) {
    const rows = parsed.filter((entry): entry is Record<string, unknown> => (
      !!entry && typeof entry === 'object' && !Array.isArray(entry)
    ));
    return { table: tablePreviewFromRows(rows) };
  }
  if (parsed && typeof parsed === 'object') {
    return {
      table: tablePreviewFromRows([parsed as Record<string, unknown>]),
      excerpt: JSON.stringify(parsed, null, 2),
    };
  }
  return { excerpt: String(parsed) };
}

function parseDelimitedTablePreview(text: string, delimiter: ',' | '\t'): ArtifactPreviewMetadata['table'] | undefined {
  const lines = text.split(/\r?\n/).filter((line) => line.trim());
  if (lines.length === 0) return undefined;
  const splitLine = (line: string) => line.split(delimiter).map((cell) => cell.trim().replace(/^"|"$/g, ''));
  const columns = splitLine(lines[0]);
  const rows = lines.slice(1, 1 + MAX_TABLE_ROWS).map((line) => splitLine(line));
  return {
    columns: columns.slice(0, MAX_TABLE_COLUMNS),
    rows: rows.map((row) => row.slice(0, MAX_TABLE_COLUMNS).map((cell) => truncate(cell, MAX_CELL_CHARS))),
    totalRows: Math.max(0, lines.length - 1),
    totalColumns: columns.length,
  };
}

function titleFromHtml(html: string): string | undefined {
  const title = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1];
  if (title) return truncate(stripHtml(title), 100);
  const h1 = /<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1];
  if (h1) return truncate(stripHtml(h1), 100);
  return undefined;
}

function bundleEntryHtml(manifest: BundleManifest): { html: string; filename: string } | null {
  const entry = manifest.files[manifest.entryPoint];
  if (entry?.mimeType === 'text/html') {
    return { html: entry.content, filename: manifest.entryPoint };
  }
  const firstHtml = Object.entries(manifest.files).find(([, file]) => file.mimeType === 'text/html');
  if (!firstHtml) return null;
  return { filename: firstHtml[0], html: firstHtml[1].content };
}

function reportPreviewFromJson(input: PreviewInput, text: string): ArtifactPreviewMetadata | undefined {
  try {
    const parsed = JSON.parse(decodePossiblyBase64Json(text)) as {
      title?: unknown;
      summary?: unknown;
      abstract?: unknown;
      audience?: unknown;
      pages?: unknown[];
      sources?: unknown[];
    };
    const title = typeof parsed.title === 'string' ? parsed.title : input.name;
    const summary = typeof parsed.summary === 'string'
      ? parsed.summary
      : typeof parsed.abstract === 'string'
        ? parsed.abstract
        : '';

    return {
      version: 1,
      kind: 'report',
      title: truncate(title, 120),
      subtitle: typeof parsed.audience === 'string' ? truncate(parsed.audience, 80) : input.type.replace(/_/g, ' '),
      excerpt: summary ? truncate(stripMarkdown(summary), MAX_EXCERPT_CHARS) : undefined,
      metrics: [
        ...(Array.isArray(parsed.pages) ? [{ label: 'Pages', value: String(parsed.pages.length) }] : []),
        ...(Array.isArray(parsed.sources) ? [{ label: 'Sources', value: String(parsed.sources.length) }] : []),
      ],
    };
  } catch {
    return undefined;
  }
}

function dataPreview(input: PreviewInput, text: string): ArtifactPreviewMetadata | undefined {
  try {
    if (input.mimeType === 'application/json') {
      const parsed = parseJsonTablePreview(text);
      return {
        version: 1,
        kind: parsed.table ? 'table' : 'text',
        title: input.name,
        subtitle: parsed.table
          ? `${parsed.table.totalRows ?? 0} rows x ${parsed.table.totalColumns ?? 0} cols`
          : input.mimeType,
        excerpt: parsed.excerpt ? truncate(parsed.excerpt, MAX_EXCERPT_CHARS) : undefined,
        table: parsed.table,
      };
    }

    if (input.mimeType === 'text/csv' || input.mimeType === 'text/tab-separated-values') {
      const table = parseDelimitedTablePreview(text, input.mimeType === 'text/tab-separated-values' ? '\t' : ',');
      return {
        version: 1,
        kind: table ? 'table' : 'text',
        title: input.name,
        subtitle: table ? `${table.totalRows ?? 0} rows x ${table.totalColumns ?? 0} cols` : input.mimeType,
        table,
        excerpt: table ? undefined : truncate(text, MAX_EXCERPT_CHARS),
      };
    }
  } catch {
    return undefined;
  }

  if (input.mimeType.startsWith('text/') || input.mimeType === 'application/json') {
    return {
      version: 1,
      kind: 'text',
      title: input.name,
      subtitle: input.mimeType,
      excerpt: truncate(stripMarkdown(text), MAX_EXCERPT_CHARS),
    };
  }

  return undefined;
}

function documentPreview(input: PreviewInput): ArtifactPreviewMetadata | undefined {
  if (input.type === 'document_pdf' || input.mimeType === 'application/pdf') {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'PDF document' };
  }
  if (input.type === 'document_pptx' || input.mimeType.includes('presentationml')) {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'PowerPoint deck' };
  }
  if (input.type === 'document_docx') {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'Word document' };
  }
  if (input.type === 'document_html') {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'Interactive HTML' };
  }
  if (input.mimeType.includes('spreadsheet') || input.mimeType.includes('ms-excel')) {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'Spreadsheet' };
  }
  if (input.mimeType.includes('wordprocessingml') || input.mimeType === 'application/rtf') {
    return { version: 1, kind: 'document', title: input.name, subtitle: 'Document' };
  }
  return undefined;
}

export function buildArtifactPreviewMetadata(input: PreviewInput): ArtifactPreviewMetadata | undefined {
  if (!input.data) {
    return documentPreview(input);
  }

  if (input.type === 'image' || input.mimeType.startsWith('image/')) {
    return {
      version: 1,
      kind: 'image',
      title: input.name,
      subtitle: input.metadata?.dimensions || input.mimeType,
    };
  }

  const text = maybeDecodeText(input.data, input.mimeType);

  if (input.type === 'analysis_artifact_spec' || input.type === 'report_spec') {
    return reportPreviewFromJson(input, text) ?? {
      version: 1,
      kind: 'report',
      title: input.name,
      excerpt: truncate(stripMarkdown(text), MAX_EXCERPT_CHARS),
    };
  }

  if (input.type === 'document_pdf' || input.type === 'document_pptx' || input.type === 'document_docx' || input.type === 'document_html') {
    return documentPreview(input);
  }

  if (input.type === 'artifact_bundle') {
    try {
      const manifest = JSON.parse(text) as BundleManifest;
      const entry = bundleEntryHtml(manifest);
      const htmlTitle = entry ? titleFromHtml(entry.html) : undefined;
      const excerpt = entry ? stripHtml(entry.html) : '';
      return {
        version: 1,
        kind: 'bundle',
        title: htmlTitle || input.name,
        subtitle: `${Object.keys(manifest.files || {}).length} files`,
        excerpt: excerpt ? truncate(excerpt, MAX_EXCERPT_CHARS) : undefined,
      };
    } catch {
      return {
        version: 1,
        kind: 'bundle',
        title: input.name,
        subtitle: input.metadata?.bundleFileCount ? `${input.metadata.bundleFileCount} files` : undefined,
      };
    }
  }

  if (input.type === 'html' || input.mimeType === 'text/html') {
    return {
      version: 1,
      kind: 'html',
      title: titleFromHtml(text) || input.name,
      subtitle: input.metadata?.externalDomains?.length
        ? `${input.metadata.externalDomains.length} external domains`
        : 'HTML page',
      excerpt: truncate(stripHtml(text), MAX_EXCERPT_CHARS),
    };
  }

  if (input.type === 'code') {
    const lines = text.trim().split(/\r?\n/).slice(0, MAX_CODE_LINES).join('\n');
    return {
      version: 1,
      kind: 'code',
      title: input.name,
      subtitle: input.metadata?.language || 'code',
      excerpt: truncateMultiline(lines, MAX_EXCERPT_CHARS),
    };
  }

  if (
    input.type === 'dataset'
    || input.type === 'table'
    || input.type === 'data'
    || input.mimeType === 'text/csv'
    || input.mimeType === 'text/tab-separated-values'
    || input.mimeType === 'application/json'
  ) {
    return dataPreview(input, text) ?? documentPreview(input);
  }

  if (input.mimeType.startsWith('text/')) {
    return {
      version: 1,
      kind: 'text',
      title: input.name,
      subtitle: input.mimeType,
      excerpt: truncate(stripMarkdown(text), MAX_EXCERPT_CHARS),
    };
  }

  return documentPreview(input);
}

export function withArtifactPreviewMetadata<T extends Artifact>(artifact: T): T {
  if (artifact.metadata?.preview) return artifact;
  const preview = buildArtifactPreviewMetadata(artifact);
  if (!preview) return artifact;
  return {
    ...artifact,
    metadata: {
      ...artifact.metadata,
      preview,
    },
  };
}
