// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
import type { BundleManifest } from '../../types/notebook';

const SEMANTIC_DOCUMENT_PATTERNS = [
  /<\s*(?:article|main|section|header|footer|aside|nav)\b/i,
  /<\s*h[1-6]\b/i,
  /<\s*p\b/i,
  /<\s*(?:ul|ol|dl|li)\b/i,
  /<\s*(?:table|thead|tbody|tr|th|td)\b/i,
  /<\s*(?:blockquote|figure|figcaption)\b/i,
];

const INTERACTIVE_RUNTIME_PATTERNS = [
  /<\s*script\b/i,
  /\son[a-z]+\s*=/i,
  /\bhref\s*=\s*["']\s*javascript:/i,
  /<\s*canvas\b/i,
  /<\s*(?:form|input|select|textarea)\b/i,
  /\bPlotly\.newPlot\b/i,
  /\bplotly(?:\.js|-graph-div|_plot)\b/i,
  /\bBokeh\b|\bbk-root\b|data-root-id\s*=/i,
  /\bvegaEmbed\b|\bvega-embed\b|\bvega-lite\b/i,
  /\bfolium-map\b|\bleaflet\b|\bL\.map\s*\(/i,
  /\bmapboxgl\b|\bmaplibregl\b|\bnew\s+ol\.Map\b|\bdeck\.gl\b/i,
  /\b(?:addEventListener|requestAnimationFrame|setInterval|setTimeout)\s*\(/i,
  /\b(?:localStorage|sessionStorage|indexedDB)\b/i,
  /id\s*=\s*["']map(?:_[^"']*)?["'][\s\S]{0,800}(?:height\s*:\s*100%|position\s*:\s*absolute)/i,
  /(?:html|body)\s*\{[^}]*height\s*:\s*100%[^}]*overflow\s*:\s*hidden/i,
];

export function hasSemanticDocumentHtml(content: string): boolean {
  return SEMANTIC_DOCUMENT_PATTERNS.some((pattern) => pattern.test(content));
}

/**
 * Remove Subresource Integrity (`integrity`) attributes from an HTML string.
 *
 * LLM-authored artifacts frequently ship a hallucinated / mismatched SRI hash on a CDN
 * `<link>` or `<script>` (e.g. `leaflet.css`). When the hash doesn't match, the browser BLOCKS
 * the resource entirely — a Leaflet map then loads its JS but not its CSS, so its tiles are never
 * absolutely positioned and scatter across the page. Models cannot reliably produce SRI hashes,
 * so this is a recurring, provider-agnostic failure. These artifacts are already sandbox-isolated,
 * so SRI adds negligible security here; dropping `integrity` lets the resource load normally. A
 * bare `crossorigin` (without `integrity`) is harmless, so we leave it.
 */
export function stripSubresourceIntegrity(html: string): string {
  if (!html || !html.includes('integrity')) return html;
  // Attribute values can't contain their surrounding quote, so the non-greedy classes are safe;
  // the last alternative covers an unquoted value.
  return html.replace(/\s+integrity\s*=\s*("[^"]*"|'[^']*'|[^\s"'>]+)/gi, '');
}

/** Every repair model-authored HTML gets before it is stored, rendered, or published. */
export function repairModelAuthoredHtml(html: string): string {
  return stripSubresourceIntegrity(html);
}

/**
 * Same repairs for base64-stored HTML (document_html artifacts on binary download
 * paths). atob yields a latin-1 binary string whose bytes round-trip through btoa
 * unchanged, and the repair only rewrites ASCII spans, so multibyte UTF-8
 * content is untouched.
 */
export function repairModelAuthoredBase64Html(base64: string): string {
  try {
    const binary = atob(base64);
    if (!binary.includes('integrity')) return base64;
    return btoa(repairModelAuthoredHtml(binary));
  } catch {
    return base64;
  }
}

export function hasInteractiveHtmlRuntime(content: string): boolean {
  return INTERACTIVE_RUNTIME_PATTERNS.some((pattern) => pattern.test(content));
}

export function isLikelyGeoMapHtml(content: string): boolean {
  const lower = content.toLowerCase();
  return (
    lower.includes('scattergeo') ||
    lower.includes('choropleth') ||
    lower.includes('scattermapbox') ||
    lower.includes('choroplethmapbox') ||
    lower.includes('scattermap') ||
    lower.includes('choroplethmap') ||
    lower.includes('folium') ||
    lower.includes('leaflet') ||
    lower.includes('maplibre') ||
    lower.includes('mapboxgl') ||
    lower.includes('openlayers') ||
    lower.includes('ol.map') ||
    lower.includes('deck.gl')
  );
}

function getHtmlBundleFiles(data: string): string[] {
  try {
    const manifest = JSON.parse(data) as BundleManifest;
    if (!manifest?.files) return [];
    return Object.values(manifest.files)
      .filter((file) => file.mimeType === 'text/html' && !file.isBase64)
      .map((file) => file.content);
  } catch {
    return [];
  }
}

export function getHtmlLikeContents(
  type: 'html' | 'artifact_bundle',
  data: string,
): string[] {
  if (type === 'html') return [data];
  return getHtmlBundleFiles(data);
}

export function hasInteractiveHtmlLikeRuntime(
  type: 'html' | 'artifact_bundle',
  data: string,
): boolean {
  return getHtmlLikeContents(type, data).some(hasInteractiveHtmlRuntime);
}

export function hasSemanticHtmlLikeDocument(
  type: 'html' | 'artifact_bundle',
  data: string,
): boolean {
  return getHtmlLikeContents(type, data).some(hasSemanticDocumentHtml);
}

export function artifactContainsGeoMapHtml(data: string, type: 'html' | 'artifact_bundle'): boolean {
  return getHtmlLikeContents(type, data).some(isLikelyGeoMapHtml);
}
