// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * InlineBundlerService
 *
 * Pure-function service that takes a BundleManifest and a target HTML filename,
 * and returns self-contained HTML with all CSS/JS/images inlined from the bundle.
 *
 * This avoids the need for a Service Worker to resolve relative URLs within
 * sandboxed iframes (which have opaque origins and can't be SW-controlled).
 */

import type { BundleManifest } from '../../types/notebook';
import { finalizeHtmlArtifactBranding } from '../branding/ArtifactBrandingService';

export interface BundleOutputLike {
  name?: string;
  manifest: BundleManifest;
  sourceFiles?: string[];
}

export interface BundleHtmlOutputItem {
  content: string;
  filename: string;
}

/**
 * Resolve a file from the manifest, returning its content.
 * For base64-encoded binary files, returns the raw base64.
 * For text files, returns the text content.
 */
function normalizePathSegments(path: string): string {
  const segments: string[] = [];
  for (const part of path.split('/')) {
    if (!part || part === '.') continue;
    if (part === '..') {
      segments.pop();
    } else {
      segments.push(part);
    }
  }
  return segments.join('/');
}

export function normalizeBundlePathKey(path?: string | null): string | null {
  const trimmed = path?.trim();
  if (!trimmed || /^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(trimmed)) return null;

  const withoutQuery = trimmed.split(/[?#]/)[0];
  const withoutOutputPrefix = withoutQuery.replace(/^\/output\//i, '');
  const withoutLeadingSlash = withoutOutputPrefix.replace(/^\/+/, '');
  const normalized = normalizePathSegments(withoutLeadingSlash);
  return normalized || null;
}

function dirname(path: string): string {
  const index = path.lastIndexOf('/');
  return index === -1 ? '' : path.slice(0, index);
}

function resolveBundleReference(
  manifest: BundleManifest,
  reference: string,
  fromFilename?: string,
): string | null {
  if (/^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(reference)) return null;

  const stripped = reference.split(/[?#]/)[0].trim();
  if (!stripped) return null;

  const withoutOutputPrefix = stripped.replace(/^\/output\//i, '');
  const candidates: string[] = [];

  if (withoutOutputPrefix.startsWith('/')) {
    candidates.push(normalizePathSegments(withoutOutputPrefix.slice(1)));
  } else {
    const baseDir = fromFilename ? dirname(fromFilename) : '';
    candidates.push(normalizePathSegments(baseDir ? `${baseDir}/${withoutOutputPrefix}` : withoutOutputPrefix));
    candidates.push(normalizePathSegments(withoutOutputPrefix.replace(/^\.\//, '')));
  }

  return candidates.find((candidate) => Boolean(manifest.files[candidate])) ?? null;
}

function getFileContent(manifest: BundleManifest, filename: string): string | null {
  const file = manifest.files[filename];
  if (!file) return null;
  return file.content;
}

/**
 * Build a data URI from a bundle file.
 */
function toDataUri(manifest: BundleManifest, reference: string, fromFilename?: string): string | null {
  const filename = resolveBundleReference(manifest, reference, fromFilename);
  if (!filename) return null;

  const file = manifest.files[filename];
  if (!file) return null;

  if (file.isBase64) {
    return `data:${file.mimeType};base64,${file.content}`;
  }
  // Text content — encode to base64 for data URI
  try {
    const encoded = btoa(file.content);
    return `data:${file.mimeType};base64,${encoded}`;
  } catch {
    // btoa fails on non-Latin1 chars — use encodeURIComponent fallback
    return `data:${file.mimeType},${encodeURIComponent(file.content)}`;
  }
}

/**
 * Inline CSS @import directives recursively.
 * Depth-limited to prevent infinite loops.
 */
function inlineCssImports(
  css: string,
  manifest: BundleManifest,
  cssFilename?: string,
  depth: number = 0
): string {
  if (depth >= 3) return css;

  // @import "file.css" or @import url("file.css")
  return css.replace(
    /@import\s+(?:url\s*\(\s*)?["']([^"']+)["'](?:\s*\))?\s*;/gi,
    (fullMatch, importPath) => {
      if (/^https?:/i.test(importPath)) return fullMatch; // Leave external imports
      const normalized = resolveBundleReference(manifest, importPath, cssFilename);
      if (!normalized) return fullMatch;

      const content = getFileContent(manifest, normalized);
      if (!content) return fullMatch; // File not in bundle, leave as-is
      // Recursively inline nested imports
      const inlined = inlineCssImports(content, manifest, normalized, depth + 1);
      return `/* inlined: ${normalized} */\n${inlined}\n`;
    }
  );
}

/**
 * Replace CSS url() references with data URIs for files in the bundle.
 */
function inlineCssUrls(css: string, manifest: BundleManifest, fromFilename?: string): string {
  return css.replace(
    /url\(\s*["']?([^"')]+)["']?\s*\)/gi,
    (fullMatch, urlPath) => {
      if (/^(https?:|data:|blob:)/i.test(urlPath)) return fullMatch;
      const dataUri = toDataUri(manifest, urlPath, fromFilename);
      if (!dataUri) return fullMatch; // Not in bundle
      return `url("${dataUri}")`;
    }
  );
}

/**
 * Process a CSS string: inline @imports and url() references.
 */
function processCSS(css: string, manifest: BundleManifest, cssFilename?: string): string {
  let result = inlineCssImports(css, manifest, cssFilename);
  result = inlineCssUrls(result, manifest, cssFilename);
  return result;
}

/**
 * Inline all CSS, JS, and image dependencies from a bundle into an HTML page.
 *
 * Transformations:
 * - <link rel="stylesheet" href="style.css"> → <style>/* contents *\/</style>
 * - <script src="app.js"></script> → <script>/* contents *\/</script>
 * - <img src="chart.png"> → <img src="data:image/png;base64,...">
 * - CSS url(filename) → data: URIs
 * - CSS @import "file.css" → inlined recursively (depth limit 3)
 * - <a href="page2.html"> → left intact (handled by postMessage navigation)
 * - External URLs → left intact (not in bundle)
 *
 * Only inlines files that exist in the manifest. Missing references are left as-is.
 */
export function inlineBundlePage(
  manifest: BundleManifest,
  htmlFilename: string
): string {
  const htmlFile = manifest.files[htmlFilename];
  if (!htmlFile || htmlFile.mimeType !== 'text/html') {
    return '';
  }

  let html = htmlFile.content;

  // 1. Inline <link rel="stylesheet" href="...">
  html = html.replace(
    /<link\s+([^>]*?)rel\s*=\s*["']stylesheet["']([^>]*?)href\s*=\s*["']([^"']+)["']([^>]*?)\/?>/gi,
    (fullMatch, _pre, _mid, href) => {
      if (/^https?:/i.test(href)) return fullMatch;
      const normalized = resolveBundleReference(manifest, href, htmlFilename);
      if (!normalized) return fullMatch;
      const content = getFileContent(manifest, normalized);
      if (!content) return fullMatch;
      const processed = processCSS(content, manifest, normalized);
      return `<style>/* inlined: ${normalized} */\n${processed}\n</style>`;
    }
  );

  // Also handle <link href="..." rel="stylesheet"> (reversed attribute order)
  html = html.replace(
    /<link\s+([^>]*?)href\s*=\s*["']([^"']+)["']([^>]*?)rel\s*=\s*["']stylesheet["']([^>]*?)\/?>/gi,
    (fullMatch, _pre, href) => {
      if (/^https?:/i.test(href)) return fullMatch;
      const normalized = resolveBundleReference(manifest, href, htmlFilename);
      if (!normalized) return fullMatch;
      const content = getFileContent(manifest, normalized);
      if (!content) return fullMatch;
      const processed = processCSS(content, manifest, normalized);
      return `<style>/* inlined: ${normalized} */\n${processed}\n</style>`;
    }
  );

  // 2. Inline <script src="..."></script>
  html = html.replace(
    /<script\s+([^>]*?)src\s*=\s*["']([^"']+)["']([^>]*?)>\s*<\/script>/gi,
    (fullMatch, _pre, src) => {
      if (/^https?:/i.test(src)) return fullMatch;
      const normalized = resolveBundleReference(manifest, src, htmlFilename);
      if (!normalized) return fullMatch;
      const content = getFileContent(manifest, normalized);
      if (!content) return fullMatch;
      return `<script>/* inlined: ${normalized} */\n${content}\n</script>`;
    }
  );

  // 3. Inline <img src="..."> with data URIs
  html = html.replace(
    /(<img\s+[^>]*?)src\s*=\s*["']([^"']+)["']/gi,
    (fullMatch, prefix, src) => {
      if (/^(https?:|data:|blob:)/i.test(src)) return fullMatch;
      const dataUri = toDataUri(manifest, src, htmlFilename);
      if (!dataUri) return fullMatch;
      return `${prefix}src="${dataUri}"`;
    }
  );

  // 4. Inline CSS url() references in <style> blocks
  html = html.replace(
    /(<style[^>]*>)([\s\S]*?)(<\/style>)/gi,
    (fullMatch, openTag, cssContent, closeTag) => {
      const processed = inlineCssUrls(cssContent, manifest, htmlFilename);
      return `${openTag}${processed}${closeTag}`;
    }
  );

  // 5. Inline CSS url() in inline style="" attributes
  html = html.replace(
    /style\s*=\s*["']([^"']*url\([^)]+\)[^"']*)["']/gi,
    (fullMatch, styleContent) => {
      const processed = inlineCssUrls(styleContent, manifest, htmlFilename);
      return `style="${processed}"`;
    }
  );

  // 6. Normalize local HTML links to manifest keys so iframe navigation can
  // resolve pages written inside /output subdirectories.
  html = html.replace(
    /(<a\s+[^>]*?)href\s*=\s*["']([^"']+\.html(?:[?#][^"']*)?)["']/gi,
    (fullMatch, prefix, href) => {
      if (/^(https?:|javascript:|mailto:|#)/i.test(href)) return fullMatch;
      const resolved = resolveBundleReference(manifest, href, htmlFilename);
      if (!resolved) return fullMatch;
      return `${prefix}href="${resolved}"`;
    }
  );

  return finalizeHtmlArtifactBranding(html, undefined, {
    mode: 'auto',
    filename: htmlFilename,
  });
}

export function bundleOutputsToHtmlOutputs(
  bundleOutputs?: BundleOutputLike[]
): BundleHtmlOutputItem[] {
  if (!bundleOutputs || bundleOutputs.length === 0) return [];

  const outputs: BundleHtmlOutputItem[] = [];
  const seen = new Set<string>();

  for (const bundle of bundleOutputs) {
    const htmlFilenames = Object.entries(bundle.manifest.files)
      .filter(([, file]) => file.mimeType === 'text/html')
      .map(([filename]) => filename);
    const entryPoint = normalizeBundlePathKey(bundle.manifest.entryPoint);

    htmlFilenames.sort((a, b) => {
      const aKey = normalizeBundlePathKey(a);
      const bKey = normalizeBundlePathKey(b);
      if (aKey === entryPoint) return -1;
      if (bKey === entryPoint) return 1;
      return 0;
    });

    for (const filename of htmlFilenames) {
      const key = normalizeBundlePathKey(filename);
      if (!key || seen.has(key)) continue;
      const content = inlineBundlePage(bundle.manifest, filename);
      if (!content) continue;
      seen.add(key);
      outputs.push({ content, filename: key });
    }
  }

  return outputs;
}

export function bundleOutputHtmlFilenameSet(
  bundleOutputs?: BundleOutputLike[]
): Set<string> {
  const filenames = new Set<string>();
  if (!bundleOutputs) return filenames;

  for (const bundle of bundleOutputs) {
    for (const [filename, file] of Object.entries(bundle.manifest.files)) {
      if (file.mimeType !== 'text/html') continue;
      const normalized = normalizeBundlePathKey(filename);
      if (normalized) filenames.add(normalized);
    }

    for (const sourceFile of bundle.sourceFiles || []) {
      const normalized = normalizeBundlePathKey(sourceFile);
      if (normalized && /\.html?$/i.test(normalized)) {
        filenames.add(normalized);
      }
    }
  }

  return filenames;
}
