// GENERATED by symposium-ai-web scripts/sync-analyze-contract.mjs. Do not edit by hand.
/**
 * PolicyGateService
 *
 * Pure-function service that validates artifacts against security policies.
 * Runs at artifact creation (audit mode) and render time (enforce mode).
 */

import type { Artifact, ArtifactProfile, BundleManifest, PolicyReport, PolicyViolation } from '../../types/notebook';

interface PolicyRule {
  id: string;
  pattern: RegExp;
  severity: 'error' | 'warning';
  message: string;
  profiles?: ArtifactProfile[];
  /** Profiles for which this rule is escalated from its base severity to 'error'. */
  errorProfiles?: ArtifactProfile[];
}

/**
 * Security rules for HTML artifact content.
 * Errors block rendering in enforce mode; warnings are informational.
 */
const HTML_POLICY_RULES: PolicyRule[] = [
  {
    id: 'no-fetch',
    pattern: /\bfetch\s*\(/g,
    severity: 'error',
    message: 'Network requests via fetch() are not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'no-xmlhttprequest',
    pattern: /new\s+XMLHttpRequest/g,
    severity: 'error',
    message: 'Network requests via XMLHttpRequest are not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'no-websocket',
    pattern: /new\s+WebSocket/g,
    severity: 'error',
    message: 'WebSocket connections are not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'no-eventsource',
    pattern: /new\s+EventSource/g,
    severity: 'error',
    message: 'EventSource connections are not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'no-external-script',
    pattern: /<script[^>]+src\s*=\s*["']https?:\/\//gi,
    severity: 'error',
    message: 'External script loading is not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'no-external-css',
    pattern: /<link[^>]+href\s*=\s*["']https?:\/\/[^"']*\.css/gi,
    severity: 'error',
    message: 'External CSS loading is not allowed in portable artifacts',
    profiles: ['ARCHIVE_PORTABLE'],
  },
  {
    id: 'window-open',
    pattern: /window\.open\s*\(/g,
    severity: 'warning',
    message: 'window.open() may not work in sandboxed context',
  },
  {
    id: 'document-domain',
    pattern: /document\.domain/g,
    severity: 'warning',
    message: 'document.domain manipulation detected',
  },
  {
    id: 'postmessage-wildcard',
    pattern: /postMessage\([^)]+,\s*['"][*]['"]\)/g,
    severity: 'warning',
    message: 'postMessage with wildcard origin detected',
    // Air-gapped portable artifacts must not broadcast to '*' — escalate to a blocking error.
    errorProfiles: ['ARCHIVE_PORTABLE'],
  },
];

function ruleAppliesToProfile(rule: PolicyRule, profile?: ArtifactProfile): boolean {
  if (!rule.profiles || rule.profiles.length === 0) return true;
  if (!profile) return true;
  return rule.profiles.includes(profile);
}

function effectiveSeverity(rule: PolicyRule, profile?: ArtifactProfile): 'error' | 'warning' {
  if (profile && rule.errorProfiles?.includes(profile)) return 'error';
  return rule.severity;
}

/**
 * Validate an artifact against security policies.
 *
 * @param artifact - The artifact to validate (needs at minimum type, data, and optionally profile)
 * @param mode - 'enforce' blocks on errors, 'audit' always passes but reports violations
 * @returns PolicyReport with pass/fail status and violation details
 */
export function validateArtifact(
  artifact: Pick<Artifact, 'type' | 'data'> & { profile?: ArtifactProfile },
  mode: 'enforce' | 'audit'
): PolicyReport {
  // Legacy artifacts (no profile) always run in audit mode
  const effectiveMode = artifact.profile ? mode : 'audit';
  const violations: PolicyViolation[] = [];

  if (artifact.type === 'html') {
    for (const rule of HTML_POLICY_RULES) {
      if (!ruleAppliesToProfile(rule, artifact.profile)) continue;
      // Reset lastIndex for global regexes
      rule.pattern.lastIndex = 0;
      const matches = artifact.data.match(rule.pattern);
      if (matches && matches.length > 0) {
        violations.push({
          rule: rule.id,
          severity: effectiveSeverity(rule, artifact.profile),
          message: rule.message,
          location: `${matches.length} occurrence${matches.length > 1 ? 's' : ''}`,
        });
      }
    }
  }

  if (artifact.type === 'artifact_bundle') {
    try {
      const manifest: BundleManifest = JSON.parse(artifact.data);
      for (const [filename, file] of Object.entries(manifest.files)) {
        if (file.mimeType !== 'text/html') continue;
        for (const rule of HTML_POLICY_RULES) {
          if (!ruleAppliesToProfile(rule, artifact.profile)) continue;
          rule.pattern.lastIndex = 0;
          const matches = file.content.match(rule.pattern);
          if (matches && matches.length > 0) {
            violations.push({
              rule: rule.id,
              severity: effectiveSeverity(rule, artifact.profile),
              message: `${rule.message} (in ${filename})`,
              location: `${matches.length} occurrence${matches.length > 1 ? 's' : ''}`,
            });
          }
        }
      }
    } catch {
      violations.push({
        rule: 'invalid-bundle-manifest',
        severity: 'error',
        message: 'Bundle manifest is not valid JSON',
      });
    }
  }

  const hasErrors = violations.some(v => v.severity === 'error');
  const auditOnly = effectiveMode === 'audit';

  return {
    passed: auditOnly || !hasErrors,
    violations,
    checkedAt: Date.now(),
    auditOnly,
  };
}
